// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "package:intl_data_gen/bin/intl_data_gen.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.iterable.data.ET;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/cldr_template.dart';

final symbols = new IterableSymbols(start: new SeparatorTemplate(separator: ', '), 
middle: new SeparatorTemplate(separator: ', '), 
end: new SeparatorTemplate(separator: ' ja '), 
two: new SeparatorTemplate(separator: ' ja '));

