// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "package:intl_data_gen/bin/intl_data_gen.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.CHR;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"{0} ᎠᏎᏢ","other":"{0} ᏗᏎᏢ"},
      "MINUTE": {"one":"{0} ᎢᏯᏔᏬᏍᏔᏅ","other":"{0} ᎢᏧᏔᏬᏍᏔᏅ"},
      "HOUR": {"one":"{0} ᏑᏣᎶᏓ","other":"{0} ᎢᏧᏣᎶᏓ"},
      "DAY": {"one":"{0} ᏏᎦ","other":"{0} ᏧᏒᎯᏓ"},
      "WEEK": {"one":"{0} ᏒᎾᏙᏓᏆᏍᏗ","other":"{0} ᎢᏳᎾᏙᏓᏆᏍᏗ"},
      "MONTH": {"one":"{0} ᏏᏅᏓ","other":"{0} ᎢᏯᏅᏓ"},
      "YEAR": {"one":"{0} ᏑᏕᏘᏴᏓ","other":"{0} ᏧᏕᏘᏴᏓ"}
    },
      shortUnits: {
      "SECOND": {},
      "MINUTE": {},
      "HOUR": {},
      "DAY": {},
      "WEEK": {},
      "MONTH": {},
      "YEAR": {}
    },
      pastUnits: {
      "SECOND": {"other":"-{0} s"},
      "MINUTE": {"other":"-{0} min"},
      "HOUR": {"other":"-{0} h"},
      "DAY": {"other":"-{0} d"},
      "WEEK": {"other":"-{0} w"},
      "MONTH": {"other":"-{0} m"},
      "YEAR": {"other":"-{0} y"}
    },
      futureUnits: {
      "SECOND": {"other":"+{0} s"},
      "MINUTE": {"other":"+{0} min"},
      "HOUR": {"other":"+{0} h"},
      "DAY": {"other":"+{0} d"},
      "WEEK": {"other":"+{0} w"},
      "MONTH": {"other":"+{0} m"},
      "YEAR": {"other":"+{0} y"}
    });

