// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "package:intl_data_gen/bin/intl_data_gen.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.EL;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"{0} δευτερόλεπτο","other":"{0} δευτερόλεπτα"},
      "MINUTE": {"one":"{0} λεπτό","other":"{0} λεπτά"},
      "HOUR": {"one":"{0} ώρα","other":"{0} ώρες"},
      "DAY": {"one":"{0} ημέρα","other":"{0} ημέρες"},
      "WEEK": {"one":"{0} εβδομάδα","other":"{0} εβδομάδες"},
      "MONTH": {"one":"{0} μήνας","other":"{0} μήνες"},
      "YEAR": {"one":"{0} έτος","other":"{0} έτη"}
    },
      shortUnits: {
      "SECOND": {"0":"0 δευτερόλεπτα","1":"1 δευτερόλεπτο","other":"{0} δευτερόλεπτα"},
      "MINUTE": {"0":"0 λεπτά","1":"1 λεπτό","other":"{0} λεπτά"},
      "HOUR": {"0":"0 ώρες","1":"1 ώρα","other":"{0} ώρες"},
      "DAY": {"0":"0 ημέρες","1":"1 ημέρα","other":"{0} ημέρες"},
      "WEEK": {"0":"0 εβδομάδες","1":"1 εβδομάδα","other":"{0} εβδομάδες"},
      "MONTH": {"0":"0 μήνες","1":"1 μήνας","other":"{0} μήνες"},
      "YEAR": {"0":"0 έτη","1":"1 έτος","other":"{0} έτη"}
    },
      pastUnits: {
      "SECOND": {"0":"Πριν από 0 δευτερόλεπτα","1":"Πριν από 1 δευτερόλεπτο","one":"Πριν από {0} δευτερόλεπτο","other":"Πριν από {0} δευτερόλεπτα"},
      "MINUTE": {"0":"Πριν από 0 λεπτά","1":"Πριν από 1 λεπτό","one":"Πριν από {0} λεπτό","other":"Πριν από {0} λεπτά"},
      "HOUR": {"0":"Πριν από 0 ώρες","1":"Πριν από 1 ώρα","one":"Πριν από {0} ώρα","other":"Πριν από {0} ώρες"},
      "DAY": {"0":"Πριν από 0 ημέρες","1":"Πριν από 1 ημέρα","one":"Πριν από {0} ημέρα","other":"Πριν από {0} ημέρες"},
      "WEEK": {"0":"Πριν από 0 εβδομάδες","1":"Πριν από 1 εβδομάδα","one":"Πριν από {0} εβδομάδα","other":"Πριν από {0} εβδομάδες"},
      "MONTH": {"0":"Πριν από 0 μήνες","1":"Πριν από 1 μήνα","one":"Πριν από {0} μήνα","other":"Πριν από {0} μήνες"},
      "YEAR": {"0":"Πριν από 0 έτη","1":"Πριν από 1 έτος","one":"Πριν από {0} έτος","other":"Πριν από {0} έτη"}
    },
      futureUnits: {
      "SECOND": {"0":"Σε 0 δευτερόλεπτα","1":"Σε 1 δευτερόλεπτο","one":"Σε {0} δευτερόλεπτο","other":"Σε {0} δευτερόλεπτα"},
      "MINUTE": {"0":"Σε 0 λεπτά","1":"Σε 1 λεπτό","one":"Σε {0} λεπτό","other":"Σε {0} λεπτά"},
      "HOUR": {"0":"Σε 0 ώρες","1":"Σε 1 ώρα","one":"Σε {0} ώρα","other":"Σε {0} ώρες"},
      "DAY": {"0":"Σε 0 ημέρες","1":"Σε 1 ημέρα","one":"Σε {0} ημέρα","other":"Σε {0} ημέρες"},
      "WEEK": {"0":"Σε 0 εβδομάδες","1":"Σε 1 εβδομάδα","one":"Σε {0} εβδομάδα","other":"Σε {0} εβδομάδες"},
      "MONTH": {"0":"Σε 0 μήνες","1":"Σε 1 μήνα","one":"Σε {0} μήνα","other":"Σε {0} μήνες"},
      "YEAR": {"0":"Σε 0 έτη","1":"Σε 1 έτος","one":"Σε {0} έτος","other":"Σε {0} έτη"}
    });

