// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "package:intl_data_gen/bin/intl_data_gen.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.FO;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"{0} sekund","other":"{0} sekundir"},
      "MINUTE": {"one":"{0} minuttur","other":"{0} minuttir"},
      "HOUR": {"one":"{0} tími","other":"{0} tímar"},
      "DAY": {"one":"{0} samdøgur","other":"{0} samdøgur"},
      "WEEK": {"one":"{0} vika","other":"{0} vikur"},
      "MONTH": {"one":"{0} mánadur","other":"{0} mánaðir"},
      "YEAR": {"one":"{0} ár","other":"{0} ár"}
    },
      shortUnits: {
      "SECOND": {},
      "MINUTE": {},
      "HOUR": {},
      "DAY": {},
      "WEEK": {},
      "MONTH": {},
      "YEAR": {}
    },
      pastUnits: {
      "SECOND": {"other":"-{0} s"},
      "MINUTE": {"other":"-{0} min"},
      "HOUR": {"other":"-{0} h"},
      "DAY": {"other":"-{0} d"},
      "WEEK": {"other":"-{0} w"},
      "MONTH": {"other":"-{0} m"},
      "YEAR": {"other":"-{0} y"}
    },
      futureUnits: {
      "SECOND": {"other":"+{0} s"},
      "MINUTE": {"other":"+{0} min"},
      "HOUR": {"other":"+{0} h"},
      "DAY": {"other":"+{0} d"},
      "WEEK": {"other":"+{0} w"},
      "MONTH": {"other":"+{0} m"},
      "YEAR": {"other":"+{0} y"}
    });

