// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "package:intl_data_gen/bin/intl_data_gen.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.FR;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"{0} seconde","other":"{0} secondes"},
      "MINUTE": {"one":"{0} minute","other":"{0} minutes"},
      "HOUR": {"one":"{0} heure","other":"{0} heures"},
      "DAY": {"one":"{0} jour","other":"{0} jours"},
      "WEEK": {"one":"{0} semaine","other":"{0} semaines"},
      "MONTH": {"one":"{0} mois","other":"{0} mois"},
      "YEAR": {"one":"{0} année","other":"{0} années"}
    },
      shortUnits: {
      "SECOND": {"one":"{0} s","other":"{0} s"},
      "MINUTE": {"one":"{0} mn","other":"{0} mn"},
      "HOUR": {"one":"{0} h","other":"{0} h"},
      "DAY": {"one":"{0} j","other":"{0} j"},
      "WEEK": {"one":"{0} sem.","other":"{0} sem."},
      "MONTH": {"one":"{0} mois","other":"{0} mois"},
      "YEAR": {"one":"{0} an","other":"{0} ans"}
    },
      pastUnits: {
      "SECOND": {"0":"Il y a 0 seconde","1":"Il y a 1 seconde","one":"il y a {0} seconde","other":"il y a {0} secondes"},
      "MINUTE": {"0":"Il y a 0 minute","1":"Il y a 1 minute","one":"il y a {0} minute","other":"il y a {0} minutes"},
      "HOUR": {"0":"Il y a 0 heure","1":"Il y a 1 heure","one":"il y a {0} heure","other":"il y a {0} heures"},
      "DAY": {"0":"Il y a 0 jour","1":"Il y a 1 jour","one":"il y a {0} jour","other":"il y a {0} jours"},
      "WEEK": {"0":"Il y a 0 semaine","1":"Il y a 1 semaine","one":"il y a {0} semaine","other":"il y a {0} semaines"},
      "MONTH": {"0":"Il y a 0 mois","1":"Il y a 1 mois","one":"il y a {0} mois","other":"il y a {0} mois"},
      "YEAR": {"0":"Il y a 0 an","1":"Il y a 1 an","one":"il y a {0} an","other":"il y a {0} ans"}
    },
      futureUnits: {
      "SECOND": {"0":"Dans 0 seconde","1":"Dans 1 seconde","one":"dans {0} seconde","other":"dans {0} secondes"},
      "MINUTE": {"0":"Dans 0 minute","1":"Dans 1 minute","one":"dans {0} minute","other":"dans {0} minutes"},
      "HOUR": {"0":"Dans 0 heure","1":"Dans 1 heure","one":"dans {0} heure","other":"dans {0} heures"},
      "DAY": {"0":"Dans 0 jour","1":"Dans 1 jour","one":"dans {0} jour","other":"dans {0} jours"},
      "WEEK": {"0":"Dans 0 semaine","1":"Dans 1 semaine","one":"dans {0} semaine","other":"dans {0} semaines"},
      "MONTH": {"0":"Dans 0 mois","1":"Dans 1 mois","one":"dans {0} mois","other":"dans {0} mois"},
      "YEAR": {"0":"Dans 0 an","1":"Dans 1 an","one":"dans {0} an","other":"dans {0} ans"}
    });

