// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/relative_time/code_build.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.FR_CA;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"{0} seconde","other":"{0} secondes"},
      "MINUTE": {"one":"{0} minute","other":"{0} minutes"},
      "HOUR": {"one":"{0} heure","other":"{0} heures"},
      "DAY": {"one":"{0} jour","other":"{0} jours"},
      "WEEK": {"one":"{0} semaine","other":"{0} semaines"},
      "MONTH": {"one":"{0} mois","other":"{0} mois"},
      "YEAR": {"one":"{0} année","other":"{0} années"}
    },
      shortUnits: {
      "SECOND": {"one":"{0} s","other":"{0} s"},
      "MINUTE": {"one":"{0} mn","other":"{0} mn"},
      "HOUR": {"one":"{0} h","other":"{0} h"},
      "DAY": {"one":"{0} j","other":"{0} j"},
      "WEEK": {"one":"{0} sem.","other":"{0} sem."},
      "MONTH": {"one":"{0} mois","other":"{0} mois"},
      "YEAR": {"one":"{0} an","other":"{0} ans"}
    },
      pastUnits: {
      "SECOND": {"1":"il y a 1 seconde","one":"Il y a {0} seconde","0":"il y a 0 seconde","other":"Il y a {0} secondes"},
      "MINUTE": {"1":"il y a 1 minute","one":"Il y a {0} minute","0":"il y a 0 minute","other":"Il y a {0} minutes"},
      "HOUR": {"1":"il y a 1 heure","one":"Il y a {0} heure","0":"il y a 0 heure","other":"Il y a {0} heures"},
      "DAY": {"1":"il y a 1 jour","one":"Il y a {0} jour","0":"il y a 0 jour","other":"Il y a {0} jours"},
      "WEEK": {"1":"il y a 1 semaine","one":"Il y a {0} semaine","0":"il y a 0 semaine","other":"Il y a {0} semaines"},
      "MONTH": {"1":"il y a 1 mois","one":"Il y a {0} mois","0":"il y a 0 mois","other":"Il y a {0} mois"},
      "YEAR": {"1":"il y a 1 an","one":"Il y a {0} an","0":"il y a 0 an","other":"Il y a {0} ans"}
    },
      futureUnits: {
      "SECOND": {"1":"Dans 1 seconde","one":"Dans {0} seconde","0":"Dans 0 seconde","other":"Dans {0} secondes"},
      "MINUTE": {"1":"dans 1 minute","one":"Dans {0} minute","0":"dans 0 minute","other":"Dans {0} minutes"},
      "HOUR": {"1":"dans 1 heure","one":"Dans {0} heure","0":"dans 0 heure","other":"Dans {0} heures"},
      "DAY": {"1":"dans 1 jour","one":"Dans {0} jour","0":"dans 0 jour","other":"Dans {0} jours"},
      "WEEK": {"1":"dans 1 semaine","one":"Dans {0} semaine","0":"dans 0 semaine","other":"Dans {0} semaines"},
      "MONTH": {"1":"dans 1 mois","one":"Dans {0} mois","0":"dans 0 mois","other":"Dans {0} mois"},
      "YEAR": {"1":"dans 1 an","one":"Dans {0} an","0":"dans 0 an","other":"Dans {0} ans"}
    });

