// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/relative_time/code_build.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library relative_time_symbols_hi;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"{0} सेकंड","other":"{0} सेकंड"},
      "MINUTE": {"one":"{0} मिनट","other":"{0} मिनट"},
      "HOUR": {"one":"{0} घंटा","other":"{0} घंटे"},
      "DAY": {"one":"{0} दिन","other":"{0} दिन"},
      "WEEK": {"one":"{0} सप्ताह","other":"{0} सप्ताह"},
      "MONTH": {"one":"{0} महीना","other":"{0} महीने"},
      "YEAR": {"one":"{0} साल","other":"{0} साल"}
    },
      shortUnits: {
      "SECOND": {"one":"{0} सेकं.","other":"{0} सेकं."},
      "MINUTE": {"one":"{0} मिन.","other":"{0} मिन."},
      "HOUR": {"one":"{0} घं.","other":"{0} घंटे"},
      "DAY": {"one":"{0} दि.","other":"{0} दि."},
      "WEEK": {"one":"{0} सप्त.","other":"{0} सप्त."},
      "MONTH": {"one":"{0} मही.","other":"{0} मही."},
      "YEAR": {"one":"{0} साल","other":"{0} साल"}
    },
      pastUnits: {
      "SECOND": {"1":"1 सेकंड पहले","0":"0 सेकंड पहले","other":"{0} सेकंड पहले"},
      "MINUTE": {"1":"1 मिनट पहले","0":"0 मिनट पहले","other":"{0} मिनट पहले"},
      "HOUR": {"1":"1 घंटे पहले","0":"0 घंटे पहले","other":"{0} घंटे पहले"},
      "DAY": {"1":"1 दिन पहले","0":"0 दिन पहले","other":"{0} दिन पहले"},
      "WEEK": {"1":"1 सप्ताह पहले","0":"0 सप्ताह पहले","other":"{0} सप्ताह पहले"},
      "MONTH": {"1":"1 माह पहले","0":"0 माह पहले","other":"{0} माह पहले"},
      "YEAR": {"1":"1 वर्ष पहले","0":"0 वर्ष पहले","other":"{0} वर्ष पहले"}
    },
      futureUnits: {
      "SECOND": {"1":"1 सेकंड में","0":"0 सेकंड में","other":"{0} सेकंड में"},
      "MINUTE": {"1":"1 मिनट में","0":"0 मिनट में","other":"{0} मिनट में"},
      "HOUR": {"1":"1 घंटे में","0":"0 घंटे में","other":"{0} घंटों में"},
      "DAY": {"1":"1 दिन में","0":"0 दिन में","other":"{0} दिनों में"},
      "WEEK": {"1":"1 सप्ताह में","0":"0 सेकंड में","other":"{0} सप्ताह में"},
      "MONTH": {"1":"1 माह में","0":"0 माह में","other":"{0} माह में"},
      "YEAR": {"1":"1 वर्ष में","0":"0 वर्ष में","other":"{0} वर्ष में"}
    });
