// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/relative_time/code_build.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.HU;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"other":"{0} másodperc"},
      "MINUTE": {"other":"{0} perc"},
      "HOUR": {"other":"{0} óra"},
      "DAY": {"other":"{0} nap"},
      "WEEK": {"other":"{0} hét"},
      "MONTH": {"other":"{0} hónap"},
      "YEAR": {"other":"{0} év"}
    },
      shortUnits: {
      "SECOND": {"other":"{0} mp"},
      "MINUTE": {"other":"{0} p"},
      "HOUR": {"other":"{0} ó"},
      "DAY": {"other":"{0} nap"},
      "WEEK": {"other":"{0} hét"},
      "MONTH": {"other":"{0} hónap"},
      "YEAR": {"other":"{0} év"}
    },
      pastUnits: {
      "SECOND": {"1":"1 másodperce","0":"0 másodperce","other":"{0} másodperccel ezelőtt"},
      "MINUTE": {"1":"1 perce","0":"0 perce","other":"{0} perccel ezelőtt"},
      "HOUR": {"1":"1 órája","0":"0 órája","other":"{0} órával ezelőtt"},
      "DAY": {"1":"1 napja","0":"0 napja","other":"{0} nappal ezelőtt"},
      "WEEK": {"1":"1 hete","0":"0 hete","other":"{0} héttel ezelőtt"},
      "MONTH": {"1":"1 hónapja","0":"0 hónapja","other":"{0} hónappal ezelőtt"},
      "YEAR": {"1":"1 éve","0":"0 éve","other":"{0} évvel ezelőtt"}
    },
      futureUnits: {
      "SECOND": {"1":"1 másodperc múlva","0":"0 másodperc múlva","other":"{0} másodperc múlva"},
      "MINUTE": {"1":"1 perc múlva","0":"0 perc múlva","other":"{0} perc múlva"},
      "HOUR": {"1":"1 óra múlva","0":"0 óra múlva","other":"{0} óra múlva"},
      "DAY": {"1":"1 nap múlva","0":"0 nap múlva","other":"{0} nap múlva"},
      "WEEK": {"1":"1 hét múlva","0":"0 hét múlva","other":"{0} hét múlva"},
      "MONTH": {"1":"1 hónap múlva","0":"0 hónap múlva","other":"{0} hónap múlva"},
      "YEAR": {"1":"1 év múlva","0":"0 év múlva","other":"{0} év múlva"}
    });

