// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "package:intl_data_gen/bin/intl_data_gen.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.LT;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"{0} sekundę","few":"{0} sekundės","other":"{0} sekundžių"},
      "MINUTE": {"one":"{0} minutė","few":"{0} minutės","other":"{0} minučių"},
      "HOUR": {"one":"{0} valandą","few":"{0} valandos","other":"{0} valandų"},
      "DAY": {"one":"{0} diena","few":"{0} dienos","other":"{0} dienų"},
      "WEEK": {"one":"{0} savaitė","few":"{0} savaitės","other":"{0} savaičių"},
      "MONTH": {"one":"{0} mėnesio","few":"{0} mėnesiai","other":"{0} mėnesių"},
      "YEAR": {"one":"{0} metai","few":"{0} metai","other":"{0} metų"}
    },
      shortUnits: {
      "SECOND": {"one":"{0} sek.","few":"{0} sek.","other":"{0} sek."},
      "MINUTE": {"one":"{0} min.","few":"{0} min.","other":"{0} min."},
      "HOUR": {"one":"{0} val.","few":"{0} val.","other":"{0} val."},
      "DAY": {"one":"{0} d.","few":"{0} d.","other":"{0} d."},
      "WEEK": {"one":"{0} sav.","few":"{0} sav.","other":"{0} sav."},
      "MONTH": {"one":"{0} mėn.","few":"{0} mėn.","other":"{0} mėn."},
      "YEAR": {"one":"{0} m.","few":"{0} m.","other":"{0} m."}
    },
      pastUnits: {
      "SECOND": {"0":"Prieš 0 sekundžių","1":"Prieš 1 sekundę","one":"prieš {0} sekundę","few":"prieš {0} sekundės","other":"prieš {0} sekundžių"},
      "MINUTE": {"0":"Prieš 0 minučių","1":"Prieš 1 minutę","one":"prieš {0} minutę","few":"prieš {0} minutės","other":"prieš {0} minučių"},
      "HOUR": {"0":"Prieš 0 valandų","1":"Prieš 1 valandą","one":"prieš {0} valandą","few":"prieš {0} valandos","other":"prieš {0} valandų"},
      "DAY": {"0":"Prieš 0 dienų","1":"Prieš 1 dieną","one":"prieš {0} dieną","few":"prieš {0} dienos","other":"prieš {0} dienų"},
      "WEEK": {"0":"Prieš 0 savaičių","1":"Prieš 1 savaitę","one":"prieš {0} savaitę","few":"prieš {0} savaitės","other":"prieš {0} savaičių"},
      "MONTH": {"0":"Prieš 0 mėnesių","1":"Prieš 1 mėnesį","one":"prieš {0} mėnesio","few":"prieš {0} mėnesį","other":"prieš {0} mėnesių"},
      "YEAR": {"0":"Prieš 0 metų","1":"Prieš 1 metus","one":"prieš {0} metus","few":"prieš {0} metai","other":"prieš {0} metų"}
    },
      futureUnits: {
      "SECOND": {"0":"Po 0 sekundžių","1":"Po 1 sekundės","one":"po {0} sekundę","few":"po {0} sekundės","other":"po {0} sekundžių"},
      "MINUTE": {"0":"Po 0 minučių","1":"Po 1 minutės","one":"po {0} minutę","few":"po {0} minutės","other":"po {0} minučių"},
      "HOUR": {"0":"Po 0 valandų","1":"Po 1 valandos","one":"po {0} valandą","few":"po {0} valandos","other":"po {0} valandų"},
      "DAY": {"0":"Po 0 dienų","1":"Po 1 dienos","one":"po {0} dieną","few":"po {0} dienos","other":"po {0} dienų"},
      "WEEK": {"0":"Po 0 savaičių","1":"Po 1 savaitės","one":"po {0} savaitę","few":"po {0} savaitės","other":"po {0} savaičių"},
      "MONTH": {"0":"Po 0 mėnesių","1":"Po 1 mėnesio","one":"po {0} mėnesio","few":"po {0} mėnesį","other":"po {0} mėnesių"},
      "YEAR": {"0":"Po 0 metų","1":"Po 1 metų","one":"po {0} metus","few":"po {0} metai","other":"po {0} metų"}
    });

