// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/relative_time/code_build.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.LT;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"{0} sekundę","other":"{0} sekundžių","few":"{0} sekundės"},
      "MINUTE": {"one":"{0} minutė","other":"{0} minučių","few":"{0} minutės"},
      "HOUR": {"one":"{0} valandą","other":"{0} valandų","few":"{0} valandos"},
      "DAY": {"one":"{0} diena","other":"{0} dienų","few":"{0} dienos"},
      "WEEK": {"one":"{0} savaitė","other":"{0} savaičių","few":"{0} savaitės"},
      "MONTH": {"one":"{0} mėnesio","other":"{0} mėnesių","few":"{0} mėnesiai"},
      "YEAR": {"one":"{0} metai","other":"{0} metų","few":"{0} metai"}
    },
      shortUnits: {
      "SECOND": {"one":"{0} sek.","other":"{0} sek.","few":"{0} sek."},
      "MINUTE": {"one":"{0} min.","other":"{0} min.","few":"{0} min."},
      "HOUR": {"one":"{0} val.","other":"{0} val.","few":"{0} val."},
      "DAY": {"one":"{0} d.","other":"{0} d.","few":"{0} d."},
      "WEEK": {"one":"{0} sav.","other":"{0} sav.","few":"{0} sav."},
      "MONTH": {"one":"{0} mėn.","other":"{0} mėn.","few":"{0} mėn."},
      "YEAR": {"one":"{0} m.","other":"{0} m.","few":"{0} m."}
    },
      pastUnits: {
      "SECOND": {"1":"prieš 1 sekundę","one":"prieš {0} sekundę","0":"prieš 0 sekundžių","few":"prieš {0} sekundės","other":"prieš {0} sekundžių"},
      "MINUTE": {"1":"prieš 1 minutę","one":"prieš {0} minutę","0":"prieš 0 minučių","few":"prieš {0} minutės","other":"prieš {0} minučių"},
      "HOUR": {"1":"prieš 1 valandą","one":"prieš {0} valandą","0":"prieš 0 valandų","few":"prieš {0} valandos","other":"prieš {0} valandų"},
      "DAY": {"1":"prieš 1 dieną","one":"prieš {0} dieną","0":"prieš 0 dienų","few":"prieš {0} dienos","other":"prieš {0} dienų"},
      "WEEK": {"1":"prieš 1 savaitę","one":"prieš {0} savaitę","0":"prieš 0 savaičių","few":"prieš {0} savaitės","other":"prieš {0} savaičių"},
      "MONTH": {"1":"prieš 1 mėnesį","one":"prieš {0} mėnesio","0":"prieš 0 mėnesių","few":"prieš {0} mėnesį","other":"prieš {0} mėnesių"},
      "YEAR": {"1":"prieš 1 metus","one":"prieš {0} metus","0":"prieš 0 metų","few":"prieš {0} metai","other":"prieš {0} metų"}
    },
      futureUnits: {
      "SECOND": {"1":"po 1 sekundės","one":"po {0} sekundę","0":"po 0 sekundžių","few":"po {0} sekundės","other":"po {0} sekundžių"},
      "MINUTE": {"1":"po 1 minutės","one":"po {0} minutę","0":"po 0 minučių","few":"po {0} minutės","other":"po {0} minučių"},
      "HOUR": {"1":"po 1 valandos","one":"po {0} valandą","0":"po 0 valandų","few":"po {0} valandos","other":"po {0} valandų"},
      "DAY": {"1":"po 1 dienos","one":"po {0} dieną","0":"po 0 dienų","few":"po {0} dienos","other":"po {0} dienų"},
      "WEEK": {"1":"po 1 savaitės","one":"po {0} savaitę","0":"po 0 savaičių","few":"po {0} savaitės","other":"po {0} savaičių"},
      "MONTH": {"1":"po 1 mėnesio","one":"po {0} mėnesio","0":"po 0 mėnesių","few":"po {0} mėnesį","other":"po {0} mėnesių"},
      "YEAR": {"1":"po 1 metų","one":"po {0} metus","0":"po 0 metų","few":"po {0} metai","other":"po {0} metų"}
    });

