// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "package:intl_data_gen/bin/intl_data_gen.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.ZU;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"0":"0 amasekhondi","1":"isekhondi elingu-1","other":"{0} amasekhondi"},
      "MINUTE": {"0":"amaminithi angu-0","1":"iminithi elingu-1","other":"{0} amaminithi"},
      "HOUR": {"0":"0 amahora","1":"ihora elingu-1","other":"{0} amahora"},
      "DAY": {"0":"Izinsuku ezingu-0","1":"usuku olungu-1","other":"{0} izinsuku"},
      "WEEK": {"0":"0 amaviki","1":"iviki elingu-1","other":"{0} amaviki"},
      "MONTH": {"0":"izinyanga ezingu-0","1":"inyana engu-1","other":"{0} izinyanga"},
      "YEAR": {"0":"0 iminyaka","1":"unyaka ongu-1","other":"{0} iminyaka"}
    },
      shortUnits: {
      "SECOND": {"0":"0 amasekhondi","1":"isekhondi elingu-1","other":"{0} amasekhondi"},
      "MINUTE": {"0":"0 amaminithi","1":"iminithi elingu-1","other":"{0} amaminithi"},
      "HOUR": {"0":"0 amahora","1":"ihora elingu-1","other":"{0} amahora"},
      "DAY": {"0":"Izinsuku ezingu-0","1":"usuku olungu-1","other":"{0} izinsuku"},
      "WEEK": {"0":"0 amaviki","1":"iviki elingu-1","other":"{0} amaviki"},
      "MONTH": {"0":"0 izinyanga","1":"inyanga engu-1","other":"{0} izinyanga"},
      "YEAR": {"0":"0 iminyaka","1":"unyaka ongu-1","other":"{0} iminyaka"}
    },
      pastUnits: {
      "SECOND": {"0":"amasekhondi angu-0 adlule","1":"isekhondi elingu-1 eledlule","other":"amasekhondi angu-{0} adlule"},
      "MINUTE": {"0":"amaminithi angu-0 adlule.","1":"eminithini elingu-1 eledlule","other":"amaminithi angu-{0} adlule"},
      "HOUR": {"0":"emahoreni angu-0 adlule","1":"ehoreni eligu-1 eledluli","other":"emahoreni angu-{0} edlule"},
      "DAY": {"0":"ezinsukwini ezingu-0 ezedlule.","1":"osukwini olungu-1 olwedlule","other":"ezinsukwini ezingu-{0} ezedlule."},
      "WEEK": {"0":"emavikini angu-0 adlule","1":"evikini elingu-1 eledlule","other":"amaviki angu-{0} adlule"},
      "MONTH": {"0":"izinyanga ezingu-0 ezedlule","1":"enyangeni engu-1 eyedlule","other":"ezinyangeni ezingu-{0} ezedlule"},
      "YEAR": {"0":"eminyakeni engu-0 edlule","1":"enyakeni ongu-1 owedlule","other":"iminyaka engu-{0} eyedlule"}
    },
      futureUnits: {
      "SECOND": {"0":"Emasekhondini angu-0","1":"Kusekhondi elingu-1","other":"Kumasekhondi angu-{0}"},
      "MINUTE": {"0":"Emaminithini angu-0","1":"Kumunithi engu-1","other":"Emaminithini angu-{0}"},
      "HOUR": {"0":"Emahoreni angu-0","1":"Ehoreni elingu-1","other":"Emahoreni angu-{0}"},
      "DAY": {"0":"Ezinsukwini ezingu-0","1":"Osukwini olungu-1","other":"Ezinsukwini ezingu-{0}"},
      "WEEK": {"0":"Emavikini angu-0","1":"Evikini elingu-1","other":"Emavikini angu-{0}"},
      "MONTH": {"0":"Ezinyangeni ezingu-0","1":"Enyangeni engu-1","other":"Ezinyangeni ezingu-{0}"},
      "YEAR": {"0":"Eminyakeni engu-0","1":"Onyakeni ongu-1","other":"Eminyakeni engu-{0}"}
    });

