/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library plural_locale_list;


const pluralLocales = const <String> ["gu", "rof", "gl", "lg", "lb", "xog", "brx", "ts", "tn", "tk", "ksb", "te", "haw", "kcg", "ssy", "de", "da", "dv", "el", "eo", "en", "teo", "ee", "eu", "et", "es", "seh", "kl", "fy", "rm", "bn", "bg", "ps", "asa", "cgg", "om", "vun", "or", "xh", "ca", "pt", "wae", "chr", "pa", "jmc", "ha", "he", "iw", "fur", "bem", "ml", "mn", "ur", "bez", "mr", "ta", "ve", "af", "is", "it", "zu", "saq", "pap", "nl", "nn", "nah", "nd", "ne", "ny", "nyn", "nr", "tig", "mas", "rwk", "kaj", "syr", "kk", "fi", "fo", "gsw", "ckb", "ss", "sq", "sw", "sv", "st", "so", "sn", "ku", "no", "nb", "lo", "tr", "to", "th", "yo", "ko", "dz", "ses", "kde", "ms", "wo", "bm", "jv", "bo", "kea", "ja", "fa", "zh", "hu", "my", "sah", "kn", "ii", "az", "id", "ig", "ka", "sg", "vi", "in", "ln", "fil", "guw", "wa", "bh", "nso", "tl", "ak", "am", "ti", "hi", "mg", "ru", "be", "bs", "hr", "uk", "sr", "sh", "cs", "sk", "fr", "ar", "pl", "lt", "lv", "mt", "ro", "sl"];
