name: intlx
version: 0.2.4
author: Sean Eagan <seaneagan1@gmail.com>
description: Intlx is internationalization APIs for Dart,  which have not yet made it into the intl package itself.  All data is sourced from CLDR.
homepage: http://www.github.com/seaneagan/intlx
dependencies:
  cldr: any
  intl: any
  observe: any
  parsers: any
  polymer: any
dev_dependencies:
  browser: any
  http: any
  logging: any
  unittest: any
