/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_symbols_ar;

import 'package:intlx/src/collection/collection_symbols.dart';

final symbols = new CollectionSymbols(    start: '{0}Ø {1}',
    middle: '{0}Ø {1}',
    end: '{0}Ø Ù {1}',
    indexed: const {"2":"{0} Ù {1}"});
