/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_symbols_sw;

import 'package:intlx/src/collection/collection_symbols.dart';

final symbols = new CollectionSymbols(    start: '{0}, {1}',
    middle: '{0}, {1}',
    end: '{0}, na {1}',
    indexed: const {"2":"{0} na {1}"});
