/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_symbols_tr;

import 'package:intlx/src/collection/symbols.dart';

final symbols = new CollectionSymbols(    start: '{0}, {1}',
    middle: '{0}, {1}',
    end: '{0} ve {1}',
    indexed: const {"2":"{0} ve {1}"});
