/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_symbols_ur;

import '../symbols.dart';

final symbols = new CollectionSymbols(    start: '{0}، {1}',
    middle: '{0}، {1}',
    end: '{0}، اور {1}',
    indexed: const {"2":"{0} اور {1}"});
