/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_symbols_zh;

import 'package:intlx/src/collection/symbols.dart';

final symbols = new CollectionSymbols(    start: '{0}ã{1}',
    middle: '{0}ã{1}',
    end: '{0}å{1}',
    indexed: const {"2":"{0}å{1}"});
