// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/relative_time/code_build.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.AR;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"ثانية","other":"{0} ثانية","few":"{0} ثوان","zero":"لا ثوان","two":"ثانيتان","many":"{0} ثانيةً"},
      "MINUTE": {"one":"دقيقة","other":"{0} دقيقة","few":"{0} دقائق","zero":"لا دقائق","two":"دقيقتان","many":"{0} دقيقةً"},
      "HOUR": {"one":"ساعة","other":"{0} ساعة","few":"{0} ساعات","zero":"لا ساعات","two":"ساعتان","many":"{0} ساعةً"},
      "DAY": {"one":"يوم","other":"{0} يوم","few":"{0} أيام","zero":"لا أيام","two":"يومان","many":"{0} يوماً"},
      "WEEK": {"one":"أسبوع","other":"{0} أسبوع","few":"{0} أسابيع","zero":"لا أسابيع","two":"أسبوعان","many":"{0} أسبوعاً"},
      "MONTH": {"one":"شهر","other":"{0} شهر","few":"{0} أشهر","zero":"لا أشهر","two":"شهران","many":"{0} شهراً"},
      "YEAR": {"one":"سنة","other":"{0} سنة","few":"{0} سنوات","zero":"لا سنوات","two":"سنتان","many":"{0} سنةً"}
    },
      shortUnits: {
      "SECOND": {"one":"ثانية","other":"{0} ث","few":"{0} ث","zero":"لا ثوان","two":"ثانيتان","many":"{0} ث"},
      "MINUTE": {"one":"دقيقة","other":"{0} د","few":"{0} د","zero":"لا دقائق","two":"دقيقتان","many":"{0} د"},
      "HOUR": {"one":"ساعة","other":"{0} س","few":"{0} س","zero":"لا ساعات","two":"ساعتان","many":"{0} س"},
      "DAY": {"one":"يوم","other":"{0} يوم","few":"{0} أيام","zero":"لا أيام","two":"يومان","many":"{0} يوماً"},
      "WEEK": {"one":"أسبوع","other":"{0} أسبوع","few":"{0} أسابيع","zero":"لا أسابيع","two":"أسبوعان","many":"{0} أسبوعاً"},
      "MONTH": {"one":"شهر","other":"{0} شهر","few":"{0} أشهر","zero":"لا أشهر","two":"شهران","many":"{0} شهراً"},
      "YEAR": {"one":"سنة","other":"{0} سنة","few":"{0} سنوات","zero":"لا سنوات","two":"سنتان","many":"{0} سنةً"}
    },
      pastUnits: {
      "SECOND": {"1":"قبل ثانية واحدة","0":"قبل 0 ثانية","few":"قبل {0} ثوانِ","other":"قبل {0} من الثواني","two":"قبل ثانيتين","many":"قبل {0} ثانية"},
      "MINUTE": {"1":"قبل دقيقة واحدة","0":"قبل 0 دقيقة","few":"قبل {0} دقائق","other":"قبل {0} من الدقائق","two":"قبل دقيقتين","many":"قبل {0} دقيقة"},
      "HOUR": {"1":"قبل ساعة واحدة","0":"قبل 0 ساعة","few":"قبل {0} ساعات","other":"قبل {0} من الساعات","two":"قبل ساعتين","many":"قبل {0} ساعة"},
      "DAY": {"1":"قبل يوم واحد","0":"قبل 0 يوم","few":"قبل {0} أيام","other":"قبل {0} من الأيام","two":"قبل يومين","many":"قبل {0} يومًا"},
      "WEEK": {"1":"قبل أسبوع واحد","0":"قبل 0 أسبوع","few":"قبل {0} أسابيع","other":"قبل {0} من الأسابيع","two":"قبل أسبوعين","many":"قبل {0} أسبوعًا"},
      "MONTH": {"1":"قبل شهر واحد","0":"قبل 0 شهر","few":"قبل {0} أشهر","other":"قبل {0} من الشهور","two":"قبل شهرين","many":"قبل {0} شهرًا"},
      "YEAR": {"1":"قبل سنة واحدة","0":"قبل 0 سنة","few":"قبل {0} سنوات","other":"قبل {0} من السنوات","two":"قبل سنتين","many":"قبل {0} سنة"}
    },
      futureUnits: {
      "SECOND": {"1":"خلال ثانية واحدة","0":"خلال 0 ثانية","few":"خلال {0} ثوانِ","other":"خلال {0} من الثواني","two":"خلال ثانيتين","many":"خلال {0} ثانية"},
      "MINUTE": {"1":"خلال دقيقة واحدة","0":"خلال 0 دقيقة","few":"خلال {0} دقائق","other":"خلال {0} من الدقائق","two":"خلال دقيقتين","many":"خلال {0} دقيقة"},
      "HOUR": {"1":"خلال ساعة واحدة","0":"خلال 0 ساعة","few":"خلال {0} ساعات","other":"خلال {0} من الساعات","two":"خلال ساعتين","many":"خلال {0} ساعة"},
      "DAY": {"1":"خلال يوم واحد","0":"خلال 0 يوم","few":"خلال {0} أيام","other":"خلال {0} من الأيام","two":"خلال يومين","many":"خلال {0} يومًا"},
      "WEEK": {"1":"خلال أسبوع واحد","0":"خلال 0 أسبوع","few":"خلال {0} أسابيع","other":"خلال {0} من الأسابيع","two":"خلال أسبوعين","many":"خلال {0} أسبوعًا"},
      "MONTH": {"1":"خلال شهر واحد","0":"خلال 0 شهر","few":"خلال {0} شهور","other":"خلال {0} من الشهور","two":"خلال شهرين","many":"خلال {0} شهرًا"},
      "YEAR": {"1":"خلال سنة واحدة","0":"خلال 0 سنة","few":"خلال {0} سنوات","other":"خلال {0} من السنوات","two":"خلال سنتين","many":"خلال {0} سنة"}
    });
