// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/relative_time/code_build.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library relative_time_symbols_bn;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"{0} সেকেন্ড","other":"{0} সেকেন্ড"},
      "MINUTE": {"one":"{0} মিনিট","other":"{0} মিনিট"},
      "HOUR": {"one":"{0} ঘন্টা","other":"{0} ঘন্টা"},
      "DAY": {"one":"{0} দিন","other":"{0} দিন"},
      "WEEK": {"one":"{0} সপ্তাহ","other":"{0} সপ্তাহ"},
      "MONTH": {"one":"{0} মাস","other":"{0} মাস"},
      "YEAR": {"one":"{0} বছর","other":"{0} বছর"}
    },
      shortUnits: {
      "SECOND": {"1":"১ সেকেন্ড","0":"০ সেকেন্ড","other":"{0} সেকেন্ড"},
      "MINUTE": {"1":"1 মিনিট","0":"0 মিনিট","other":"{0} মিনিট"},
      "HOUR": {"1":"1 ঘন্টা","0":"0 ঘন্টা","other":"{0} ঘন্টা"},
      "DAY": {"1":"1 দিন","0":"0 দিন","other":"{0} দিন"},
      "WEEK": {"1":"১ সপ্তাহ","0":"0 সপ্তাহ","other":"{0} সপ্তাহ"},
      "MONTH": {"1":"১ মাস","0":"০ মাস","other":"{0} মাস"},
      "YEAR": {"1":"১ বছর","0":"০ বছর","other":"{0} বছর"}
    },
      pastUnits: {
      "SECOND": {"1":"১ সেকেন্ড পূর্বে","0":"0 সেকেন্ড পূর্বে","other":"{0}সেকেন্ড পূর্বে"},
      "MINUTE": {"1":"1 মিনিট পূর্বে","0":"0 মিনিট পূর্বে","other":"{0} মিনিট পূর্বে"},
      "HOUR": {"1":"১ ঘন্টা আগে","0":"০ ঘন্টা আগে","other":"{0}ঘন্টা আগে"},
      "DAY": {"1":"১ দিন পূর্বে","0":"0 দিন পূর্বে","other":"{0} দিন পূর্বে"},
      "WEEK": {"1":"১ সপ্তাহ পূর্বে","0":"0 সপ্তাহ পূর্বে","other":"{0} সপ্তাহ পূর্বে"},
      "MONTH": {"1":"১ মাস পূর্বে","0":"0 মাস পূর্বে","other":"{0} মাস পূর্বে"},
      "YEAR": {"1":"১ বছর পূর্বে","0":"0 বছর পূর্বে","other":"{0} বছর পূর্বে"}
    },
      futureUnits: {
      "SECOND": {"1":"১ সেকেন্ডে","0":"০ সেকেন্ডে","other":"{0} সেকেন্ডে"},
      "MINUTE": {"1":"১ মিনিটে","0":"০মিনিটে","other":"{0} মিনিটে"},
      "HOUR": {"1":"১ ঘন্টায়","0":"০ ঘন্টায়","other":"{0} ঘন্টায়"},
      "DAY": {"1":"১ দিনের মধ্যে","0":"0 দিনের মধ্যে","other":"{0} দিনের মধ্যে"},
      "WEEK": {"1":"১ সপ্তাহে","0":"০ সপ্তাহে","other":"{0} সপ্তাহে"},
      "MONTH": {"1":"১ মাসে","0":"০ মাসে","other":"{0} মাসে"},
      "YEAR": {"1":"১ বছরে","0":"0 বছরে","other":"{0} বছরে"}
    });
