// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/relative_time/code_build.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.DE;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"{0} Sekunde","other":"{0} Sekunden"},
      "MINUTE": {"one":"{0} Minute","other":"{0} Minuten"},
      "HOUR": {"one":"{0} Stunde","other":"{0} Stunden"},
      "DAY": {"one":"{0} Tag","other":"{0} Tage"},
      "WEEK": {"one":"{0} Woche","other":"{0} Wochen"},
      "MONTH": {"one":"{0} Monat","other":"{0} Monate"},
      "YEAR": {"one":"{0} Jahr","other":"{0} Jahre"}
    },
      shortUnits: {
      "SECOND": {"one":"{0} Sek.","other":"{0} Sek."},
      "MINUTE": {"one":"{0} Min.","other":"{0} Min."},
      "HOUR": {"one":"{0} Std.","other":"{0} Std."},
      "DAY": {"one":"{0} Tag","other":"{0} Tage"},
      "WEEK": {"one":"{0} Woche","other":"{0} Wochen"},
      "MONTH": {"one":"{0} Monat","other":"{0} Monate"},
      "YEAR": {"one":"{0} Jahr","other":"{0} Jahre"}
    },
      pastUnits: {
      "SECOND": {"1":"Vor 1 Sekunde","one":"Vor {0} Sekunde","0":"Vor 0 Sekunden","other":"Vor {0} Sekunden"},
      "MINUTE": {"1":"Vor 1 Minute","one":"Vor {0} Minute","0":"Vor 0 Minuten","other":"Vor {0} Minuten"},
      "HOUR": {"1":"Vor 1 Stunde","one":"Vor {0} Stunde","0":"Vor 0 Stunden","other":"Vor {0} Stunden"},
      "DAY": {"1":"Vor 1 Tag","one":"Vor {0} Tag","0":"Vor 0 Tagen","other":"Vor {0} Tagen"},
      "WEEK": {"1":"Vor 1 Woche","one":"Vor {0} Woche","0":"Vor 0 Wochen","other":"Vor {0} Wochen"},
      "MONTH": {"1":"Vor 1 Monat","one":"Vor {0} Monat","0":"Vor 0 Monaten","other":"Vor {0} Monaten"},
      "YEAR": {"1":"Vor 1 Jahr","one":"Vor {0} Jahr","0":"Vor 0 Jahren","other":"Vor {0} Jahren"}
    },
      futureUnits: {
      "SECOND": {"1":"In 1 Sekunde","one":"In {0} Sekunde","0":"In 0 Sekunden","other":"In {0} Sekunden"},
      "MINUTE": {"1":"In 1 Minute","one":"In {0} Minute","0":"In 0 Minuten","other":"In {0} Minuten"},
      "HOUR": {"1":"In 1 Stunde","one":"In {0} Stunde","0":"In 0 Stunden","other":"In {0} Stunden"},
      "DAY": {"1":"In 1 Tag","one":"In {0} Tag","0":"In 0 Tagen","other":"In {0} Tagen"},
      "WEEK": {"1":"In 1 Woche","one":"In {0} Woche","0":"In 0 Wochen","other":"In {0} Wochen"},
      "MONTH": {"1":"In 1 Monat","one":"In {0} Monat","0":"In 0 Monaten","other":"In {0} Monaten"},
      "YEAR": {"1":"In 1 Jahr","one":"In {0} Jahr","0":"In 0 Jahren","other":"In {0} Jahren"}
    });
