// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/relative_time/code_build.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library relative_time_symbols_fa;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"other":"{0} Ø«Ø§ÙÛÙ"},
      "MINUTE": {"other":"{0} Ø¯ÙÛÙÙ"},
      "HOUR": {"other":"{0} Ø³Ø§Ø¹Øª"},
      "DAY": {"other":"{0} Ø±ÙØ²"},
      "WEEK": {"other":"{0} ÙÙØªÙ"},
      "MONTH": {"other":"{0} ÙØ§Ù"},
      "YEAR": {"other":"{0} Ø³Ø§Ù"}
    },
      shortUnits: {
      "SECOND": {"1":"1 Ø«Ø§ÙÛÙ","0":"0 Ø«Ø§ÙÛÙ","other":"{0} Ø«Ø§ÙÛÙ"},
      "MINUTE": {"1":"1 Ø¯ÙÛÙÙ","0":"0 Ø¯ÙÛÙÙ","other":"{0} Ø¯ÙÛÙÙ"},
      "HOUR": {"1":"1 Ø³Ø§Ø¹Øª","0":"0 Ø³Ø§Ø¹Øª","other":"{0} Ø³Ø§Ø¹Øª"},
      "DAY": {"1":"1 Ø±ÙØ²","0":"0 Ø±ÙØ²","other":"{0} Ø±ÙØ²"},
      "WEEK": {"1":"1 ÙÙØªÙ","0":"0 ÙÙØªÙ","other":"{0} ÙÙØªÙ"},
      "MONTH": {"1":"1 ÙØ§Ù","0":"0 ÙØ§Ù","other":"{0} ÙØ§Ù"},
      "YEAR": {"1":"1 Ø³Ø§Ù","0":"0 Ø³Ø§Ù","other":"{0} Ø³Ø§Ù"}
    },
      pastUnits: {
      "SECOND": {"1":"1 Ø«Ø§ÙÛÙ ÙØ¨Ù","0":"0 Ø«Ø§ÙÛÙ ÙØ¨Ù","other":"{0} Ø«Ø§ÙÛÙ Ù¾ÛØ´"},
      "MINUTE": {"1":"1 Ø¯ÙÛÙÙ ÙØ¨Ù","0":"0 Ø¯ÙÛÙÙ ÙØ¨Ù","other":"{0} Ø¯ÙÛÙÙ Ù¾ÛØ´"},
      "HOUR": {"1":"1 Ø³Ø§Ø¹Øª ÙØ¨Ù","0":"0 Ø³Ø§Ø¹Øª ÙØ¨Ù","other":"{0} Ø³Ø§Ø¹Øª Ù¾ÛØ´"},
      "DAY": {"1":"1 Ø±ÙØ² ÙØ¨Ù","0":"0 Ø±ÙØ² ÙØ¨Ù","other":"{0} Ø±ÙØ² Ù¾ÛØ´"},
      "WEEK": {"1":"1 ÙÙØªÙ ÙØ¨Ù","0":"0 ÙÙØªÙ ÙØ¨Ù","other":"{0} ÙÙØªÙ Ù¾ÛØ´"},
      "MONTH": {"1":"1 ÙØ§Ù ÙØ¨Ù","0":"0 ÙØ§Ù ÙØ¨Ù","other":"{0} ÙØ§Ù Ù¾ÛØ´"},
      "YEAR": {"1":"1 Ø³Ø§Ù ÙØ¨Ù","0":"0 Ø³Ø§Ù ÙØ¨Ù","other":"{0} Ø³Ø§Ù Ù¾ÛØ´"}
    },
      futureUnits: {
      "SECOND": {"1":"Ø¯Ø± 1 Ø«Ø§ÙÛÙ","0":"Ø¯Ø± 0 Ø«Ø§ÙÛÙ","other":"{0} Ø«Ø§ÙÛÙ Ø¨Ø¹Ø¯"},
      "MINUTE": {"1":"Ø¯Ø± 1 Ø¯ÙÛÙÙ","0":"Ø¯Ø± 0 Ø¯ÙÛÙÙ","other":"{0} Ø¯ÙÛÙÙ Ø¨Ø¹Ø¯"},
      "HOUR": {"1":"Ø¯Ø± 1 Ø³Ø§Ø¹Øª","0":"Ø¯Ø± 0 Ø³Ø§Ø¹Øª","other":"{0} Ø³Ø§Ø¹Øª Ø¨Ø¹Ø¯"},
      "DAY": {"1":"Ø¯Ø± 1 Ø±ÙØ²","0":"Ø¯Ø± 0 Ø±ÙØ²","other":"{0} Ø±ÙØ² Ø¨Ø¹Ø¯"},
      "WEEK": {"1":"Ø¯Ø± 1 ÙÙØªÙ","0":"Ø¯Ø± 0 ÙÙØªÙ","other":"{0} ÙÙØªÙ Ø¨Ø¹Ø¯"},
      "MONTH": {"1":"Ø¯Ø± 1 ÙØ§Ù","0":"Ø¯Ø± 0 ÙØ§Ù","other":"{0} ÙØ§Ù Ø¨Ø¹Ø¯"},
      "YEAR": {"1":"Ø¯Ø± 1 Ø³Ø§Ù","0":"Ø¯Ø± 0 Ø³Ø§Ù","other":"{0} Ø³Ø§Ù Ø¨Ø¹Ø¯"}
    });
