// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/relative_time/code_build.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.FA;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"other":"{0} ثانیه"},
      "MINUTE": {"other":"{0} دقیقه"},
      "HOUR": {"other":"{0} ساعت"},
      "DAY": {"other":"{0} روز"},
      "WEEK": {"other":"{0} هفته"},
      "MONTH": {"other":"{0} ماه"},
      "YEAR": {"other":"{0} سال"}
    },
      shortUnits: {
      "SECOND": {"1":"1 ثانیه","0":"0 ثانیه","other":"{0} ثانیه"},
      "MINUTE": {"1":"1 دقیقه","0":"0 دقیقه","other":"{0} دقیقه"},
      "HOUR": {"1":"1 ساعت","0":"0 ساعت","other":"{0} ساعت"},
      "DAY": {"1":"1 روز","0":"0 روز","other":"{0} روز"},
      "WEEK": {"1":"1 هفته","0":"0 هفته","other":"{0} هفته"},
      "MONTH": {"1":"1 ماه","0":"0 ماه","other":"{0} ماه"},
      "YEAR": {"1":"1 سال","0":"0 سال","other":"{0} سال"}
    },
      pastUnits: {
      "SECOND": {"1":"1 ثانیه قبل","0":"0 ثانیه قبل","other":"{0} ثانیه پیش"},
      "MINUTE": {"1":"1 دقیقه قبل","0":"0 دقیقه قبل","other":"{0} دقیقه پیش"},
      "HOUR": {"1":"1 ساعت قبل","0":"0 ساعت قبل","other":"{0} ساعت پیش"},
      "DAY": {"1":"1 روز قبل","0":"0 روز قبل","other":"{0} روز پیش"},
      "WEEK": {"1":"1 هفته قبل","0":"0 هفته قبل","other":"{0} هفته پیش"},
      "MONTH": {"1":"1 ماه قبل","0":"0 ماه قبل","other":"{0} ماه پیش"},
      "YEAR": {"1":"1 سال قبل","0":"0 سال قبل","other":"{0} سال پیش"}
    },
      futureUnits: {
      "SECOND": {"1":"در 1 ثانیه","0":"در 0 ثانیه","other":"{0} ثانیه بعد"},
      "MINUTE": {"1":"در 1 دقیقه","0":"در 0 دقیقه","other":"{0} دقیقه بعد"},
      "HOUR": {"1":"در 1 ساعت","0":"در 0 ساعت","other":"{0} ساعت بعد"},
      "DAY": {"1":"در 1 روز","0":"در 0 روز","other":"{0} روز بعد"},
      "WEEK": {"1":"در 1 هفته","0":"در 0 هفته","other":"{0} هفته بعد"},
      "MONTH": {"1":"در 1 ماه","0":"در 0 ماه","other":"{0} ماه بعد"},
      "YEAR": {"1":"در 1 سال","0":"در 0 سال","other":"{0} سال بعد"}
    });
