// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/relative_time/code_build.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library relative_time_symbols_he;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"{0} ×©× ××","other":"{0} ×©× ×××ª"},
      "MINUTE": {"one":"{0} ××§×","other":"{0} ××§××ª"},
      "HOUR": {"one":"{0} ×©×¢×","other":"{0} ×©×¢××ª"},
      "DAY": {"one":"{0} ×××","other":"{0} ××××"},
      "WEEK": {"one":"{0} ×©×××¢","other":"{0} ×©×××¢××ª"},
      "MONTH": {"one":"{0} ××××©","other":"{0} ××××©××"},
      "YEAR": {"one":"{0} ×©× ×","other":"{0} ×©× ××"}
    },
      shortUnits: {
      "SECOND": {"one":"{0} ×©× ×³","other":"{0} ×©× ×³"},
      "MINUTE": {"one":"{0} ××§×³","other":"{0} ××§×³"},
      "HOUR": {"one":"{0} ×©×¢×","other":"{0} ×©×¢××ª"},
      "DAY": {"one":"{0} ×××","other":"{0} ××××"},
      "WEEK": {"one":"{0} ×©×××¢","other":"{0} ×©×××¢××ª"},
      "MONTH": {"one":"{0} ××××©","other":"{0} ××××©××"},
      "YEAR": {"one":"{0} ×©× ×","other":"{0} ×©× ××"}
    },
      pastUnits: {
      "SECOND": {"1":"××¤× × ×©× ×××","0":"××¤× × 0 ×©× ×××ª","other":"××¤× × {0} ×©× ×××ª"},
      "MINUTE": {"1":"××¤× × ××§×","0":"××¤× × 0 ××§××ª","other":"××¤× × {0} ××§××ª"},
      "HOUR": {"1":"××¤× × ×©×¢×","0":"××¤× × 0 ×©×¢××ª","other":"××¤× × {0} ×©×¢××ª"},
      "DAY": {"1":"××¤× × ×××","0":"××¤× × 0 ××××","other":"××¤× × {0} ××××"},
      "WEEK": {"1":"××¤× × ×©×××¢","0":"××¤× × 0 ×©×××¢××ª","other":"××¤× × {0} ×©×××¢××ª"},
      "MONTH": {"1":"××¤× × ××××©","0":"××¤× × 0 ××××©××","other":"××¤× × {0} ××××©××"},
      "YEAR": {"1":"××¤× × ×©× ×","0":"××¤× × 0 ×©× ××","other":"××¤× × {0} ×©× ××"}
    },
      futureUnits: {
      "SECOND": {"1":"×¢×× ×©× ×××","0":"×¢×× 0 ×©× ×××ª","other":"××¢×× {0} ×©× ×××ª"},
      "MINUTE": {"1":"×¢×× ××§×","0":"×¢×× 0 ××§××ª","other":"××¢×× {0} ××§××ª"},
      "HOUR": {"1":"×¢×× ×©×¢×","0":"×¢×× 0 ×©×¢××ª","other":"××¢×× {0} ×©×¢××ª"},
      "DAY": {"1":"×¢×× ×××","0":"×¢×× 0 ××××","other":"××¢×× {0} ××××"},
      "WEEK": {"1":"×¢×× ×©×××¢","0":"×¢×× 0 ×©×××¢××ª","other":"××¢×× {0} ×©×××¢××ª"},
      "MONTH": {"1":"×¢×× ××××©","0":"×¢×× 0 ××××©××","other":"××¢×× {0} ××××©××"},
      "YEAR": {"1":"×¢×× ×©× ×","0":"×¢×× 0 ×©× ××","other":"××¢×× {0} ×©× ××"}
    });
