// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/relative_time/code_build.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library relative_time_symbols_he;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"{0} שניה","other":"{0} שניות"},
      "MINUTE": {"one":"{0} דקה","other":"{0} דקות"},
      "HOUR": {"one":"{0} שעה","other":"{0} שעות"},
      "DAY": {"one":"{0} יום","other":"{0} ימים"},
      "WEEK": {"one":"{0} שבוע","other":"{0} שבועות"},
      "MONTH": {"one":"{0} חודש","other":"{0} חודשים"},
      "YEAR": {"one":"{0} שנה","other":"{0} שנים"}
    },
      shortUnits: {
      "SECOND": {"one":"{0} שנ׳","other":"{0} שנ׳"},
      "MINUTE": {"one":"{0} דק׳","other":"{0} דק׳"},
      "HOUR": {"one":"{0} שעה","other":"{0} שעות"},
      "DAY": {"one":"{0} יום","other":"{0} ימים"},
      "WEEK": {"one":"{0} שבוע","other":"{0} שבועות"},
      "MONTH": {"one":"{0} חודש","other":"{0} חודשים"},
      "YEAR": {"one":"{0} שנה","other":"{0} שנים"}
    },
      pastUnits: {
      "SECOND": {"1":"לפני שנייה","0":"לפני 0 שניות","other":"לפני {0} שניות"},
      "MINUTE": {"1":"לפני דקה","0":"לפני 0 דקות","other":"לפני {0} דקות"},
      "HOUR": {"1":"לפני שעה","0":"לפני 0 שעות","other":"לפני {0} שעות"},
      "DAY": {"1":"לפני יום","0":"לפני 0 ימים","other":"לפני {0} ימים"},
      "WEEK": {"1":"לפני שבוע","0":"לפני 0 שבועות","other":"לפני {0} שבועות"},
      "MONTH": {"1":"לפני חודש","0":"לפני 0 חודשים","other":"לפני {0} חודשים"},
      "YEAR": {"1":"לפני שנה","0":"לפני 0 שנים","other":"לפני {0} שנים"}
    },
      futureUnits: {
      "SECOND": {"1":"עוד שנייה","0":"עוד 0 שניות","other":"בעוד {0} שניות"},
      "MINUTE": {"1":"עוד דקה","0":"עוד 0 דקות","other":"בעוד {0} דקות"},
      "HOUR": {"1":"עוד שעה","0":"עוד 0 שעות","other":"בעוד {0} שעות"},
      "DAY": {"1":"עוד יום","0":"עוד 0 ימים","other":"בעוד {0} ימים"},
      "WEEK": {"1":"עוד שבוע","0":"עוד 0 שבועות","other":"בעוד {0} שבועות"},
      "MONTH": {"1":"עוד חודש","0":"עוד 0 חודשים","other":"בעוד {0} חודשים"},
      "YEAR": {"1":"עוד שנה","0":"עוד 0 שנים","other":"בעוד {0} שנים"}
    });
