// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/relative_time/code_build.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library relative_time_symbols_hr;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"{0} sekunda","other":"{0} sekunda","few":"{0} sekunde","many":"{0} sekundi"},
      "MINUTE": {"one":"{0} minuta","other":"{0} minuta","few":"{0} minute","many":"{0} minuta"},
      "HOUR": {"one":"{0} sat","other":"{0} sat","few":"{0} sata","many":"{0} sati"},
      "DAY": {"one":"{0} dan","other":"{0} dan","few":"{0} dana","many":"{0} dana"},
      "WEEK": {"one":"{0} tjedan","other":"{0} tjedan","few":"{0} tjedna","many":"{0} tjedana"},
      "MONTH": {"one":"{0} mjesec","other":"{0} mjesec","few":"{0} mjeseca","many":"{0} mjeseci"},
      "YEAR": {"one":"{0} godina","other":"{0} godina","few":"{0} godine","many":"{0} godina"}
    },
      shortUnits: {
      "SECOND": {"one":"{0} s","other":"{0} s","few":"{0} s","many":"{0} s"},
      "MINUTE": {"one":"{0} min","other":"{0} min","few":"{0} min","many":"{0} min"},
      "HOUR": {"one":"{0} h","other":"{0} h","few":"{0} h","many":"{0} h"},
      "DAY": {"one":"{0} dan","other":"{0} dan","few":"{0} dana","many":"{0} dana"},
      "WEEK": {"one":"{0} tj.","other":"{0} tj.","few":"{0} tj.","many":"{0} tj."},
      "MONTH": {"one":"{0} mj.","other":"{0} mj.","few":"{0} mj.","many":"{0} mj."},
      "YEAR": {"one":"{0} g.","other":"{0} g.","few":"{0} g.","many":"{0} g."}
    },
      pastUnits: {
      "SECOND": {"1":"prije 1 sekundu","one":"prije {0} sekundu","0":"prije 0 sekundi","few":"prije {0} sekunde","other":"prije {0} sekundi","many":"prije {0} sekundi"},
      "MINUTE": {"1":"prije 1 minutu","one":"prije {0} minutu","0":"prije 0 minuta","few":"prije {0} minute","other":"Prije {0} minuta","many":"prije {0} minuta"},
      "HOUR": {"1":"prije 1 h","one":"prije {0} sat","0":"prije 0 sati","few":"prije {0} sata","other":"Prije {0} sati","many":"prije {0} sati"},
      "DAY": {"1":"prije 1 dana","one":"prije {0} dan","0":"prije 0 dana","few":"prije {0} dana","other":"Prije ovoliko dana: {0}","many":"prije {0} dana"},
      "WEEK": {"1":"prije 1 tjedna","one":"prije {0} tjedan","0":"prije 0 tjedana","few":"prije {0} tjedna","other":"prije ovoliko tjedana: {0}","many":"prije {0} tjedana"},
      "MONTH": {"1":"prije 1 mjeseca","one":"prije {0} mjesec","0":"prije 0 mjeseci","few":"prije {0} mjeseca","other":"prije ovoliko mjeseci: {0}","many":"prije {0} mjeseci"},
      "YEAR": {"1":"prije 1 godine","one":"prije {0} godinu","0":"prije 0 godina","few":"prije {0} godine","other":"prije ovoliko godina: {0}","many":"prije {0} godina"}
    },
      futureUnits: {
      "SECOND": {"1":"za 1 sekundu","one":"za {0} sekundu","0":"za 0 sekundi","few":"za {0} sekunde","other":"za {0} sekundi","many":"za {0} sekundi"},
      "MINUTE": {"1":"za 1 min","one":"za {0} minutu","0":"za 0 minuta","few":"za {0} minute","other":"Za {0} minuta","many":"za {0} minuta"},
      "HOUR": {"1":"za 1 sat","one":"za {0} sat","0":"za 0 sati","few":"za {0} sata","other":"Za {0} sati","many":"za {0} sati"},
      "DAY": {"1":"za 1 dan","one":"za {0} dan","0":"za 0 dana","few":"za {0} dana","other":"za {0} dana","many":"za {0} dana"},
      "WEEK": {"1":"za 1 tjedan","one":"za {0} tjedan","0":"za 0 tjedana","few":"za {0} tjedna","other":"za sljedeÄi broj tjedana: {0}","many":"za {0} tjedana"},
      "MONTH": {"1":"za 1 mjesec","one":"za {0} mjesec","0":"za 0 mjeseci","few":"za {0} mjeseca","other":"za sljedeÄi broj mjeseci: {0}","many":"za {0} mjeseci"},
      "YEAR": {"1":"za 1 godinu","one":"za {0} godinu","0":"za 0 g.","few":"za {0} godine","other":"za {0} godina","many":"za {0} godina"}
    });
