// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"
/// 
/// Before checkin, this file could have been manually edited. This is
/// to incorporate changes before we could correct CLDR. All manual
/// modification must be documented in this section, and should be
/// removed after those changes land to CLDR.
part of relative_time_symbols_data;

final symbols_HU = new RelativeTimeSymbols(      units: {
      "SECOND": {"other":"{0} mÃ¡sodperc"},
      "MINUTE": {"other":"{0} perc"},
      "HOUR": {"other":"{0} Ã³ra"},
      "DAY": {"other":"{0} nap"},
      "WEEK": {"other":"{0} hÃ©t"},
      "MONTH": {"other":"{0} hÃ³nap"},
      "YEAR": {"other":"{0} Ã©v"}
    },
      shortUnits: {
      "SECOND": {"other":"{0} mp"},
      "MINUTE": {"other":"{0} p"},
      "HOUR": {"other":"{0} Ã³"},
      "DAY": {"other":"{0} nap"},
      "WEEK": {"other":"{0} hÃ©t"},
      "MONTH": {"other":"{0} hÃ³nap"},
      "YEAR": {"other":"{0} Ã©v"}
    },
      pastUnits: {
      "SECOND": {"1":"1 mÃ¡sodperce","0":"0 mÃ¡sodperce","other":"{0} mÃ¡sodperccel ezelÅtt"},
      "MINUTE": {"1":"1 perce","0":"0 perce","other":"{0} perccel ezelÅtt"},
      "HOUR": {"1":"1 Ã³rÃ¡ja","0":"0 Ã³rÃ¡ja","other":"{0} Ã³rÃ¡val ezelÅtt"},
      "DAY": {"1":"1 napja","0":"0 napja","other":"{0} nappal ezelÅtt"},
      "WEEK": {"1":"1 hete","0":"0 hete","other":"{0} hÃ©ttel ezelÅtt"},
      "MONTH": {"1":"1 hÃ³napja","0":"0 hÃ³napja","other":"{0} hÃ³nappal ezelÅtt"},
      "YEAR": {"1":"1 Ã©ve","0":"0 Ã©ve","other":"{0} Ã©vvel ezelÅtt"}
    },
      futureUnits: {
      "SECOND": {"1":"1 mÃ¡sodperc mÃºlva","0":"0 mÃ¡sodperc mÃºlva","other":"{0} mÃ¡sodperc mÃºlva"},
      "MINUTE": {"1":"1 perc mÃºlva","0":"0 perc mÃºlva","other":"{0} perc mÃºlva"},
      "HOUR": {"1":"1 Ã³ra mÃºlva","0":"0 Ã³ra mÃºlva","other":"{0} Ã³ra mÃºlva"},
      "DAY": {"1":"1 nap mÃºlva","0":"0 nap mÃºlva","other":"{0} nap mÃºlva"},
      "WEEK": {"1":"1 hÃ©t mÃºlva","0":"0 hÃ©t mÃºlva","other":"{0} hÃ©t mÃºlva"},
      "MONTH": {"1":"1 hÃ³nap mÃºlva","0":"0 hÃ³nap mÃºlva","other":"{0} hÃ³nap mÃºlva"},
      "YEAR": {"1":"1 Ã©v mÃºlva","0":"0 Ã©v mÃºlva","other":"{0} Ã©v mÃºlva"}
    });
