// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/relative_time/code_build.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.ID;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"other":"{0} detik"},
      "MINUTE": {"other":"{0} menit"},
      "HOUR": {"other":"{0} jam"},
      "DAY": {"other":"{0} hari"},
      "WEEK": {"other":"{0} minggu"},
      "MONTH": {"other":"{0} bulan"},
      "YEAR": {"other":"{0} tahun"}
    },
      shortUnits: {
      "SECOND": {"other":"{0} dtk"},
      "MINUTE": {"other":"{0} mnt"},
      "HOUR": {"other":"{0} jam"},
      "DAY": {"other":"{0} hr"},
      "WEEK": {"other":"{0} mggu"},
      "MONTH": {"other":"{0} bln"},
      "YEAR": {"other":"{0} thn"}
    },
      pastUnits: {
      "SECOND": {"1":"1 detik yang lalu","0":"0 detik yang lalu","other":"{0} detik yang lalu"},
      "MINUTE": {"1":"1 menit yang lalu","0":"0 menit yang lalu","other":"{0} menit yang lalu"},
      "HOUR": {"1":"1 jam yang lalu","0":"0 jam yang lalu","other":"{0} jam yang lalu"},
      "DAY": {"1":"1 hari yang lalu","0":"0 hari yang lalu","other":"{0} hari yang lalu"},
      "WEEK": {"1":"1 minggu yang lalu","0":"0 minggu yang lalu","other":"{0} minggu yang lalu"},
      "MONTH": {"1":"1 bulan yang lalu","0":"0 bulan yang lalu","other":"{0} bulan yang lalu"},
      "YEAR": {"1":"1 tahun yang lalu","0":"0 tahun yang lalu","other":"{0} tahun yang lalu"}
    },
      futureUnits: {
      "SECOND": {"1":"Dalam 1 detik","0":"Dalam 0 detik","other":"Dalam {0} detik"},
      "MINUTE": {"1":"Dalam 1 menit","0":"Dalam 0 menit","other":"Dalam {0} menit"},
      "HOUR": {"1":"Dalam 1 jam","0":"Dalam 0 jam","other":"Dalam {0} jam"},
      "DAY": {"1":"Dalam 1 hari","0":"Dalam 0 hari","other":"Dalam {0} hari"},
      "WEEK": {"1":"Dalam 1 minggu","0":"Dalam 0 minggu","other":"Dalam {0} minggu"},
      "MONTH": {"1":"Dalam 1 bulan","0":"Dalam 0 bulan","other":"Dalam {0} bulan"},
      "YEAR": {"1":"Dalam 1 tahun","0":"Dalam 0 tahun","other":"Dalam {0} tahun"}
    });

