// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "package:intl_data_gen/bin/intl_data_gen.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.KK;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"other":"{0} секунд"},
      "MINUTE": {"other":"{0} минут"},
      "HOUR": {"other":"{0} сағат"},
      "DAY": {"other":"{0} тәулік"},
      "WEEK": {"other":"{0} апта"},
      "MONTH": {"other":"{0} ай"},
      "YEAR": {"other":"{0} жыл"}
    },
      shortUnits: {
      "SECOND": {},
      "MINUTE": {},
      "HOUR": {},
      "DAY": {},
      "WEEK": {},
      "MONTH": {},
      "YEAR": {}
    },
      pastUnits: {
      "SECOND": {"other":"{0} секунд бұрын"},
      "MINUTE": {"other":"{0} минут бұрын"},
      "HOUR": {"other":"{0} сағат бұрын"},
      "DAY": {"other":"{0} күн бұрын"},
      "WEEK": {"other":"{0} апта бұрын"},
      "MONTH": {"other":"{0} ай бұрын"},
      "YEAR": {"other":"{0} жыл бұрын"}
    },
      futureUnits: {
      "SECOND": {"other":"{0} секундтан кейін"},
      "MINUTE": {"other":"{0} минуттан кейін"},
      "HOUR": {"other":"{0} сағаттан кейін"},
      "DAY": {"other":"{0} күннен кейін"},
      "WEEK": {"other":"{0} аптадан кейін"},
      "MONTH": {"other":"{0} айдан кейін"},
      "YEAR": {"other":"{0} жылдан кейін"}
    });

