// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "package:intl_data_gen/bin/intl_data_gen.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.MR;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"0":"0 सेकंद","1":"1 सेकंद","other":"{0} सेकंद"},
      "MINUTE": {"0":"0 मिनिटे","1":"1 मिनिट","other":"{0} मिनिटे"},
      "HOUR": {"0":"0 तास","1":"1 तास","other":"{0} तास"},
      "DAY": {"0":"0 दिवस","1":"1 दिवस","other":"{0} दिवस"},
      "WEEK": {"0":"0 आठवडे","1":"1 आठवडा","other":"{0} आठवडे"},
      "MONTH": {"0":"0 महिने","1":"1 महिना","other":"{0} महिने"},
      "YEAR": {"0":"0 वर्षे","1":"1 वर्ष","other":"{0} वर्षे"}
    },
      shortUnits: {
      "SECOND": {"0":"0 से","1":"1 सेकंद","other":"{0} से"},
      "MINUTE": {"0":"0 मि","1":"1 मि","other":"{0} मि"},
      "HOUR": {"0":"0 तास","1":"1 तास","other":"{0} तास"},
      "DAY": {"0":"0 दिवस","1":"1 दिवस","other":"{0} दिवस"},
      "WEEK": {"0":"0 आठवडे","1":"1 आ","other":"{0} आ"},
      "MONTH": {"0":"0 महिने","1":"1 महिना","other":"{0} महिने"},
      "YEAR": {"0":"0 वर्षे","1":"1 वर्ष","other":"{0} वर्षे"}
    },
      pastUnits: {
      "SECOND": {"0":"0 सेकंदांपूर्वी","1":"1 सेकंदापूर्वी","other":"{0} सेकंदांपूर्वी"},
      "MINUTE": {"0":"0 मिनिटांपूर्वी","1":"1 मिनिटापूर्वी","other":"{0} मिनिटांपूर्वी"},
      "HOUR": {"0":"0 तासांपूर्वी","1":"1 तासापूर्वी","other":"{0} तासांपूर्वी"},
      "DAY": {"0":"0 दिवसांपूर्वी","1":"1 दिवसापूर्वी","other":"{0} दिवसांपूर्वी"},
      "WEEK": {"0":"0 आठवड्यांपूर्वी","1":"1 आठवड्या पूर्वी","other":"{0} आठवड्यांपूर्वी"},
      "MONTH": {"0":"0 महिन्यांपूर्वी","1":"1 महिन्यापूर्वी","other":"{0} महिन्यांपूर्वी"},
      "YEAR": {"0":"0 वर्षांपूर्वी","1":"1 वर्षापूर्वी","other":"{0} वर्षांपूर्वी"}
    },
      futureUnits: {
      "SECOND": {"0":"0 सेकंदांत","1":"1 सेकंदात","other":"{0} सेकंदांत"},
      "MINUTE": {"0":"0 मिनिटांत","1":"1 मिनिटात","other":"{0} मिनिटांत"},
      "HOUR": {"0":"0 तासांत","1":"1 तासात","other":"{0} तासांत"},
      "DAY": {"0":"0 दिवसांत","1":"1 दिवसात","other":"{0} दिवसांत"},
      "WEEK": {"0":"0 आठवड्यांत","1":"1 आठवड्यात","other":"{0} आठवड्यांत"},
      "MONTH": {"0":"0 महिन्यांत","1":"1 महिन्यात","other":"{0} महिन्यांत"},
      "YEAR": {"0":"10 वर्षांमध्ये","1":"1 वर्षात","other":"{0} वर्षांमध्ये"}
    });

