// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "package:intl_data_gen/bin/intl_data_gen.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.TO;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"other":"{0} s"},
      "MINUTE": {"other":"{0} m"},
      "HOUR": {"other":"{0} h"},
      "DAY": {"other":"{0} ʻa"},
      "WEEK": {"other":"{0} u"},
      "MONTH": {"other":"{0} m"},
      "YEAR": {"other":"{0} t"}
    },
      shortUnits: {
      "SECOND": {},
      "MINUTE": {},
      "HOUR": {},
      "DAY": {},
      "WEEK": {},
      "MONTH": {},
      "YEAR": {}
    },
      pastUnits: {
      "SECOND": {"other":"ʻosi sekoni ʻe {0}"},
      "MINUTE": {"other":"ʻosi miniti ʻe {0}"},
      "HOUR": {"other":"ʻosi houa ʻe {0}"},
      "DAY": {"other":"ʻosi ʻaho ʻe {0}"},
      "WEEK": {"other":"uike ʻe {0} kuo hili"},
      "MONTH": {"other":"māhina ʻe {0} kuo hili"},
      "YEAR": {"other":"taʻu ʻe {0} kuo hili"}
    },
      futureUnits: {
      "SECOND": {"other":"ʻi he sekoni ʻe {0}"},
      "MINUTE": {"other":"ʻi he miniti ʻe {0}"},
      "HOUR": {"other":"ʻi he houa ʻe {0}"},
      "DAY": {"other":"ʻi he ʻaho ʻe {0}"},
      "WEEK": {"other":"ʻi he uike ʻe {0}"},
      "MONTH": {"other":"ʻi he māhina ʻe {0}"},
      "YEAR": {"other":"ʻi he taʻu ʻe {0}"}
    });

