// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/relative_time/code_build.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.VI;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"other":"{0} giây"},
      "MINUTE": {"other":"{0} phút"},
      "HOUR": {"other":"{0} giờ"},
      "DAY": {"other":"{0} ngày"},
      "WEEK": {"other":"{0} tuần"},
      "MONTH": {"other":"{0} tháng"},
      "YEAR": {"other":"{0} năm"}
    },
      shortUnits: {
      "SECOND": {"other":"{0} s"},
      "MINUTE": {"other":"{0} ph"},
      "HOUR": {"other":"{0} g"},
      "DAY": {"other":"{0} ngày"},
      "WEEK": {"other":"{0} tuần"},
      "MONTH": {"other":"{0} tháng"},
      "YEAR": {"other":"{0} năm"}
    },
      pastUnits: {
      "SECOND": {"1":"1 giây trước","0":"0 giây trước","other":"{0} giây trước"},
      "MINUTE": {"1":"1 phút trước","0":"0 phút trước","other":"{0} phút trước"},
      "HOUR": {"1":"1 giờ trước","0":"0 giờ trước","other":"{0} giờ trước"},
      "DAY": {"1":"1 ngày trước","0":"0 ngày trước","other":"{0} ngày trước"},
      "WEEK": {"1":"1 tuần trước","0":"0 tuần trước","other":"{0} tuần trước"},
      "MONTH": {"1":"1 tháng trước","0":"0 tháng trước","other":"{0} tháng trước"},
      "YEAR": {"1":"1 năm trước","0":"0 năm trước","other":"{0} năm trước"}
    },
      futureUnits: {
      "SECOND": {"1":"Trong 1 giây","0":"Trong 0 giây","other":"Trong {0} giây"},
      "MINUTE": {"1":"Trong 1 phút","0":"Trong 0 phút","other":"Trong {0} phút"},
      "HOUR": {"1":"Trong 1 giờ","0":"Trong 0 giờ","other":"Trong {0} giờ"},
      "DAY": {"1":"Trong 1 ngày","0":"Trong 0 ngày","other":"Trong {0} ngày"},
      "WEEK": {"1":"Trong 1 tuần","0":"Trong 0 tuần","other":"Trong {0} tuần"},
      "MONTH": {"1":"Trong 1 tháng","0":"Trong 0 tháng","other":"Trong {0} tháng"},
      "YEAR": {"1":"Trong 1 năm","0":"Trong 0 năm","other":"Trong {0} năm"}
    });

