// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "package:intl_data_gen/bin/intl_data_gen.dart"
// 
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library intlx.relative_time.data.ZH_HK;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"other":"{0}秒"},
      "MINUTE": {"other":"{0}分"},
      "HOUR": {"other":"{0}小時"},
      "DAY": {"other":"{0}日"},
      "WEEK": {"other":"{0}週"},
      "MONTH": {"other":"{0}月"},
      "YEAR": {"other":"{0}年"}
    },
      shortUnits: {
      "SECOND": {"other":"{0}秒"},
      "MINUTE": {"other":"{0}分"},
      "HOUR": {"other":"{0}小時"},
      "DAY": {"other":"{0}日"},
      "WEEK": {"other":"{0}週"},
      "MONTH": {"other":"{0}月"},
      "YEAR": {"other":"{0}年"}
    },
      pastUnits: {
      "SECOND": {"0":"0 秒前","1":"1 秒前","other":"{0} 秒前"},
      "MINUTE": {"0":"0 分鐘前","1":"1 分鐘前","other":"{0} 分鐘前"},
      "HOUR": {"0":"0 小時前","1":"1 小時前","other":"{0} 小時前"},
      "DAY": {"0":"0 天前","1":"1 天前","other":"{0} 天前"},
      "WEEK": {"0":"0 週前","1":"1 週前","other":"{0} 週前"},
      "MONTH": {"0":"0 個月前","1":"1 個月前","other":"{0} 個月前"},
      "YEAR": {"0":"0 年前","1":"1 年前","other":"{0} 年前"}
    },
      futureUnits: {
      "SECOND": {"0":"0 秒後","1":"1 秒後","other":"{0} 秒後"},
      "MINUTE": {"0":"0 分鐘後","1":"1 分鐘後","other":"{0} 分鐘後"},
      "HOUR": {"0":"0 小時後","1":"1 小時後","other":"{0} 小時後"},
      "DAY": {"0":"0 天後","1":"1 天後","other":"{0} 天後"},
      "WEEK": {"0":"0 週後","1":"1 週後","other":"{0} 週後"},
      "MONTH": {"0":"0 個月後","1":"1 個月後","other":"{0} 個月後"},
      "YEAR": {"0":"0 年後","1":"1 年後","other":"{0} 年後"}
    });

