// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"

library relative_time_symbols_data;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

part 'package:intlx/src/relative_time/data/af.dart';
part 'package:intlx/src/relative_time/data/am.dart';
part 'package:intlx/src/relative_time/data/ar.dart';
part 'package:intlx/src/relative_time/data/bg.dart';
part 'package:intlx/src/relative_time/data/bn.dart';
part 'package:intlx/src/relative_time/data/ca.dart';
part 'package:intlx/src/relative_time/data/cs.dart';
part 'package:intlx/src/relative_time/data/da.dart';
part 'package:intlx/src/relative_time/data/de.dart';
part 'package:intlx/src/relative_time/data/de_AT.dart';
part 'package:intlx/src/relative_time/data/de_CH.dart';
part 'package:intlx/src/relative_time/data/el.dart';
part 'package:intlx/src/relative_time/data/en.dart';
part 'package:intlx/src/relative_time/data/en_AU.dart';
part 'package:intlx/src/relative_time/data/en_GB.dart';
part 'package:intlx/src/relative_time/data/en_IE.dart';
part 'package:intlx/src/relative_time/data/en_IN.dart';
part 'package:intlx/src/relative_time/data/en_SG.dart';
part 'package:intlx/src/relative_time/data/en_US.dart';
part 'package:intlx/src/relative_time/data/en_ZA.dart';
part 'package:intlx/src/relative_time/data/es.dart';
part 'package:intlx/src/relative_time/data/es_419.dart';
part 'package:intlx/src/relative_time/data/et.dart';
part 'package:intlx/src/relative_time/data/eu.dart';
part 'package:intlx/src/relative_time/data/fa.dart';
part 'package:intlx/src/relative_time/data/fi.dart';
part 'package:intlx/src/relative_time/data/fil.dart';
part 'package:intlx/src/relative_time/data/fr.dart';
part 'package:intlx/src/relative_time/data/fr_CA.dart';
part 'package:intlx/src/relative_time/data/gl.dart';
part 'package:intlx/src/relative_time/data/gsw.dart';
part 'package:intlx/src/relative_time/data/gu.dart';
part 'package:intlx/src/relative_time/data/he.dart';
part 'package:intlx/src/relative_time/data/hi.dart';
part 'package:intlx/src/relative_time/data/hr.dart';
part 'package:intlx/src/relative_time/data/hu.dart';
part 'package:intlx/src/relative_time/data/id.dart';
part 'package:intlx/src/relative_time/data/in.dart';
part 'package:intlx/src/relative_time/data/is.dart';
part 'package:intlx/src/relative_time/data/it.dart';
part 'package:intlx/src/relative_time/data/iw.dart';
part 'package:intlx/src/relative_time/data/ja.dart';
part 'package:intlx/src/relative_time/data/kn.dart';
part 'package:intlx/src/relative_time/data/ko.dart';
part 'package:intlx/src/relative_time/data/ln.dart';
part 'package:intlx/src/relative_time/data/lt.dart';
part 'package:intlx/src/relative_time/data/lv.dart';
part 'package:intlx/src/relative_time/data/ml.dart';
part 'package:intlx/src/relative_time/data/mr.dart';
part 'package:intlx/src/relative_time/data/ms.dart';
part 'package:intlx/src/relative_time/data/mt.dart';
part 'package:intlx/src/relative_time/data/nl.dart';
part 'package:intlx/src/relative_time/data/no.dart';
part 'package:intlx/src/relative_time/data/or.dart';
part 'package:intlx/src/relative_time/data/pl.dart';
part 'package:intlx/src/relative_time/data/pt.dart';
part 'package:intlx/src/relative_time/data/pt_BR.dart';
part 'package:intlx/src/relative_time/data/pt_PT.dart';
part 'package:intlx/src/relative_time/data/ro.dart';
part 'package:intlx/src/relative_time/data/ru.dart';
part 'package:intlx/src/relative_time/data/sk.dart';
part 'package:intlx/src/relative_time/data/sl.dart';
part 'package:intlx/src/relative_time/data/sq.dart';
part 'package:intlx/src/relative_time/data/sr.dart';
part 'package:intlx/src/relative_time/data/sv.dart';
part 'package:intlx/src/relative_time/data/sw.dart';
part 'package:intlx/src/relative_time/data/ta.dart';
part 'package:intlx/src/relative_time/data/te.dart';
part 'package:intlx/src/relative_time/data/th.dart';
part 'package:intlx/src/relative_time/data/tl.dart';
part 'package:intlx/src/relative_time/data/tr.dart';
part 'package:intlx/src/relative_time/data/uk.dart';
part 'package:intlx/src/relative_time/data/ur.dart';
part 'package:intlx/src/relative_time/data/vi.dart';
part 'package:intlx/src/relative_time/data/zh.dart';
part 'package:intlx/src/relative_time/data/zh_CN.dart';
part 'package:intlx/src/relative_time/data/zh_HK.dart';
part 'package:intlx/src/relative_time/data/zh_TW.dart';
part 'package:intlx/src/relative_time/data/zu.dart';
