/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_list;

const relative_timeLocales = const <String> ["af","am","ar","bg","bn","ca","cs","da","de","de_AT","de_CH","el","en","en_AU","en_GB","en_IE","en_IN","en_SG","en_US","en_ZA","es","es_419","et","eu","fa","fi","fil","fr","fr_CA","gl","gsw","gu","he","hi","hr","hu","id","in","is","it","iw","ja","kn","ko","ln","lt","lv","ml","mr","ms","mt","nl","no","or","pl","pt","pt_BR","pt_PT","ro","ru","sk","sl","sq","sr","sv","sw","ta","te","th","tl","tr","uk","ur","vi","zh","zh_CN","zh_HK","zh_TW","zu"];
  