/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library all;

import '../src/internal.dart';
import '../src/locale/en.dart' as en;

void init() {
  var locales = [en.locale];
  
  locales.forEach(registerSymbols);
}
