/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_bn;

import '../src/internal.dart';
import '../src/locale/bn.dart' as relative_time_symbols_bn;

void init() {
  registerSymbols(relative_time_symbols_bn.locale);
}
