/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

#library("relative_time_locale_ca");

#import("../src/internal.dart");
#import("../src/locale/ca.dart", prefix: "ca");

void init() {
  registerSymbols(ca.locale);
}
