/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

#library("relative_time_locale_da");

#import("../src/internal.dart");
#import("../src/locale/da.dart", prefix: "da");

void init() {
  registerSymbols(da.locale);
}
