/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_da;

import '../src/internal.dart';
import '../src/locale/da.dart' as relative_time_symbols_da;

void init() {
  registerSymbols(relative_time_symbols_da.locale);
}
