/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_de;

import '../src/internal.dart';
import '../src/locale/de.dart' as relative_time_symbols_de;

void init() {
  registerSymbols(relative_time_symbols_de.locale);
}
