/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library de;

import '../src/internal.dart';
import '../src/locale/de.dart' as de;

void init() {
  registerSymbols(de.locale);
}
