/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_en;

import '../src/internal.dart';
import '../src/locale/en.dart' as relative_time_symbols_en;

void init() {
  registerSymbols(relative_time_symbols_en.locale);
}
