/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_en_AU;

import '../src/internal.dart';
import '../src/locale/en_AU.dart' as relative_time_symbols_en_AU;

void init() {
  registerSymbols(relative_time_symbols_en_AU.locale);
}
