/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

#library("relative_time_locale_en_GB");

#import("../src/internal.dart");
#import("../src/locale/en_GB.dart", prefix: "en_GB");

void init() {
  registerSymbols(en_GB.locale);
}
