/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_en_SG;

import '../src/internal.dart';
import '../src/locale/en_SG.dart' as relative_time_symbols_en_SG;

void init() {
  registerSymbols(relative_time_symbols_en_SG.locale);
}
