/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library es;

import '../src/internal.dart';
import '../src/locale/es.dart' as es;

void init() {
  registerSymbols(es.locale);
}
