/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_es_419;

import '../src/internal.dart';
import '../src/locale/es_419.dart' as relative_time_symbols_es_419;

void init() {
  registerSymbols(relative_time_symbols_es_419.locale);
}
