/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_et;

import '../src/internal.dart';
import '../src/locale/et.dart' as relative_time_symbols_et;

void init() {
  registerSymbols(relative_time_symbols_et.locale);
}
