/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_eu;

import '../src/internal.dart';
import '../src/locale/eu.dart' as relative_time_symbols_eu;

void init() {
  registerSymbols(relative_time_symbols_eu.locale);
}
