/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library fr;

import '../src/internal.dart';
import '../src/locale/fr.dart' as fr;

void init() {
  registerSymbols(fr.locale);
}
