/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_fr;

import '../src/internal.dart';
import '../src/locale/fr.dart' as relative_time_symbols_fr;

void init() {
  registerSymbols(relative_time_symbols_fr.locale);
}
