/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

#library("relative_time_locale_gl");

#import("../src/internal.dart");
#import("../src/locale/gl.dart", prefix: "gl");

void init() {
  registerSymbols(gl.locale);
}
