/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_he;

import '../src/internal.dart';
import '../src/locale/he.dart' as relative_time_symbols_he;

void init() {
  registerSymbols(relative_time_symbols_he.locale);
}
