/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_in;

import '../src/internal.dart';
import '../src/locale/in.dart' as relative_time_symbols_in;

void init() {
  registerSymbols(relative_time_symbols_in.locale);
}
