/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library it;

import '../src/internal.dart';
import '../src/locale/it.dart' as it;

void init() {
  registerSymbols(it.locale);
}
