/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

#library("relative_time_locale_jp");

#import("../src/internal.dart");
#import("../src/locale/jp.dart", prefix: "jp");

void init() {
  registerSymbols(jp.locale);
}
