/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

#library("relative_time_locale_ko");

#import("../src/internal.dart");
#import("../src/locale/ko.dart", prefix: "ko");

void init() {
  registerSymbols(ko.locale);
}
