/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library ko;

import '../src/internal.dart';
import '../src/locale/ko.dart' as ko;

void init() {
  registerSymbols(ko.locale);
}
