/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_mr;

import '../src/internal.dart';
import '../src/locale/mr.dart' as relative_time_symbols_mr;

void init() {
  registerSymbols(relative_time_symbols_mr.locale);
}
