/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_ms;

import '../src/internal.dart';
import '../src/locale/ms.dart' as relative_time_symbols_ms;

void init() {
  registerSymbols(relative_time_symbols_ms.locale);
}
