/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_mt;

import '../src/internal.dart';
import '../src/locale/mt.dart' as relative_time_symbols_mt;

void init() {
  registerSymbols(relative_time_symbols_mt.locale);
}
