/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

#library("relative_time_locale_nb");

#import("../src/internal.dart");
#import("../src/locale/nb.dart", prefix: "nb");

void init() {
  registerSymbols(nb.locale);
}
