/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library nb;

import '../src/internal.dart';
import '../src/locale/nb.dart' as nb;

void init() {
  registerSymbols(nb.locale);
}
