/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

#library("relative_time_locale_nl");

#import("../src/internal.dart");
#import("../src/locale/nl.dart", prefix: "nl");

void init() {
  registerSymbols(nl.locale);
}
