/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library pt;

import '../src/internal.dart';
import '../src/locale/pt.dart' as pt;

void init() {
  registerSymbols(pt.locale);
}
