/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_pt;

import '../src/internal.dart';
import '../src/locale/pt.dart' as relative_time_symbols_pt;

void init() {
  registerSymbols(relative_time_symbols_pt.locale);
}
