/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

#library("relative_time_locale_pt");

#import("../src/internal.dart");
#import("../src/locale/pt.dart", prefix: "pt");

void init() {
  registerSymbols(pt.locale);
}
