/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_pt_PT;

import '../src/internal.dart';
import '../src/locale/pt_PT.dart' as relative_time_symbols_pt_PT;

void init() {
  registerSymbols(relative_time_symbols_pt_PT.locale);
}
