/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_ru;

import '../src/internal.dart';
import '../src/locale/ru.dart' as relative_time_symbols_ru;

void init() {
  registerSymbols(relative_time_symbols_ru.locale);
}
