/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_sk;

import '../src/internal.dart';
import '../src/locale/sk.dart' as relative_time_symbols_sk;

void init() {
  registerSymbols(relative_time_symbols_sk.locale);
}
