/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library sv;

import '../src/internal.dart';
import '../src/locale/sv.dart' as sv;

void init() {
  registerSymbols(sv.locale);
}
