/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_sw;

import '../src/internal.dart';
import '../src/locale/sw.dart' as relative_time_symbols_sw;

void init() {
  registerSymbols(relative_time_symbols_sw.locale);
}
