/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_te;

import '../src/internal.dart';
import '../src/locale/te.dart' as relative_time_symbols_te;

void init() {
  registerSymbols(relative_time_symbols_te.locale);
}
