/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_th;

import '../src/internal.dart';
import '../src/locale/th.dart' as relative_time_symbols_th;

void init() {
  registerSymbols(relative_time_symbols_th.locale);
}
