/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

#library("relative_time_locale_tr");

#import("../src/internal.dart");
#import("../src/locale/tr.dart", prefix: "tr");

void init() {
  registerSymbols(tr.locale);
}
