/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_tr;

import '../src/internal.dart';
import '../src/locale/tr.dart' as relative_time_symbols_tr;

void init() {
  registerSymbols(relative_time_symbols_tr.locale);
}
