/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library zh_CN;

import '../src/internal.dart';
import '../src/locale/zh_CN.dart' as zh_CN;

void init() {
  registerSymbols(zh_CN.locale);
}
