/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library tempora_locale_zu;

import '../src/internal.dart';
import '../src/locale/zu.dart' as relative_time_symbols_zu;

void init() {
  registerSymbols(relative_time_symbols_zu.locale);
}
