/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/plural/code_build.dart"

library plural_locale_ar;

import 'package:intlx/src/plural/plural.dart';
import 'package:intlx/src/plural/locale/ar.dart' as plural_symbols_ar;

void init() {
  PluralLocaleImpl.map['ar'] = plural_symbols_ar.symbols;
}
  