/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/locale_build.dart"

library plural_locale_asa;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/asa.dart' as plural_symbols_asa;

  void init() {
  PluralLocaleImpl.map['asa'] = plural_symbols_asa.symbols;
  }
  