/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_az;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/az.dart' as plural_symbols_az;

  void init() {
  PluralLocaleImpl.map['az'] = plural_symbols_az.symbols;
  }
  