/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_bem;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/bem.dart' as plural_symbols_bem;
  
  void init() {
  PluralLocaleImpl.map['bem'] = plural_symbols_bem.symbols;
  }
  