/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/plural/code_build.dart"

library plural_locale_bh;

import 'package:intlx/src/plural/plural.dart';
import 'package:intlx/src/plural/locale/bh.dart' as plural_symbols_bh;

void init() {
  PluralLocaleImpl.map['bh'] = plural_symbols_bh.symbols;
}
  