/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_bm;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/bm.dart' as plural_symbols_bm;

  void init() {
  PluralLocaleImpl.map['bm'] = plural_symbols_bm.symbols;
  }
  