/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_bo;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/bo.dart' as plural_symbols_bo;
  
  void init() {
  PluralLocaleImpl.map['bo'] = plural_symbols_bo.symbols;
  }
  