/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/locale_build.dart"

library plural_locale_bs;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/bs.dart' as plural_symbols_bs;

  void init() {
  PluralLocaleImpl.map['bs'] = plural_symbols_bs.symbols;
  }
  