/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_ca;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/ca.dart' as plural_symbols_ca;

  void init() {
  PluralLocaleImpl.map['ca'] = plural_symbols_ca.symbols;
  }
  