/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_cgg;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/cgg.dart' as plural_symbols_cgg;

  void init() {
  PluralLocaleImpl.map['cgg'] = plural_symbols_cgg.symbols;
  }
  