/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_chr;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/chr.dart' as plural_symbols_chr;

  void init() {
  PluralLocaleImpl.map['chr'] = plural_symbols_chr.symbols;
  }
  