/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_cy;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/cy.dart' as plural_symbols_cy;
  
  void init() {
  PluralLocaleImpl.map['cy'] = plural_symbols_cy.symbols;
  }
  