/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_da;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/da.dart' as plural_symbols_da;

  void init() {
  PluralLocaleImpl.map['da'] = plural_symbols_da.symbols;
  }
  