/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_de;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/de.dart' as plural_symbols_de;

  void init() {
  PluralLocaleImpl.map['de'] = plural_symbols_de.symbols;
  }
  