// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/plural/code_build.dart"

library plural_locale_dv;

import 'package:intlx/src/plural/plural.dart';
import 'package:intlx/src/plural/locale/dv.dart' as plural_symbols_dv;

void init() {
  PluralLocaleImpl.map['dv'] = plural_symbols_dv.symbols;
}
  