/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_el;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/el.dart' as plural_symbols_el;

  void init() {
  PluralLocaleImpl.map['el'] = plural_symbols_el.symbols;
  }
  