/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_en;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/en.dart' as plural_symbols_en;
  
  void init() {
  PluralLocaleImpl.map['en'] = plural_symbols_en.symbols;
  }
  