/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/locale_build.dart"

library plural_locale_en;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/en.dart' as plural_symbols_en;

  void init() {
  PluralLocaleImpl.map['en'] = plural_symbols_en.symbols;
  }
  