/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_et;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/et.dart' as plural_symbols_et;
  
  void init() {
  PluralLocaleImpl.map['et'] = plural_symbols_et.symbols;
  }
  