/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/locale_build.dart"

library plural_locale_eu;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/eu.dart' as plural_symbols_eu;

  void init() {
  PluralLocaleImpl.map['eu'] = plural_symbols_eu.symbols;
  }
  