/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_eu;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/eu.dart' as plural_symbols_eu;
  
  void init() {
  PluralLocaleImpl.map['eu'] = plural_symbols_eu.symbols;
  }
  