/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_fa;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/fa.dart' as plural_symbols_fa;

  void init() {
  PluralLocaleImpl.map['fa'] = plural_symbols_fa.symbols;
  }
  