/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_fo;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/fo.dart' as plural_symbols_fo;

  void init() {
  PluralLocaleImpl.map['fo'] = plural_symbols_fo.symbols;
  }
  