/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_fo;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/fo.dart' as plural_symbols_fo;
  
  void init() {
  PluralLocaleImpl.map['fo'] = plural_symbols_fo.symbols;
  }
  