/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_fur;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/fur.dart' as plural_symbols_fur;

  void init() {
  PluralLocaleImpl.map['fur'] = plural_symbols_fur.symbols;
  }
  