/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_fy;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/fy.dart' as plural_symbols_fy;
  
  void init() {
  PluralLocaleImpl.map['fy'] = plural_symbols_fy.symbols;
  }
  