/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_ga;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/ga.dart' as plural_symbols_ga;
  
  void init() {
  PluralLocaleImpl.map['ga'] = plural_symbols_ga.symbols;
  }
  