/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/plural/code_build.dart"

library plural_locale_ga;

import 'package:intlx/src/plural/plural.dart';
import 'package:intlx/src/plural/locale/ga.dart' as plural_symbols_ga;

void init() {
  PluralLocaleImpl.map['ga'] = plural_symbols_ga.symbols;
}
  