/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_guw;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/guw.dart' as plural_symbols_guw;

  void init() {
  PluralLocaleImpl.map['guw'] = plural_symbols_guw.symbols;
  }
  