/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_he;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/he.dart' as plural_symbols_he;
  
  void init() {
  PluralLocaleImpl.map['he'] = plural_symbols_he.symbols;
  }
  