/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_hr;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/hr.dart' as plural_symbols_hr;

  void init() {
  PluralLocaleImpl.map['hr'] = plural_symbols_hr.symbols;
  }
  