/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_ig;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/ig.dart' as plural_symbols_ig;
  
  void init() {
  PluralLocaleImpl.map['ig'] = plural_symbols_ig.symbols;
  }
  