/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_iw;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/iw.dart' as plural_symbols_iw;

  void init() {
  PluralLocaleImpl.map['iw'] = plural_symbols_iw.symbols;
  }
  