/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/locale_build.dart"

library plural_locale_jv;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/jv.dart' as plural_symbols_jv;

  void init() {
  PluralLocaleImpl.map['jv'] = plural_symbols_jv.symbols;
  }
  