/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/locale_build.dart"

library plural_locale_kaj;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/kaj.dart' as plural_symbols_kaj;

  void init() {
  PluralLocaleImpl.map['kaj'] = plural_symbols_kaj.symbols;
  }
  