/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_kaj;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/kaj.dart' as plural_symbols_kaj;
  
  void init() {
  PluralLocaleImpl.map['kaj'] = plural_symbols_kaj.symbols;
  }
  