/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_kcg;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/kcg.dart' as plural_symbols_kcg;

  void init() {
  PluralLocaleImpl.map['kcg'] = plural_symbols_kcg.symbols;
  }
  