/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_kde;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/kde.dart' as plural_symbols_kde;

  void init() {
  PluralLocaleImpl.map['kde'] = plural_symbols_kde.symbols;
  }
  