/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_kk;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/kk.dart' as plural_symbols_kk;
  
  void init() {
  PluralLocaleImpl.map['kk'] = plural_symbols_kk.symbols;
  }
  