/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/plural/code_build.dart"

library plural_locale_kk;

import 'package:intlx/src/plural/plural.dart';
import 'package:intlx/src/plural/locale/kk.dart' as plural_symbols_kk;

void init() {
  PluralLocaleImpl.map['kk'] = plural_symbols_kk.symbols;
}
  