/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/plural/code_build.dart"

library plural_locale_km;

import 'package:intlx/src/plural/plural.dart';
import 'package:intlx/src/plural/locale/km.dart' as plural_symbols_km;

void init() {
  PluralLocaleImpl.map['km'] = plural_symbols_km.symbols;
}
  