/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_kn;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/kn.dart' as plural_symbols_kn;

  void init() {
  PluralLocaleImpl.map['kn'] = plural_symbols_kn.symbols;
  }
  