/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_ksh;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/ksh.dart' as plural_symbols_ksh;

  void init() {
  PluralLocaleImpl.map['ksh'] = plural_symbols_ksh.symbols;
  }
  