/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/locale_build.dart"

library plural_locale_kw;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/kw.dart' as plural_symbols_kw;

  void init() {
  PluralLocaleImpl.map['kw'] = plural_symbols_kw.symbols;
  }
  