/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/locale_build.dart"

library plural_locale_lo;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/lo.dart' as plural_symbols_lo;

  void init() {
  PluralLocaleImpl.map['lo'] = plural_symbols_lo.symbols;
  }
  