/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_lt;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/lt.dart' as plural_symbols_lt;
  
  void init() {
  PluralLocaleImpl.map['lt'] = plural_symbols_lt.symbols;
  }
  