/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_mk;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/mk.dart' as plural_symbols_mk;
  
  void init() {
  PluralLocaleImpl.map['mk'] = plural_symbols_mk.symbols;
  }
  