/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_ml;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/ml.dart' as plural_symbols_ml;
  
  void init() {
  PluralLocaleImpl.map['ml'] = plural_symbols_ml.symbols;
  }
  