/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/plural/code_build.dart"

library plural_locale_mn;

import 'package:intlx/src/plural/plural.dart';
import 'package:intlx/src/plural/locale/mn.dart' as plural_symbols_mn;

void init() {
  PluralLocaleImpl.map['mn'] = plural_symbols_mn.symbols;
}
  