/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_ms;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/ms.dart' as plural_symbols_ms;

  void init() {
  PluralLocaleImpl.map['ms'] = plural_symbols_ms.symbols;
  }
  