/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_mt;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/mt.dart' as plural_symbols_mt;

  void init() {
  PluralLocaleImpl.map['mt'] = plural_symbols_mt.symbols;
  }
  