/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_nb;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/nb.dart' as plural_symbols_nb;

  void init() {
  PluralLocaleImpl.map['nb'] = plural_symbols_nb.symbols;
  }
  