/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_no;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/no.dart' as plural_symbols_no;
  
  void init() {
  PluralLocaleImpl.map['no'] = plural_symbols_no.symbols;
  }
  