/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_nr;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/nr.dart' as plural_symbols_nr;
  
  void init() {
  PluralLocaleImpl.map['nr'] = plural_symbols_nr.symbols;
  }
  