/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_ny;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/ny.dart' as plural_symbols_ny;

  void init() {
  PluralLocaleImpl.map['ny'] = plural_symbols_ny.symbols;
  }
  