/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_nyn;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/nyn.dart' as plural_symbols_nyn;

  void init() {
  PluralLocaleImpl.map['nyn'] = plural_symbols_nyn.symbols;
  }
  