/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_om;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/om.dart' as plural_symbols_om;
  
  void init() {
  PluralLocaleImpl.map['om'] = plural_symbols_om.symbols;
  }
  