/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/plural/code_build.dart"

library plural_locale_pap;

import 'package:intlx/src/plural/plural.dart';
import 'package:intlx/src/plural/locale/pap.dart' as plural_symbols_pap;

void init() {
  PluralLocaleImpl.map['pap'] = plural_symbols_pap.symbols;
}
  