/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_pap;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/pap.dart' as plural_symbols_pap;
  
  void init() {
  PluralLocaleImpl.map['pap'] = plural_symbols_pap.symbols;
  }
  