/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_pl;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/pl.dart' as plural_symbols_pl;
  
  void init() {
  PluralLocaleImpl.map['pl'] = plural_symbols_pl.symbols;
  }
  