/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library plural_locale_ps;

import '../src/internal.dart';

void init() {
  registerLocale(const PluralLocaleImpl("ps", BasicPluralStrategy));
}
