/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_pt;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/pt.dart' as plural_symbols_pt;

  void init() {
  PluralLocaleImpl.map['pt'] = plural_symbols_pt.symbols;
  }
  