/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_ru;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/ru.dart' as plural_symbols_ru;

  void init() {
  PluralLocaleImpl.map['ru'] = plural_symbols_ru.symbols;
  }
  