/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_sah;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/sah.dart' as plural_symbols_sah;

  void init() {
  PluralLocaleImpl.map['sah'] = plural_symbols_sah.symbols;
  }
  