/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/plural/code_build.dart"

library plural_locale_sg;

import 'package:intlx/src/plural/plural.dart';
import 'package:intlx/src/plural/locale/sg.dart' as plural_symbols_sg;

void init() {
  PluralLocaleImpl.map['sg'] = plural_symbols_sg.symbols;
}
  