/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/plural/code_build.dart"

library plural_locale_sl;

import 'package:intlx/src/plural/plural.dart';
import 'package:intlx/src/plural/locale/sl.dart' as plural_symbols_sl;

void init() {
  PluralLocaleImpl.map['sl'] = plural_symbols_sl.symbols;
}
  