/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/locale_build.dart"

library plural_locale_smj;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/smj.dart' as plural_symbols_smj;

  void init() {
  PluralLocaleImpl.map['smj'] = plural_symbols_smj.symbols;
  }
  