/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/locale_build.dart"

library plural_locale_smn;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/smn.dart' as plural_symbols_smn;

  void init() {
  PluralLocaleImpl.map['smn'] = plural_symbols_smn.symbols;
  }
  