/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_sq;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/sq.dart' as plural_symbols_sq;

  void init() {
  PluralLocaleImpl.map['sq'] = plural_symbols_sq.symbols;
  }
  