/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_sr;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/sr.dart' as plural_symbols_sr;
  
  void init() {
  PluralLocaleImpl.map['sr'] = plural_symbols_sr.symbols;
  }
  