/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_sv;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/sv.dart' as plural_symbols_sv;
  
  void init() {
  PluralLocaleImpl.map['sv'] = plural_symbols_sv.symbols;
  }
  