/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_sw;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/sw.dart' as plural_symbols_sw;

  void init() {
  PluralLocaleImpl.map['sw'] = plural_symbols_sw.symbols;
  }
  