/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_syr;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/syr.dart' as plural_symbols_syr;

  void init() {
  PluralLocaleImpl.map['syr'] = plural_symbols_syr.symbols;
  }
  