/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_ta;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/ta.dart' as plural_symbols_ta;
  
  void init() {
  PluralLocaleImpl.map['ta'] = plural_symbols_ta.symbols;
  }
  