/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/plural/code_build.dart"

library plural_locale_te;

import 'package:intlx/src/plural/plural.dart';
import 'package:intlx/src/plural/locale/te.dart' as plural_symbols_te;

void init() {
  PluralLocaleImpl.map['te'] = plural_symbols_te.symbols;
}
  