/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_ti;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/ti.dart' as plural_symbols_ti;

  void init() {
  PluralLocaleImpl.map['ti'] = plural_symbols_ti.symbols;
  }
  