/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_tig;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/tig.dart' as plural_symbols_tig;

  void init() {
  PluralLocaleImpl.map['tig'] = plural_symbols_tig.symbols;
  }
  