/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_tig;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/tig.dart' as plural_symbols_tig;

  void init() {
  PluralLocaleImpl.map['tig'] = plural_symbols_tig.symbols;
  }
  