/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_tk;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/tk.dart' as plural_symbols_tk;

  void init() {
  PluralLocaleImpl.map['tk'] = plural_symbols_tk.symbols;
  }
  