/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_to;

  import '../../src/internal.dart';
  import 'package:intlx/src/plural/locale/to.dart' as plural_symbols_to;
  
  void init() {
  PluralLocaleImpl.map['to'] = plural_symbols_to.symbols;
  }
  