/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library plural_locale_to;

import '../../src/plural/internal.dart';

void init() {
  registerLocale(const PluralLocaleImpl("to", RulelessPluralStrategy));
}
