/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_ts;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/ts.dart' as plural_symbols_ts;

  void init() {
  PluralLocaleImpl.map['ts'] = plural_symbols_ts.symbols;
  }
  