/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_ur;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/ur.dart' as plural_symbols_ur;

  void init() {
  PluralLocaleImpl.map['ur'] = plural_symbols_ur.symbols;
  }
  