/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_locale_ve;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/ve.dart' as plural_symbols_ve;

  void init() {
  PluralLocaleImpl.map['ve'] = plural_symbols_ve.symbols;
  }
  