/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_zh;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/zh.dart' as plural_symbols_zh;

  void init() {
  PluralLocaleImpl.map['zh'] = plural_symbols_zh.symbols;
  }
  