/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_locale_zu;

  import 'package:intlx/src/plural/plural.dart';
  import 'package:intlx/src/plural/locale/zu.dart' as plural_symbols_zu;

  void init() {
  PluralLocaleImpl.map['zu'] = plural_symbols_zu.symbols;
  }
  