/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/code_build.dart"

library iterable_locale_af;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/af.dart' as iterable_symbols_af;

  void init() {
  IterableSymbols.map['af'] = iterable_symbols_af.symbols;
  }
  