/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library iterable_locale_bg;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/bg.dart' as iterable_symbols_bg;

  void init() {
  IterableSymbols.map['bg'] = iterable_symbols_bg.symbols;
  }
  