/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_ca;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/ca.dart' as iterable_symbols_ca;

void init() {
  IterableSymbols.map['ca'] = iterable_symbols_ca.symbols;
}
  