/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_da;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/da.dart' as iterable_symbols_da;

void init() {
  IterableSymbols.map['da'] = iterable_symbols_da.symbols;
}
  