/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library iterable_locale_de_AT;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/de_AT.dart' as iterable_symbols_de_AT;

  void init() {
  IterableSymbols.map['de_AT'] = iterable_symbols_de_AT.symbols;
  }
  