/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/code_build.dart"

library iterable_locale_en;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/en.dart' as iterable_symbols_en;

  void init() {
  IterableSymbols.map['en'] = iterable_symbols_en.symbols;
  }
  