/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/locale_build.dart"

library iterable_locale_en_AU;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/en_AU.dart' as iterable_symbols_en_AU;

  void init() {
  IterableSymbols.map['en_AU'] = iterable_symbols_en_AU.symbols;
  }
  