/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/code_build.dart"

library iterable_locale_en_GB;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/en_GB.dart' as iterable_symbols_en_GB;

  void init() {
  IterableSymbols.map['en_GB'] = iterable_symbols_en_GB.symbols;
  }
  