/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/code_build.dart"

library iterable_locale_en_SG;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/en_SG.dart' as iterable_symbols_en_SG;

  void init() {
  IterableSymbols.map['en_SG'] = iterable_symbols_en_SG.symbols;
  }
  