// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_en_US;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/en_US.dart' as iterable_symbols_en_US;

void init() {
  IterableSymbols.map['en_US'] = iterable_symbols_en_US.symbols;
}
  