/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_es;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/es.dart' as iterable_symbols_es;

void init() {
  IterableSymbols.map['es'] = iterable_symbols_es.symbols;
}
  