/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library iterable_locale_es_419;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/es_419.dart' as iterable_symbols_es_419;

  void init() {
  IterableSymbols.map['es_419'] = iterable_symbols_es_419.symbols;
  }
  