/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_gu;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/gu.dart' as iterable_symbols_gu;

void init() {
  IterableSymbols.map['gu'] = iterable_symbols_gu.symbols;
}
  