/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library iterable_locale_he;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/he.dart' as iterable_symbols_he;

  void init() {
  IterableSymbols.map['he'] = iterable_symbols_he.symbols;
  }
  