/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_hi;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/hi.dart' as iterable_symbols_hi;

void init() {
  IterableSymbols.map['hi'] = iterable_symbols_hi.symbols;
}
  