/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_hr;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/hr.dart' as iterable_symbols_hr;

void init() {
  IterableSymbols.map['hr'] = iterable_symbols_hr.symbols;
}
  