/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/locale_build.dart"

library iterable_locale_hr;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/hr.dart' as iterable_symbols_hr;

  void init() {
  IterableSymbols.map['hr'] = iterable_symbols_hr.symbols;
  }
  