/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/locale_build.dart"

library iterable_locale_id;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/id.dart' as iterable_symbols_id;

  void init() {
  IterableSymbols.map['id'] = iterable_symbols_id.symbols;
  }
  