/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/locale_build.dart"

library iterable_locale_is;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/is.dart' as iterable_symbols_is;

  void init() {
  IterableSymbols.map['is'] = iterable_symbols_is.symbols;
  }
  