/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_ja;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/ja.dart' as iterable_symbols_ja;

void init() {
  IterableSymbols.map['ja'] = iterable_symbols_ja.symbols;
}
  