/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_kn;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/kn.dart' as iterable_symbols_kn;

void init() {
  IterableSymbols.map['kn'] = iterable_symbols_kn.symbols;
}
  