/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library iterable_locale_ko;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/ko.dart' as iterable_symbols_ko;

  void init() {
  IterableSymbols.map['ko'] = iterable_symbols_ko.symbols;
  }
  