/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library iterable_locale_ln;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/ln.dart' as iterable_symbols_ln;

  void init() {
  IterableSymbols.map['ln'] = iterable_symbols_ln.symbols;
  }
  