/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/code_build.dart"

library iterable_locale_lt;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/lt.dart' as iterable_symbols_lt;

  void init() {
  IterableSymbols.map['lt'] = iterable_symbols_lt.symbols;
  }
  