/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/locale_build.dart"

library iterable_locale_ml;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/ml.dart' as iterable_symbols_ml;

  void init() {
  IterableSymbols.map['ml'] = iterable_symbols_ml.symbols;
  }
  