/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/locale_build.dart"

library iterable_locale_ms;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/ms.dart' as iterable_symbols_ms;

  void init() {
  IterableSymbols.map['ms'] = iterable_symbols_ms.symbols;
  }
  