/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library iterable_locale_mt;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/mt.dart' as iterable_symbols_mt;

  void init() {
  IterableSymbols.map['mt'] = iterable_symbols_mt.symbols;
  }
  