/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library iterable_locale_nl;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/nl.dart' as iterable_symbols_nl;

  void init() {
  IterableSymbols.map['nl'] = iterable_symbols_nl.symbols;
  }
  