/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library iterable_locale_no;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/no.dart' as iterable_symbols_no;

  void init() {
  IterableSymbols.map['no'] = iterable_symbols_no.symbols;
  }
  