/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/code_build.dart"

library iterable_locale_pl;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/pl.dart' as iterable_symbols_pl;

  void init() {
  IterableSymbols.map['pl'] = iterable_symbols_pl.symbols;
  }
  