/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_pt;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/pt.dart' as iterable_symbols_pt;

void init() {
  IterableSymbols.map['pt'] = iterable_symbols_pt.symbols;
}
  