/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library iterable_locale_pt_PT;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/pt_PT.dart' as iterable_symbols_pt_PT;

  void init() {
  IterableSymbols.map['pt_PT'] = iterable_symbols_pt_PT.symbols;
  }
  