/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library iterable_locale_sk;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/sk.dart' as iterable_symbols_sk;

  void init() {
  IterableSymbols.map['sk'] = iterable_symbols_sk.symbols;
  }
  