/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_sk;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/sk.dart' as iterable_symbols_sk;

void init() {
  IterableSymbols.map['sk'] = iterable_symbols_sk.symbols;
}
  