/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/code_build.dart"

library iterable_locale_sl;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/sl.dart' as iterable_symbols_sl;

  void init() {
  IterableSymbols.map['sl'] = iterable_symbols_sl.symbols;
  }
  