/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_sv;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/sv.dart' as iterable_symbols_sv;

void init() {
  IterableSymbols.map['sv'] = iterable_symbols_sv.symbols;
}
  