/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_te;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/te.dart' as iterable_symbols_te;

void init() {
  IterableSymbols.map['te'] = iterable_symbols_te.symbols;
}
  