/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/locale_build.dart"

library iterable_locale_tl;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/tl.dart' as iterable_symbols_tl;

  void init() {
  IterableSymbols.map['tl'] = iterable_symbols_tl.symbols;
  }
  