/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_tr;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/tr.dart' as iterable_symbols_tr;

void init() {
  IterableSymbols.map['tr'] = iterable_symbols_tr.symbols;
}
  