/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_ur;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/ur.dart' as iterable_symbols_ur;

void init() {
  IterableSymbols.map['ur'] = iterable_symbols_ur.symbols;
}
  