/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_vi;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/vi.dart' as iterable_symbols_vi;

void init() {
  IterableSymbols.map['vi'] = iterable_symbols_vi.symbols;
}
  