/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library iterable_locale_zh_CN;

  import 'package:intlx/src/iterable/iterable_symbols.dart';
  import 'package:intlx/src/iterable/locale/zh_CN.dart' as iterable_symbols_zh_CN;

  void init() {
  IterableSymbols.map['zh_CN'] = iterable_symbols_zh_CN.symbols;
  }
  