/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_zh_HK;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/zh_HK.dart' as iterable_symbols_zh_HK;

void init() {
  IterableSymbols.map['zh_HK'] = iterable_symbols_zh_HK.symbols;
}
  