/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_zh_TW;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/zh_TW.dart' as iterable_symbols_zh_TW;

void init() {
  IterableSymbols.map['zh_TW'] = iterable_symbols_zh_TW.symbols;
}
  