/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/iterable/code_build.dart"

library iterable_locale_zu;

import 'package:intlx/src/iterable/iterable_symbols.dart';
import 'package:intlx/src/iterable/locale/zu.dart' as iterable_symbols_zu;

void init() {
  IterableSymbols.map['zu'] = iterable_symbols_zu.symbols;
}
  