/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_symbols_bn;

import '../symbols.dart';

const RelativeTimeSymbols locale = const RelativeTimeSymbols(
  name: "bn",
  units: const {
    "second": const {"one":"{0} সেকেন্ড","other":"{0} সেকেন্ড"},
    "minute": const {"one":"{0} মিনিট","other":"{0} মিনিট"},
    "hour": const {"one":"{0} ঘন্টা","other":"{0} ঘন্টা"},
    "day": const {"one":"{0} দিন","other":"{0} দিন"},
    "week": const {"one":"{0} সপ্তাহ","other":"{0} সপ্তাহ"},
    "month": const {"one":"{0} মাস","other":"{0} মাস"},
    "year": const {"one":"{0} বছর","other":"{0} বছর"}
  },
  shortUnits: const {
    "second": const {"1":"১ সেকেন্ড","0":"০ সেকেন্ড","other":"{0} সেকেন্ড"},
    "minute": const {"1":"1 মিনিট","0":"0 মিনিট","other":"{0} মিনিট"},
    "hour": const {"1":"1 ঘন্টা","0":"0 ঘন্টা","other":"{0} ঘন্টা"},
    "day": const {"1":"1 দিন","0":"0 দিন","other":"{0} দিন"},
    "week": const {"1":"১ সপ্তাহ","0":"0 সপ্তাহ","other":"{0} সপ্তাহ"},
    "month": const {"1":"১ মাস","0":"০ মাস","other":"{0} মাস"},
    "year": const {"1":"১ বছর","0":"০ বছর","other":"{0} বছর"}
  },
  pastUnits: const {
    "second": const {"1":"১ সেকেন্ড পূর্বে","0":"0 সেকেন্ড পূর্বে","other":"{0}সেকেন্ড পূর্বে"},
    "minute": const {"1":"1 মিনিট পূর্বে","0":"0 মিনিট পূর্বে","other":"{0} মিনিট পূর্বে"},
    "hour": const {"1":"১ ঘন্টা আগে","0":"০ ঘন্টা আগে","other":"{0}ঘন্টা আগে"},
    "day": const {"1":"১ দিন পূর্বে","0":"0 দিন পূর্বে","other":"{0} দিন পূর্বে"},
    "week": const {"1":"১ সপ্তাহ পূর্বে","0":"0 সপ্তাহ পূর্বে","other":"{0} সপ্তাহ পূর্বে"},
    "month": const {"1":"১ মাস পূর্বে","0":"0 মাস পূর্বে","other":"{0} মাস পূর্বে"},
    "year": const {"1":"১ বছর পূর্বে","0":"0 বছর পূর্বে","other":"{0} বছর পূর্বে"}
  },
  futureUnits: const {
    "second": const {"1":"১ সেকেন্ডে","0":"০ সেকেন্ডে","other":"{0} সেকেন্ডে"},
    "minute": const {"1":"১ মিনিটে","0":"০মিনিটে","other":"{0} মিনিটে"},
    "hour": const {"1":"১ ঘন্টায়","0":"০ ঘন্টায়","other":"{0} ঘন্টায়"},
    "day": const {"1":"১ দিনের মধ্যে","0":"0 দিনের মধ্যে","other":"{0} দিনের মধ্যে"},
    "week": const {"1":"১ সপ্তাহে","0":"০ সপ্তাহে","other":"{0} সপ্তাহে"},
    "month": const {"1":"১ মাসে","0":"০ মাসে","other":"{0} মাসে"},
    "year": const {"1":"১ বছরে","0":"0 বছরে","other":"{0} বছরে"}
  });
