/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_ca;

import '../symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "second": const {"one":"{0} segon","other":"{0} segons"},
      "minute": const {"one":"{0} minut","other":"{0} minuts"},
      "hour": const {"one":"{0} hora","other":"{0} hores"},
      "day": const {"one":"{0} dia","other":"{0} dies"},
      "week": const {"one":"{0} setmana","other":"{0} setmanes"},
      "month": const {"one":"{0} mes","other":"{0} mesos"},
      "year": const {"one":"{0} any","other":"{0} anys"}
    },
      shortUnits: const {
      "second": const {"one":"{0} s","other":"{0} s"},
      "minute": const {"one":"{0} m","other":"{0} m"},
      "hour": const {"one":"{0} h","other":"{0} h"},
      "day": const {"one":"{0} dia","other":"{0} dies"},
      "week": const {"one":"{0} setmana","other":"{0} setmanes"},
      "month": const {"one":"{0} mes","other":"{0} mesos"},
      "year": const {"one":"{0} any","other":"{0} anys"}
    },
      pastUnits: const {
      "second": const {"1":"Fa 1 segon","one":"Fa {0} segon","0":"Fa 0 segons","other":"Fa {0} segons"},
      "minute": const {"1":"Fa 1 minut","one":"Fa {0} minut","0":"Fa 0 minuts","other":"Fa {0} minuts"},
      "hour": const {"1":"Fa 1 hora","one":"Fa {0} hora","0":"Fa 0 hores","other":"Fa {0} hores"},
      "day": const {"1":"Fa 1 dia","one":"Fa {0} dia","0":"Fa 0 dies","other":"Fa {0} dies"},
      "week": const {"1":"Fa 1 setmana","one":"Fa {0} setmana","0":"Fa 0 setmanes","other":"Fa {0} setmanes"},
      "month": const {"1":"Fa 1 mes","one":"Fa {0} mes","0":"Fa 0 mesos","other":"Fa {0} mesos"},
      "year": const {"1":"Fa 1 any","one":"Fa {0} any","0":"Fa 0 anys","other":"Fa {0} anys"}
    },
      futureUnits: const {
      "second": const {"1":"D'aquí a 1 segon","one":"D'aquí a {0} segon","0":"D'aquí a 0 segons","other":"D'aquí a {0} segons"},
      "minute": const {"1":"D'aquí a 1 minut","one":"D'aquí a {0} minut","0":"D'aquí a 0 minuts","other":"D'aquí a {0} minuts"},
      "hour": const {"1":"D'aquí a 1 hora","one":"D'aquí a {0} hora","0":"D'aquí a 0 hores","other":"D'aquí a {0} hores"},
      "day": const {"1":"D'aquí a 1 dia","one":"D'aquí a {0} dia","0":"D'aquí a 0 dies","other":"D'aquí a {0} dies"},
      "week": const {"1":"D'aquí a 1 setmana","one":"D'aquí a {0} setmana","0":"D'aquí a 0 setmanes","other":"D'aquí a {0} setmanes"},
      "month": const {"1":"D'aquí a 1 mes","one":"D'aquí a {0} mes","0":"D'aquí a 0 mesos","other":"D'aquí a {0} mesos"},
      "year": const {"1":"D'aquí a 1 any","one":"D'aquí a {0} any","0":"D'aquí a 0 anys","other":"D'aquí a {0} anys"}
    });
