/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/relative_time/code_build.dart"

library relative_time_symbols_cs;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "SECOND": const {"one":"{0} sekunda","other":"{0} sekund","few":"{0} sekundy"},
      "MINUTE": const {"one":"{0} minuta","other":"{0} minut","few":"{0} minuty"},
      "HOUR": const {"one":"{0} hodina","other":"{0} hodin","few":"{0} hodiny"},
      "DAY": const {"one":"{0} den","other":"{0} dnÃ­","few":"{0} dny"},
      "WEEK": const {"one":"{0} tÃ½den","other":"{0} tÃ½dnÅ¯","few":"{0} tÃ½dny"},
      "MONTH": const {"one":"{0} mÄsÃ­c","other":"{0} mÄsÃ­cÅ¯","few":"{0} mÄsÃ­ce"},
      "YEAR": const {"one":"{0} rok","other":"{0} let","few":"{0} roky"}
    },
      shortUnits: const {
      "SECOND": const {"one":"{0} sek.","other":"{0} sek.","few":"{0} sek."},
      "MINUTE": const {"one":"{0} min.","other":"{0} min.","few":"{0} min."},
      "HOUR": const {"one":"{0} hod.","other":"{0} hod.","few":"{0} hod."},
      "DAY": const {"one":"{0} den","other":"{0} dnÃ­","few":"{0} dny"},
      "WEEK": const {"one":"{0} tÃ½d.","other":"{0} tÃ½d.","few":"{0} tÃ½d."},
      "MONTH": const {"one":"{0} mÄs.","other":"{0} mÄs.","few":"{0} mÄs."},
      "YEAR": const {"one":"{0} rok","other":"{0} let","few":"{0} roky"}
    },
      pastUnits: const {
      "SECOND": const {"1":"pÅed 1 sekundou","one":"pÅed {0} sekundou","0":"pÅed 0 sekundami","few":"pÅed {0} sekundami","other":"pÅed {0} sekundami"},
      "MINUTE": const {"1":"pÅed 1 minutou","one":"pÅed {0} minutou","0":"pÅed 0 minutami","few":"pÅed {0} minutami","other":"pÅed {0} minutami"},
      "HOUR": const {"1":"pÅed 1 hodinou","one":"pÅed {0} hodinou","0":"pÅed 0 hodinami","few":"pÅed {0} hodinami","other":"pÅed {0} hodinami"},
      "DAY": const {"1":"pÅed 1 dnem","one":"pÅed {0} dnem","0":"pÅed 0 dny","few":"pÅed {0} dny","other":"pÅed {0} dny"},
      "WEEK": const {"1":"pÅed 1 tÃ½dnem","one":"pÅed {0} tÃ½dnem","0":"pÅed 0 tÃ½dny","few":"pÅed {0} tÃ½dny","other":"pÅed {0} tÃ½dny"},
      "MONTH": const {"1":"pÅed 1 mÄsÃ­cem","one":"pÅed {0} mÄsÃ­cem","0":"pÅed 0 mÄsÃ­ci","few":"pÅed {0} mÄsÃ­ci","other":"pÅed {0} mÄsÃ­ci"},
      "YEAR": const {"1":"pÅed 1 rokem","one":"pÅed {0} rokem","0":"pÅed 0 roky","few":"pÅed {0} lety","other":"pÅed {0} lety"}
    },
      futureUnits: const {
      "SECOND": const {"1":"za 1 sekundu","one":"za {0} sekundu","0":"za 0 sekund","few":"za {0} sekundy","other":"za {0} sekund"},
      "MINUTE": const {"1":"za 1 minutu","one":"za {0} minutu","0":"za 0 minut","few":"za {0} minuty","other":"za {0} minut"},
      "HOUR": const {"1":"za 1 hodinu","one":"za {0} hodinu","0":"za 0 hodin","few":"za {0} hodiny","other":"za {0} hodin"},
      "DAY": const {"1":"za 1 den","one":"za {0} den","0":"za 0 dnÃ­","few":"za {0} dny","other":"za {0} dnÃ­"},
      "WEEK": const {"1":"za 1 tÃ½den","one":"za {0} tÃ½den","0":"za 0 tÃ½dnÅ¯","few":"za {0} tÃ½dny","other":"za {0} tÃ½dnÅ¯"},
      "MONTH": const {"1":"za 1 mÄsÃ­c","one":"za {0} mÄsÃ­c","0":"za 0 mÄsÃ­cÅ¯","few":"za {0} mÄsÃ­ce","other":"za {0} mÄsÃ­cÅ¯"},
      "YEAR": const {"1":"za 1 rok","one":"za {0} rok","0":"za 0 rokÅ¯","few":"za {0} roky","other":"za {0} let"}
    });
