/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_da;

import '../symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "second": const {"one":"{0} sekund","other":"{0} sekunder"},
      "minute": const {"one":"{0} minut","other":"{0} minutter"},
      "hour": const {"one":"{0} time","other":"{0} timer"},
      "day": const {"one":"{0} dag","other":"{0} dage"},
      "week": const {"one":"{0} uge","other":"{0} uger"},
      "month": const {"one":"{0} måned","other":"{0} måneder"},
      "year": const {"one":"{0} år","other":"{0} år"}
    },
      shortUnits: const {
      "second": const {"one":"{0} sek.","other":"{0} sek."},
      "minute": const {"one":"{0} min.","other":"{0} min."},
      "hour": const {"one":"{0} t.","other":"{0} t."},
      "day": const {"one":"{0} dag","other":"{0} dage"},
      "week": const {"one":"{0} uge","other":"{0} uger"},
      "month": const {"one":"{0} mdr.","other":"{0} mdr."},
      "year": const {"one":"{0} år","other":"{0} år"}
    },
      pastUnits: const {
      "second": const {"1":"1 sekund siden","one":"for {0} sekund siden","0":"0 sekunder siden","other":"{0} sekunder siden"},
      "minute": const {"1":"1 minut siden","one":"for {0} minut siden","0":"0 minutter siden","other":"{0} minutter siden"},
      "hour": const {"1":"1 time siden","one":"for {0} time siden","0":"0 timer siden","other":"{0} timer siden"},
      "day": const {"1":"1 dag siden","one":"for {0} døgn siden","0":"0 dage siden","other":"{0} dage siden"},
      "week": const {"1":"1 uge siden","one":"for {0} uge siden","0":"0 uger siden","other":"{0} uger siden"},
      "month": const {"1":"1 måned siden","one":"for {0} måned siden","0":"0 måneder siden","other":"{0} måneder siden"},
      "year": const {"1":"1 år siden","one":"for {0} år siden","0":"0 år siden","other":"{0} år siden"}
    },
      futureUnits: const {
      "second": const {"1":"Om 1 sekund","one":"om {0} sekund","0":"Om 0 sekunder","other":"Om {0} sekunder"},
      "minute": const {"1":"Om 1 minut","one":"om {0} minut","0":"Om 0 minutter","other":"Om {0} minutter"},
      "hour": const {"1":"Om 1 time","one":"om {0} time","0":"Om 0 timer","other":"Om {0} timer"},
      "day": const {"1":"Om 1 dag","one":"om {0} døgn","0":"Om 0 dage","other":"Om {0} dage"},
      "week": const {"1":"om 1 uge","one":"om {0} uge","0":"Om 0 uger","other":"Om {0} uger"},
      "month": const {"1":"Om 1 måned","one":"om {0} måned","0":"Om 0 måneder","other":"Om {0} måneder"},
      "year": const {"1":"Om 1 år","one":"om {0} år","0":"Om 0 år","other":"Om {0} år"}
    });
