/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_es_419;

import '../symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "second": const {"one":"{0} segundo","other":"{0} segundos"},
      "minute": const {"one":"{0} minuto","other":"{0} minutos"},
      "hour": const {"one":"{0} hora","other":"{0} horas"},
      "day": const {"one":"{0} día","other":"{0} días"},
      "week": const {"one":"{0} semana","other":"{0} semanas"},
      "month": const {"one":"{0} mes","other":"{0} meses"},
      "year": const {"one":"{0} año","other":"{0} años"}
    },
      shortUnits: const {
      "second": const {"one":"{0} s","other":"{0} s"},
      "minute": const {"one":"{0} min","other":"{0} min"},
      "hour": const {"one":"{0} h","other":"{0} h"},
      "day": const {"one":"{0} día","other":"{0} días"},
      "week": const {"one":"{0} semana","other":"{0} semanas"},
      "month": const {"one":"{0} mes","other":"{0} meses"},
      "year": const {"one":"{0} año","other":"{0} años"}
    },
      pastUnits: const {
      "second": const {"1":"Hace 1 segundo","one":"Hace {0} segundo","0":"Hace 0 segundos","other":"Hace {0} segundos"},
      "minute": const {"1":"Hace 1 minuto","one":"Hace {0} minuto","0":"Hace 0 minutos","other":"Hace {0} minutos"},
      "hour": const {"1":"Hace 1 hora","one":"Hace {0} hora","0":"Hace 0 horas","other":"Hace {0} horas"},
      "day": const {"1":"Hace 1 día","one":"Hace {0} día","0":"Hace 0 días","other":"Hace {0} días"},
      "week": const {"1":"Hace 1 semana","one":"Hace {0} semana","0":"Hace 0 semanas","other":"Hace {0} semanas"},
      "month": const {"1":"Hace 1 mes","one":"Hace {0} mes","0":"Hace 0 meses","other":"Hace {0} meses"},
      "year": const {"1":"Hace 1 año","one":"Hace {0} año","0":"Hace 0 años","other":"Hace {0} años"}
    },
      futureUnits: const {
      "second": const {"1":"En 1 segundo","one":"En {0} segundo","0":"En 0 segundos","other":"En {0} segundos"},
      "minute": const {"1":"En 1 minuto","one":"En {0} minuto","0":"En 0 minutos","other":"En {0} minutos"},
      "hour": const {"1":"En 1 hora","one":"En {0} hora","0":"En 0 horas","other":"En {0} horas"},
      "day": const {"1":"En 1 día","one":"En {0} día","0":"En 0 días","other":"En {0} días"},
      "week": const {"1":"En 1 semana","one":"En {0} semana","0":"En 0 semanas","other":"En {0} semanas"},
      "month": const {"1":"En 1 mes","one":"En {0} mes","0":"En 0 meses","other":"En {0} meses"},
      "year": const {"1":"En 1 año","one":"En {0} año","0":"En 0 años","other":"En {0} años"}
    });
