/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_fi;

import '../symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "second": const {"one":"{0} sekunti","other":"{0} sekuntia"},
      "minute": const {"one":"{0} minuutti","other":"{0} minuuttia"},
      "hour": const {"one":"{0} tunti","other":"{0} tuntia"},
      "day": const {"one":"{0} päivä","other":"{0} päivää"},
      "week": const {"one":"{0} viikko","other":"{0} viikkoa"},
      "month": const {"one":"{0} kuukausi","other":"{0} kuukautta"},
      "year": const {"one":"{0} vuosi","other":"{0} vuotta"}
    },
      shortUnits: const {
      "second": const {"one":"{0} s","other":"{0} s"},
      "minute": const {"one":"{0} min","other":"{0} min"},
      "hour": const {"one":"{0} t","other":"{0} t"},
      "day": const {"one":"{0} pv","other":"{0} pv"},
      "week": const {"one":"{0} vk","other":"{0} vk"},
      "month": const {"one":"{0} kk","other":"{0} kk"},
      "year": const {"one":"{0} v","other":"{0} v"}
    },
      pastUnits: const {
      "second": const {"1":"sekunti sitten","one":"{0} sekunti sitten","0":"alle sekunti sitten","other":"{0} sekuntia sitten"},
      "minute": const {"1":"minuutti sitten","one":"{0} minuutti sitten","0":"alle minuutti sitten","other":"{0} minuuttia sitten"},
      "hour": const {"1":"tunti sitten","one":"{0} tunti sitten","0":"alle tunti sitten","other":"{0} tuntia sitten"},
      "day": const {"1":"päivä sitten","one":"{0} päivä sitten","0":"alle päivä sitten","other":"{0} päivää sitten"},
      "week": const {"1":"viikko sitten","one":"{0} viikko sitten","0":"alle viikko sitten","other":"{0} viikkoa sitten"},
      "month": const {"1":"kuukausi sitten","one":"{0} kuukausi sitten","0":"alle kuukausi sitten","other":"{0} kuukautta sitten"},
      "year": const {"1":"vuosi sitten","one":"{0} vuosi sitten","0":"alle vuosi sitten","other":"{0} vuotta sitten"}
    },
      futureUnits: const {
      "second": const {"1":"sekunnin päästä","one":"{0} sekunnin päästä","0":"alle sekunnin päästä","other":"{0} sekunnin päästä"},
      "minute": const {"1":"minuutin päästä","one":"{0} minuutin päästä","0":"alle minuutin päästä","other":"{0} minuutin päästä"},
      "hour": const {"1":"tunnin päästä","one":"{0} tunnin päästä","0":"alle tunnin päästä","other":"{0} tunnin päästä"},
      "day": const {"1":"päivän päästä","one":"{0} päivän päästä","0":"alle päivän päästä","other":"{0} päivän päästä"},
      "week": const {"1":"viikon päästä","one":"{0} viikon päästä","0":"alle viikon päästä","other":"{0} viikon päästä"},
      "month": const {"1":"kuukauden päästä","one":"{0} kuukauden päästä","0":"alle kuukauden päästä","other":"{0} kuukauden päästä"},
      "year": const {"1":"vuoden päästä","one":"{0} vuoden päästä","0":"alle vuoden päästä","other":"{0} vuoden päästä"}
    });
