/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_fil;

import 'package:intlx/src/relative_time/symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "SECOND": const {"one":"{0} segundo","other":"{0} segundo"},
      "MINUTE": const {"one":"{0} minuto","other":"{0} minuto"},
      "HOUR": const {"one":"{0} oras","other":"{0} oras"},
      "DAY": const {"one":"{0} araw","other":"{0} araw"},
      "WEEK": const {"one":"{0} linggo","other":"{0} linggo"},
      "MONTH": const {"one":"{0} buwan","other":"{0} buwan"},
      "YEAR": const {"one":"{0} taon","other":"{0} taon"}
    },
      shortUnits: const {
      "SECOND": const {"one":"{0} seg","other":"{0} seg"},
      "MINUTE": const {"one":"{0} min","other":"{0} min"},
      "HOUR": const {"one":"{0} or","other":"{0} or"},
      "DAY": const {"one":"{0} arw","other":"{0} arw"},
      "WEEK": const {"one":"{0} ling","other":"{0} ling"},
      "MONTH": const {"one":"{0} buw","other":"{0} buw"},
      "YEAR": const {"one":"{0} ta","other":"{0} ta"}
    },
      pastUnits: const {
      "SECOND": const {"1":"Nakalipas na 1 segundo","0":"Nakalipas na 0 segundo","other":"Nakalipas na {0} (na) segundo"},
      "MINUTE": const {"1":"Nakalipas na 1 minuto","0":"Nakalipas na 0 na minuto","other":"Nakalipas na {0} (na) minuto"},
      "HOUR": const {"1":"Nakalipas na 1 oras","0":"Nakalipas na 0 oras","other":"Nakalipas na {0} (na) oras"},
      "DAY": const {"1":"Nakalipas na 1 araw","0":"Nakalipas na 0 araw","other":"Nakalipas na {0} (na) araw"},
      "WEEK": const {"1":"Nakalipas na 1 linggo","0":"Nakalipas na 0 na linggo","other":"Nakalipas na {0} (na) linggo"},
      "MONTH": const {"1":"Nakalipas na 1 buwan","0":"Nakalipas na 0 buwan","other":"Nakalipas na {0} (na) buwan"},
      "YEAR": const {"1":"Nakalipas na 1 taon","0":"Nakalipas na 0 taon","other":"Nakalipas na {0} (na) taon"}
    },
      futureUnits: const {
      "SECOND": const {"1":"Sa 1 segundo","0":"Sa 0 segundo","other":"Sa {0} (na) segundo"},
      "MINUTE": const {"1":"Sa 1 minuto","0":"Sa 0 minuto","other":"Sa {0} (na) minuto"},
      "HOUR": const {"1":"Sa 1 oras","0":"Sa 0 oras","other":"Sa {0} (na) oras"},
      "DAY": const {"1":"Sa 1 araw","0":"Sa 0 na araw","other":"Sa {0} (na) araw"},
      "WEEK": const {"1":"Sa 1 linggo","0":"Sa 0 linggo","other":"Sa {0} (na) linggo"},
      "MONTH": const {"1":"Sa 1 buwan","0":"Sa 0 na buwan","other":"Sa {0} (na) buwan"},
      "YEAR": const {"1":"Sa 1 taon","0":"Sa 0 na taon","other":"Sa {0} (na) taon"}
    });
