/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_fr_CA;

import '../symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "second": const {"one":"{0} seconde","other":"{0} secondes"},
      "minute": const {"one":"{0} minute","other":"{0} minutes"},
      "hour": const {"one":"{0} heure","other":"{0} heures"},
      "day": const {"one":"{0} jour","other":"{0} jours"},
      "week": const {"one":"{0} semaine","other":"{0} semaines"},
      "month": const {"one":"{0} mois","other":"{0} mois"},
      "year": const {"one":"{0} année","other":"{0} années"}
    },
      shortUnits: const {
      "second": const {"one":"{0} s","other":"{0} s"},
      "minute": const {"one":"{0} mn","other":"{0} mn"},
      "hour": const {"one":"{0} h","other":"{0} h"},
      "day": const {"one":"{0} j","other":"{0} j"},
      "week": const {"one":"{0} sem.","other":"{0} sem."},
      "month": const {"one":"{0} mois","other":"{0} mois"},
      "year": const {"one":"{0} an","other":"{0} ans"}
    },
      pastUnits: const {
      "second": const {"1":"il y a 1 seconde","one":"Il y a {0} seconde","0":"il y a 0 seconde","other":"Il y a {0} secondes"},
      "minute": const {"1":"il y a 1 minute","one":"Il y a {0} minute","0":"il y a 0 minute","other":"Il y a {0} minutes"},
      "hour": const {"1":"il y a 1 heure","one":"Il y a {0} heure","0":"il y a 0 heure","other":"Il y a {0} heures"},
      "day": const {"1":"il y a 1 jour","one":"Il y a {0} jour","0":"il y a 0 jour","other":"Il y a {0} jours"},
      "week": const {"1":"il y a 1 semaine","one":"Il y a {0} semaine","0":"il y a 0 semaine","other":"Il y a {0} semaines"},
      "month": const {"1":"il y a 1 mois","one":"Il y a {0} mois","0":"il y a 0 mois","other":"Il y a {0} mois"},
      "year": const {"1":"il y a 1 an","one":"Il y a {0} an","0":"il y a 0 an","other":"Il y a {0} ans"}
    },
      futureUnits: const {
      "second": const {"1":"Dans 1 seconde","one":"Dans {0} seconde","0":"Dans 0 seconde","other":"Dans {0} secondes"},
      "minute": const {"1":"dans 1 minute","one":"Dans {0} minute","0":"dans 0 minute","other":"Dans {0} minutes"},
      "hour": const {"1":"dans 1 heure","one":"Dans {0} heure","0":"dans 0 heure","other":"Dans {0} heures"},
      "day": const {"1":"dans 1 jour","one":"Dans {0} jour","0":"dans 0 jour","other":"Dans {0} jours"},
      "week": const {"1":"dans 1 semaine","one":"Dans {0} semaine","0":"dans 0 semaine","other":"Dans {0} semaines"},
      "month": const {"1":"dans 1 mois","one":"Dans {0} mois","0":"dans 0 mois","other":"Dans {0} mois"},
      "year": const {"1":"dans 1 an","one":"Dans {0} an","0":"dans 0 an","other":"Dans {0} ans"}
    });
