// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"/// 
/// Before checkin, this file could have been manually edited. This is
/// to incorporate changes before we could correct CLDR. All manual
/// modification must be documented in this section, and should be
/// removed after those changes land to CLDR.

library relative_time_symbols_gl;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"{0} segundo","other":"{0} segundos"},
      "MINUTE": {"one":"{0} minuto","other":"{0} minutos"},
      "HOUR": {"one":"{0} hora","other":"{0} horas"},
      "DAY": {"one":"{0} dÃ­a","other":"{0} dÃ­as"},
      "WEEK": {"one":"{0} semana","other":"{0} semanas"},
      "MONTH": {"one":"{0} mes","other":"{0} meses"},
      "YEAR": {"one":"{0} ano","other":"{0} anos"}
    },
      shortUnits: {
      "SECOND": {"1":"1 S","0":"0 S","other":"{0} secs"},
      "MINUTE": {"1":"1 min","0":"0 min","other":"{0} mins"},
      "HOUR": {"1":"1 H","0":"0 H","other":"{0} hrs"},
      "DAY": {"1":"1 dÃ­a","0":"0 dÃ­as","other":"{0} days"},
      "WEEK": {"1":"1 semana","0":"0 semanas","other":"{0} wks"},
      "MONTH": {"1":"1 mes","0":"0 meses","other":"{0} mths"},
      "YEAR": {"1":"1 ano","0":"0 anos","other":"{0} yrs"}
    },
      pastUnits: {
      "SECOND": {"1":"Hai 1 segundo","0":"Hai 0 segundos","other":"{0} seconds ago"},
      "MINUTE": {"1":"Hai 1 minuto","0":"Hai 0 minutos","other":"{0} minutes ago"},
      "HOUR": {"1":"Hai 1 hora","0":"Hai 0 horas","other":"{0} hours ago"},
      "DAY": {"1":"Hai 1 dÃ­a","0":"Hai 0 dÃ­as","other":"{0} days ago"},
      "WEEK": {"1":"Hai 1 semana","0":"Hai 0 semanas","other":"{0} weeks ago"},
      "MONTH": {"1":"Hai 1 mes","0":"Hai 0 meses","other":"{0} months ago"},
      "YEAR": {"1":"Hai 1 ano","0":"Hai 0 anos","other":"{0} years ago"}
    },
      futureUnits: {
      "SECOND": {"1":"En 1 segundo","0":"En 0 segundos","other":"In {0} seconds"},
      "MINUTE": {"1":"En 1 minuto","0":"En 0 minutos","other":"In {0} minutes"},
      "HOUR": {"1":"En 1 hora","0":"En 0 horas","other":"In {0} hours"},
      "DAY": {"1":"En 1 dÃ­a","0":"En 0 dÃ­as","other":"In {0} days"},
      "WEEK": {"1":"En 1 semana","0":"En 0 semanas","other":"In {0} weeks"},
      "MONTH": {"1":"En 1 mes","0":"En 0 meses","other":"In {0} months"},
      "YEAR": {"1":"En 1 ano","0":"En 0 anos","other":"In {0} years"}
    });
