/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/relative_time/code_build.dart"

library relative_time_symbols_gl;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "SECOND": const {"one":"{0} segundo","other":"{0} segundos"},
      "MINUTE": const {"one":"{0} minuto","other":"{0} minutos"},
      "HOUR": const {"one":"{0} hora","other":"{0} horas"},
      "DAY": const {"one":"{0} dÃ­a","other":"{0} dÃ­as"},
      "WEEK": const {"one":"{0} semana","other":"{0} semanas"},
      "MONTH": const {"one":"{0} mes","other":"{0} meses"},
      "YEAR": const {"one":"{0} ano","other":"{0} anos"}
    },
      shortUnits: const {
      "SECOND": const {"1":"1 S","0":"0 S","other":"{0} secs"},
      "MINUTE": const {"1":"1 min","0":"0 min","other":"{0} mins"},
      "HOUR": const {"1":"1 H","0":"0 H","other":"{0} hrs"},
      "DAY": const {"1":"1 dÃ­a","0":"0 dÃ­as","other":"{0} days"},
      "WEEK": const {"1":"1 semana","0":"0 semanas","other":"{0} wks"},
      "MONTH": const {"1":"1 mes","0":"0 meses","other":"{0} mths"},
      "YEAR": const {"1":"1 ano","0":"0 anos","other":"{0} yrs"}
    },
      pastUnits: const {
      "SECOND": const {"1":"Hai 1 segundo","0":"Hai 0 segundos","other":"{0} seconds ago"},
      "MINUTE": const {"1":"Hai 1 minuto","0":"Hai 0 minutos","other":"{0} minutes ago"},
      "HOUR": const {"1":"Hai 1 hora","0":"Hai 0 horas","other":"{0} hours ago"},
      "DAY": const {"1":"Hai 1 dÃ­a","0":"Hai 0 dÃ­as","other":"{0} days ago"},
      "WEEK": const {"1":"Hai 1 semana","0":"Hai 0 semanas","other":"{0} weeks ago"},
      "MONTH": const {"1":"Hai 1 mes","0":"Hai 0 meses","other":"{0} months ago"},
      "YEAR": const {"1":"Hai 1 ano","0":"Hai 0 anos","other":"{0} years ago"}
    },
      futureUnits: const {
      "SECOND": const {"1":"En 1 segundo","0":"En 0 segundos","other":"In {0} seconds"},
      "MINUTE": const {"1":"En 1 minuto","0":"En 0 minutos","other":"In {0} minutes"},
      "HOUR": const {"1":"En 1 hora","0":"En 0 horas","other":"In {0} hours"},
      "DAY": const {"1":"En 1 dÃ­a","0":"En 0 dÃ­as","other":"In {0} days"},
      "WEEK": const {"1":"En 1 semana","0":"En 0 semanas","other":"In {0} weeks"},
      "MONTH": const {"1":"En 1 mes","0":"En 0 meses","other":"In {0} months"},
      "YEAR": const {"1":"En 1 ano","0":"En 0 anos","other":"In {0} years"}
    });
