// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"/// 
/// Before checkin, this file could have been manually edited. This is
/// to incorporate changes before we could correct CLDR. All manual
/// modification must be documented in this section, and should be
/// removed after those changes land to CLDR.

library relative_time_symbols_gsw;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"one":"{0} Sekunde","other":"{0} Sekunde"},
      "MINUTE": {"one":"{0} Minuute","other":"{0} Minuute"},
      "HOUR": {"one":"{0} Schtund","other":"{0} Schtunde"},
      "DAY": {"one":"{0} Taag","other":"{0} TÃ¤Ã¤g"},
      "WEEK": {"one":"{0} Wuche","other":"{0} Wuche"},
      "MONTH": {"one":"{0} Monet","other":"{0} MÃ¶net"},
      "YEAR": {"one":"{0} Jahr","other":"{0} Jahr"}
    },
      shortUnits: {
      "SECOND": {},
      "MINUTE": {},
      "HOUR": {},
      "DAY": {},
      "WEEK": {},
      "MONTH": {},
      "YEAR": {}
    },
      pastUnits: {
      "SECOND": {"other":"-{0} s"},
      "MINUTE": {"other":"-{0} min"},
      "HOUR": {"other":"-{0} h"},
      "DAY": {"other":"-{0} d"},
      "WEEK": {"other":"-{0} w"},
      "MONTH": {"other":"-{0} m"},
      "YEAR": {"other":"-{0} y"}
    },
      futureUnits: {
      "SECOND": {"other":"+{0} s"},
      "MINUTE": {"other":"+{0} min"},
      "HOUR": {"other":"+{0} h"},
      "DAY": {"other":"+{0} d"},
      "WEEK": {"other":"+{0} w"},
      "MONTH": {"other":"+{0} m"},
      "YEAR": {"other":"+{0} y"}
    });
