/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_gsw;

import '../symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "second": const {"one":"{0} Sekunde","other":"{0} Sekunde"},
      "minute": const {"one":"{0} Minuute","other":"{0} Minuute"},
      "hour": const {"one":"{0} Schtund","other":"{0} Schtunde"},
      "day": const {"one":"{0} Taag","other":"{0} Tääg"},
      "week": const {"one":"{0} Wuche","other":"{0} Wuche"},
      "month": const {"one":"{0} Monet","other":"{0} Mönet"},
      "year": const {"one":"{0} Jahr","other":"{0} Jahr"}
    },
      shortUnits: const {
      "second": const {},
      "minute": const {},
      "hour": const {},
      "day": const {},
      "week": const {},
      "month": const {},
      "year": const {}
    },
      pastUnits: const {
      "second": const {"other":"-{0} s"},
      "minute": const {"other":"-{0} min"},
      "hour": const {"other":"-{0} h"},
      "day": const {"other":"-{0} d"},
      "week": const {"other":"-{0} w"},
      "month": const {"other":"-{0} m"},
      "year": const {"other":"-{0} y"}
    },
      futureUnits: const {
      "second": const {"other":"+{0} s"},
      "minute": const {"other":"+{0} min"},
      "hour": const {"other":"+{0} h"},
      "day": const {"other":"+{0} d"},
      "week": const {"other":"+{0} w"},
      "month": const {"other":"+{0} m"},
      "year": const {"other":"+{0} y"}
    });
