/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_hi;

import '../symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "second": const {"one":"{0} सेकंड","other":"{0} सेकंड"},
      "minute": const {"one":"{0} मिनट","other":"{0} मिनट"},
      "hour": const {"one":"{0} घंटा","other":"{0} घंटे"},
      "day": const {"one":"{0} दिन","other":"{0} दिन"},
      "week": const {"one":"{0} सप्ताह","other":"{0} सप्ताह"},
      "month": const {"one":"{0} महीना","other":"{0} महीने"},
      "year": const {"one":"{0} साल","other":"{0} साल"}
    },
      shortUnits: const {
      "second": const {"one":"{0} सेकं.","other":"{0} सेकं."},
      "minute": const {"one":"{0} मिन.","other":"{0} मिन."},
      "hour": const {"one":"{0} घं.","other":"{0} घंटे"},
      "day": const {"one":"{0} दि.","other":"{0} दि."},
      "week": const {"one":"{0} सप्त.","other":"{0} सप्त."},
      "month": const {"one":"{0} मही.","other":"{0} मही."},
      "year": const {"one":"{0} साल","other":"{0} साल"}
    },
      pastUnits: const {
      "second": const {"1":"1 सेकंड पहले","0":"0 सेकंड पहले","other":"{0} सेकंड पहले"},
      "minute": const {"1":"1 मिनट पहले","0":"0 मिनट पहले","other":"{0} मिनट पहले"},
      "hour": const {"1":"1 घंटे पहले","0":"0 घंटे पहले","other":"{0} घंटे पहले"},
      "day": const {"1":"1 दिन पहले","0":"0 दिन पहले","other":"{0} दिन पहले"},
      "week": const {"1":"1 सप्ताह पहले","0":"0 सप्ताह पहले","other":"{0} सप्ताह पहले"},
      "month": const {"1":"1 माह पहले","0":"0 माह पहले","other":"{0} माह पहले"},
      "year": const {"1":"1 वर्ष पहले","0":"0 वर्ष पहले","other":"{0} वर्ष पहले"}
    },
      futureUnits: const {
      "second": const {"1":"1 सेकंड में","0":"0 सेकंड में","other":"{0} सेकंड में"},
      "minute": const {"1":"1 मिनट में","0":"0 मिनट में","other":"{0} मिनट में"},
      "hour": const {"1":"1 घंटे में","0":"0 घंटे में","other":"{0} घंटों में"},
      "day": const {"1":"1 दिन में","0":"0 दिन में","other":"{0} दिनों में"},
      "week": const {"1":"1 सप्ताह में","0":"0 सेकंड में","other":"{0} सप्ताह में"},
      "month": const {"1":"1 माह में","0":"0 माह में","other":"{0} माह में"},
      "year": const {"1":"1 वर्ष में","0":"0 वर्ष में","other":"{0} वर्ष में"}
    });
