/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_symbols_hu;

import '../symbols.dart';

const RelativeTimeSymbols locale = const RelativeTimeSymbols(
  name: "hu",
  units: const {
    "second": const {"other":"{0} másodperc"},
    "minute": const {"other":"{0} perc"},
    "hour": const {"other":"{0} óra"},
    "day": const {"other":"{0} nap"},
    "week": const {"other":"{0} hét"},
    "month": const {"other":"{0} hónap"},
    "year": const {"other":"{0} év"}
  },
  shortUnits: const {
    "second": const {"other":"{0} mp"},
    "minute": const {"other":"{0} p"},
    "hour": const {"other":"{0} ó"},
    "day": const {"other":"{0} nap"},
    "week": const {"other":"{0} hét"},
    "month": const {"other":"{0} hónap"},
    "year": const {"other":"{0} év"}
  },
  pastUnits: const {
    "second": const {"1":"1 másodperce","0":"0 másodperce","other":"{0} másodperccel ezelőtt"},
    "minute": const {"1":"1 perce","0":"0 perce","other":"{0} perccel ezelőtt"},
    "hour": const {"1":"1 órája","0":"0 órája","other":"{0} órával ezelőtt"},
    "day": const {"1":"1 napja","0":"0 napja","other":"{0} nappal ezelőtt"},
    "week": const {"1":"1 hete","0":"0 hete","other":"{0} héttel ezelőtt"},
    "month": const {"1":"1 hónapja","0":"0 hónapja","other":"{0} hónappal ezelőtt"},
    "year": const {"1":"1 éve","0":"0 éve","other":"{0} évvel ezelőtt"}
  },
  futureUnits: const {
    "second": const {"1":"1 másodperc múlva","0":"0 másodperc múlva","other":"{0} másodperc múlva"},
    "minute": const {"1":"1 perc múlva","0":"0 perc múlva","other":"{0} perc múlva"},
    "hour": const {"1":"1 óra múlva","0":"0 óra múlva","other":"{0} óra múlva"},
    "day": const {"1":"1 nap múlva","0":"0 nap múlva","other":"{0} nap múlva"},
    "week": const {"1":"1 hét múlva","0":"0 hét múlva","other":"{0} hét múlva"},
    "month": const {"1":"1 hónap múlva","0":"0 hónap múlva","other":"{0} hónap múlva"},
    "year": const {"1":"1 év múlva","0":"0 év múlva","other":"{0} év múlva"}
  });
