/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_id;

import 'package:intlx/src/relative_time/symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "SECOND": const {"other":"{0} detik"},
      "MINUTE": const {"other":"{0} menit"},
      "HOUR": const {"other":"{0} jam"},
      "DAY": const {"other":"{0} hari"},
      "WEEK": const {"other":"{0} minggu"},
      "MONTH": const {"other":"{0} bulan"},
      "YEAR": const {"other":"{0} tahun"}
    },
      shortUnits: const {
      "SECOND": const {"other":"{0} dtk"},
      "MINUTE": const {"other":"{0} mnt"},
      "HOUR": const {"other":"{0} jam"},
      "DAY": const {"other":"{0} hr"},
      "WEEK": const {"other":"{0} mggu"},
      "MONTH": const {"other":"{0} bln"},
      "YEAR": const {"other":"{0} thn"}
    },
      pastUnits: const {
      "SECOND": const {"1":"1 detik yang lalu","0":"0 detik yang lalu","other":"{0} detik yang lalu"},
      "MINUTE": const {"1":"1 menit yang lalu","0":"0 menit yang lalu","other":"{0} menit yang lalu"},
      "HOUR": const {"1":"1 jam yang lalu","0":"0 jam yang lalu","other":"{0} jam yang lalu"},
      "DAY": const {"1":"1 hari yang lalu","0":"0 hari yang lalu","other":"{0} hari yang lalu"},
      "WEEK": const {"1":"1 minggu yang lalu","0":"0 minggu yang lalu","other":"{0} minggu yang lalu"},
      "MONTH": const {"1":"1 bulan yang lalu","0":"0 bulan yang lalu","other":"{0} bulan yang lalu"},
      "YEAR": const {"1":"1 tahun yang lalu","0":"0 tahun yang lalu","other":"{0} tahun yang lalu"}
    },
      futureUnits: const {
      "SECOND": const {"1":"Dalam 1 detik","0":"Dalam 0 detik","other":"Dalam {0} detik"},
      "MINUTE": const {"1":"Dalam 1 menit","0":"Dalam 0 menit","other":"Dalam {0} menit"},
      "HOUR": const {"1":"Dalam 1 jam","0":"Dalam 0 jam","other":"Dalam {0} jam"},
      "DAY": const {"1":"Dalam 1 hari","0":"Dalam 0 hari","other":"Dalam {0} hari"},
      "WEEK": const {"1":"Dalam 1 minggu","0":"Dalam 0 minggu","other":"Dalam {0} minggu"},
      "MONTH": const {"1":"Dalam 1 bulan","0":"Dalam 0 bulan","other":"Dalam {0} bulan"},
      "YEAR": const {"1":"Dalam 1 tahun","0":"Dalam 0 tahun","other":"Dalam {0} tahun"}
    });
