/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_it;

import '../symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "second": const {"one":"{0} secondo","other":"{0} secondi"},
      "minute": const {"one":"{0} minuto","other":"{0} minuti"},
      "hour": const {"one":"{0} ora","other":"{0} ore"},
      "day": const {"one":"{0} giorno","other":"{0} giorni"},
      "week": const {"one":"{0} settimana","other":"{0} settimane"},
      "month": const {"one":"{0} mese","other":"{0} mesi"},
      "year": const {"one":"{0} anno","other":"{0} anni"}
    },
      shortUnits: const {
      "second": const {"one":"{0} sec","other":"{0} sec"},
      "minute": const {"one":"{0} min","other":"{0} min"},
      "hour": const {"one":"{0} h","other":"{0} h"},
      "day": const {"one":"{0} g","other":"{0} gg"},
      "week": const {"one":"{0} sett.","other":"{0} sett."},
      "month": const {"one":"{0} mese","other":"{0} mesi"},
      "year": const {"one":"{0} anno","other":"{0} anni"}
    },
      pastUnits: const {
      "second": const {"one":"{0} secondo fa","0":"0 secondi fa","other":"{0} secondi fa"},
      "minute": const {"one":"{0} minuto fa","0":"0 minuti fa","other":"{0} minuti fa"},
      "hour": const {"one":"{0} ora fa","0":"0 ore fa","other":"{0} ore fa"},
      "day": const {"one":"{0} giorno fa","0":"0 giorni fa","other":"{0} giorni fa"},
      "week": const {"one":"{0} settimana fa","0":"0 settimane fa","other":"{0} settimane fa"},
      "month": const {"one":"{0} mese fa","0":"0 mesi fa","other":"{0} mesi fa"},
      "year": const {"one":"{0} anno fa","0":"0 anni fa","other":"{0} anni fa"}
    },
      futureUnits: const {
      "second": const {"one":"tra {0} secondo","0":"tra 0 secondi","other":"tra {0} secondi"},
      "minute": const {"one":"tra {0} minuto","0":"tra 0 minuti","other":"tra {0} minuti"},
      "hour": const {"one":"tra {0} ora","0":"tra 0 ore","other":"tra {0} ore"},
      "day": const {"one":"tra {0} giorno","0":"tra 0 giorni","other":"tra {0} giorni"},
      "week": const {"one":"tra {0} settimana","0":"tra 0 settimane","other":"tra {0} settimane"},
      "month": const {"one":"tra {0} mese","0":"tra 0 mesi","other":"tra {0} mesi"},
      "year": const {"one":"tra {0} anno","0":"tra 0 anni","other":"tra {0} anni"}
    });
