/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_symbols_iw;

import '../symbols.dart';

const RelativeTimeSymbols locale = const RelativeTimeSymbols(
  name: "iw",
  units: const {
    "second": const {"one":"{0} שניה","other":"{0} שניות"},
    "minute": const {"one":"{0} דקה","other":"{0} דקות"},
    "hour": const {"one":"{0} שעה","other":"{0} שעות"},
    "day": const {"one":"{0} יום","other":"{0} ימים"},
    "week": const {"one":"{0} שבוע","other":"{0} שבועות"},
    "month": const {"one":"{0} חודש","other":"{0} חודשים"},
    "year": const {"one":"{0} שנה","other":"{0} שנים"}
  },
  shortUnits: const {
    "second": const {"one":"{0} שנ׳","other":"{0} שנ׳"},
    "minute": const {"one":"{0} דק׳","other":"{0} דק׳"},
    "hour": const {"one":"{0} שעה","other":"{0} שעות"},
    "day": const {"one":"{0} יום","other":"{0} ימים"},
    "week": const {"one":"{0} שבוע","other":"{0} שבועות"},
    "month": const {"one":"{0} חודש","other":"{0} חודשים"},
    "year": const {"one":"{0} שנה","other":"{0} שנים"}
  },
  pastUnits: const {},
  futureUnits: const {});
