/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/relative_time/code_build.dart"

library relative_time_symbols_ja;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "SECOND": const {"other":"{0}ç§"},
      "MINUTE": const {"other":"{0}å"},
      "HOUR": const {"other":"{0}æé"},
      "DAY": const {"other":"{0}æ¥"},
      "WEEK": const {"other":"{0}é±"},
      "MONTH": const {"other":"{0}ãæ"},
      "YEAR": const {"other":"{0}å¹´"}
    },
      shortUnits: const {
      "SECOND": const {"other":"{0}ç§"},
      "MINUTE": const {"other":"{0}å"},
      "HOUR": const {"other":"{0}æé"},
      "DAY": const {"other":"{0}æ¥"},
      "WEEK": const {"other":"{0}é±"},
      "MONTH": const {"other":"{0}ãæ"},
      "YEAR": const {"other":"{0}å¹´"}
    },
      pastUnits: const {
      "SECOND": const {"1":"1 ç§å","0":"0 ç§å","other":"{0}ç§å"},
      "MINUTE": const {"1":"1 åå","0":"0 åå","other":"{0}åå"},
      "HOUR": const {"1":"1 æéå","0":"0 æéå","other":"{0}æéå"},
      "DAY": const {"1":"1 æ¥å","0":"0 æ¥å","other":"{0}æ¥å"},
      "WEEK": const {"1":"1 é±éå","0":"0 é±éå","other":"{0}é±å"},
      "MONTH": const {"1":"1 ãæå","0":"0 ãæå","other":"{0}ãæå"},
      "YEAR": const {"1":"1 å¹´å","0":"0 å¹´å","other":"{0}å¹´å"}
    },
      futureUnits: const {
      "SECOND": const {"1":"1 ç§å¾","0":"0 ç§å¾","other":"{0} ç§å¾"},
      "MINUTE": const {"1":"1 åå¾","0":"0 åå¾","other":"{0} åå¾"},
      "HOUR": const {"1":"1 æéå¾","0":"0 æéå¾","other":"{0} æéå¾"},
      "DAY": const {"1":"1 æ¥å¾","0":"0 æ¥å¾","other":"{0} æ¥å¾"},
      "WEEK": const {"1":"1 é±éå¾","0":"0 é±éå¾","other":"{0} é±éå¾"},
      "MONTH": const {"1":"1 ãæå¾","0":"0 ãæå¾","other":"{0} ãæå¾"},
      "YEAR": const {"1":"1 å¹´å¾","0":"0 å¹´å¾","other":"{0} å¹´å¾"}
    });
