/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_symbols_ko;

import '../symbols.dart';

const RelativeTimeSymbols locale = const RelativeTimeSymbols(
  name: "ko",
  units: const {
    "second": const {"other":"{0}초"},
    "minute": const {"other":"{0}분"},
    "hour": const {"other":"{0}시간"},
    "day": const {"other":"{0}일"},
    "week": const {"other":"{0}주"},
    "month": const {"other":"{0}개월"},
    "year": const {"other":"{0}년"}
  },
  shortUnits: const {
    "second": const {"other":"{0}초"},
    "minute": const {"other":"{0}분"},
    "hour": const {"other":"{0}시간"},
    "day": const {"other":"{0}일"},
    "week": const {"other":"{0}주"},
    "month": const {"other":"{0}개월"},
    "year": const {"other":"{0}년"}
  },
  pastUnits: const {
    "second": const {"1":"1초 전","0":"0초 전","other":"{0}초 전"},
    "minute": const {"1":"1분 전","0":"0분 전","other":"{0}분 전"},
    "hour": const {"1":"1시간 전","0":"0시간 전","other":"{0}시간 전"},
    "day": const {"1":"1일 전","0":"0일 전","other":"{0}일 전"},
    "week": const {"1":"1주 전","0":"0주 전","other":"{0}주 전"},
    "month": const {"1":"1개월 전","0":"0개월 전","other":"{0}개월 전"},
    "year": const {"1":"1년 전","0":"0년 전","other":"{0}년 전"}
  },
  futureUnits: const {
    "second": const {"1":"1초 후","0":"0초 후","other":"{0}초 후"},
    "minute": const {"1":"1분 후","0":"0분 후","other":"{0}분 후"},
    "hour": const {"1":"1시간 후","0":"0시간 후","other":"{0}시간 후"},
    "day": const {"1":"1일 후","0":"0일 후","other":"{0}일 후"},
    "week": const {"1":"1주 후","0":"0주 후","other":"{0}주 후"},
    "month": const {"1":"1개월 후","0":"0개월 후","other":"{0}개월 후"},
    "year": const {"1":"1년 후","0":"0년 후","other":"{0}년 후"}
  });
