/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"/// 
/// Before checkin, this file could have been manually edited. This is
/// to incorporate changes before we could correct CLDR. All manual
/// modification must be documented in this section, and should be
/// removed after those changes land to CLDR.

library relative_time_symbols_lv;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "SECOND": const {"one":"{0} sekunde","other":"{0} sekundes","zero":"{0} sekundes"},
      "MINUTE": const {"one":"{0} minÅ«te","other":"{0} minÅ«tes","zero":"{0} minÅ«tes"},
      "HOUR": const {"one":"{0} stunda","other":"{0} stundas","zero":"{0} stundas"},
      "DAY": const {"one":"{0} diennakts","other":"{0} diennaktis","zero":"{0} diennaktis"},
      "WEEK": const {"one":"{0} nedÄÄ¼a","other":"{0} nedÄÄ¼as","zero":"{0} nedÄÄ¼as"},
      "MONTH": const {"one":"{0} mÄnesis","other":"{0} mÄneÅ¡i","zero":"{0} mÄneÅ¡i"},
      "YEAR": const {"one":"{0} gads","other":"{0} gadi","zero":"{0} gadi"}
    },
      shortUnits: const {
      "SECOND": const {"one":"{0} s","other":"{0} s","zero":"{0} s"},
      "MINUTE": const {"one":"{0} min","other":"{0} min","zero":"{0} min"},
      "HOUR": const {"one":"{0} h","other":"{0} h","zero":"{0} h"},
      "DAY": const {"one":"{0} diena","other":"{0} dienas","zero":"{0} dienas"},
      "WEEK": const {"one":"{0} ned.","other":"{0} ned.","zero":"{0} ned."},
      "MONTH": const {"one":"{0} mÄn.","other":"{0} mÄn.","zero":"{0} mÄn."},
      "YEAR": const {"one":"{0} g.","other":"{0} g.","zero":"{0} g."}
    },
      pastUnits: const {
      "SECOND": const {"1":"Pirms 1Â sekundes","one":"Pirms {0} sekundes","0":"Pirms 0Â sekundÄm","other":"Pirms {0} sekundÄm","zero":"Pirms {0} sekundÄm"},
      "MINUTE": const {"1":"Pirms 1Â minÅ«tes","one":"Pirms {0} minÅ«tes","0":"Pirms 0Â minÅ«tÄm","other":"Pirms {0} minÅ«tÄm","zero":"Pirms {0} minÅ«tÄm"},
      "HOUR": const {"1":"Pirms 1Â stundas","one":"Pirms {0} stundas","0":"Pirms 0Â stundÄm","other":"Pirms {0} stundÄm","zero":"Pirms {0} stundÄm"},
      "DAY": const {"1":"Pirms 1Â dienas","one":"Pirms {0} dienas","0":"Pirms 0Â dienÄm","other":"Pirms {0} dienÄm","zero":"Pirms {0} dienÄm"},
      "WEEK": const {"1":"Pirms 1Â nedÄÄ¼as","one":"Pirms {0} nedÄÄ¼as","0":"Pirms 0Â nedÄÄ¼Äm","other":"Pirms {0} nedÄÄ¼Äm","zero":"Pirms {0} nedÄÄ¼Äm"},
      "MONTH": const {"1":"Pirms 1Â mÄneÅ¡a","one":"Pirms {0} mÄneÅ¡a","0":"Pirms 0Â mÄneÅ¡iem","other":"Pirms {0} mÄneÅ¡iem","zero":"Pirms {0} mÄneÅ¡iem"},
      "YEAR": const {"1":"Pirms 1Â gada","one":"Pirms {0} gada","0":"Pirms 0Â gadiem","other":"Pirms {0} gadiem","zero":"Pirms {0} gadiem"}
    },
      futureUnits: const {
      "SECOND": const {"1":"PÄc 1Â sekundes","one":"PÄc {0} sekundes","0":"PÄc 0Â sekundÄm","other":"PÄc {0} sekundÄm","zero":"PÄc {0} sekundÄm"},
      "MINUTE": const {"1":"PÄc 1Â minÅ«tes","one":"PÄc {0} minÅ«tes","0":"PÄc 0Â minÅ«tÄm","other":"PÄc {0} minÅ«tÄm","zero":"PÄc {0} minÅ«tÄm"},
      "HOUR": const {"1":"PÄc 1Â stundas","one":"PÄc {0} stundas","0":"PÄc 0Â stundÄm","other":"PÄc {0} stundÄm","zero":"PÄc {0} stundÄm"},
      "DAY": const {"1":"PÄc 1Â dienas","one":"PÄc {0} dienas","0":"PÄc 0Â dienÄm","other":"PÄc {0} dienÄm","zero":"PÄc {0} dienÄm"},
      "WEEK": const {"1":"PÄc 1Â nedÄÄ¼as","one":"PÄc {0} nedÄÄ¼as","0":"PÄc 0Â nedÄÄ¼Äm","other":"PÄc {0} nedÄÄ¼Äm","zero":"PÄc {0} nedÄÄ¼Äm"},
      "MONTH": const {"1":"PÄc 1Â mÄneÅ¡a","one":"PÄc {0} mÄneÅ¡a","0":"PÄc 0Â mÄneÅ¡iem","other":"PÄc {0} mÄneÅ¡iem","zero":"PÄc {0} mÄneÅ¡iem"},
      "YEAR": const {"1":"PÄc 1Â gada","one":"PÄc {0} gada","0":"PÄc 0Â gadiem","other":"PÄc {0} gadiem","zero":"PÄc {0} gadiem"}
    });
