/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_ms;

import 'package:intlx/src/relative_time/symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "SECOND": const {"1":"1 saat","0":"0 saat","other":"{0} saat"},
      "MINUTE": const {"1":"1 minit","0":"0 minit","other":"{0} minit"},
      "HOUR": const {"1":"1 jam","0":"0 jam","other":"{0} jam"},
      "DAY": const {"1":"1 hari","0":"0 hari","other":"{0} hari"},
      "WEEK": const {"1":"1 minggu","0":"0 minggu","other":"{0} minggu"},
      "MONTH": const {"1":"1 bulan","0":"0 bulan","other":"{0} bulan"},
      "YEAR": const {"1":"1 tahun","0":"0 tahun","other":"{0} tahun"}
    },
      shortUnits: const {
      "SECOND": const {"1":"1 saat","0":"0 saat","other":"{0} saat"},
      "MINUTE": const {"1":"1 min","0":"0 min","other":"{0} min"},
      "HOUR": const {"1":"1 jam","0":"0 jam","other":"{0} jam"},
      "DAY": const {"1":"1 hari","0":"0 hari","other":"{0} hari"},
      "WEEK": const {"1":"1 minggu","0":"0 minggu","other":"{0} minggu"},
      "MONTH": const {"1":"1 bulan","0":"0 bulan","other":"{0} bulan"},
      "YEAR": const {"1":"1 thn","0":"0 thn","other":"{0} thn"}
    },
      pastUnits: const {
      "SECOND": const {"1":"1 saat lalu","0":"0 saat lalu","other":"{0} saat lalu"},
      "MINUTE": const {"1":"1 minit lalu","0":"0 minit lalu","other":"{0} minit lalu"},
      "HOUR": const {"1":"1 jam lalu","0":"0 jam lalu","other":"{0} jam lalu"},
      "DAY": const {"1":"1 hari lalu","0":"0 hari lalu","other":"{0} hari lalu"},
      "WEEK": const {"1":"1 minggu lalu","0":"0 minggu lalu","other":"{0} minggu lalu"},
      "MONTH": const {"1":"1 bulan lalu","0":"0 bulan lalu","other":"{0} bulan lalu"},
      "YEAR": const {"1":"1 tahun lalu","0":"0 tahun lalu","other":"{0} tahun lalu"}
    },
      futureUnits: const {
      "SECOND": const {"1":"Dalam 1 saat","0":"Dalam 0 saat","other":"Dalam {0} saat"},
      "MINUTE": const {"1":"Dalam 1 minit","0":"Dalam 0 minit","other":"Dalam {0} minit"},
      "HOUR": const {"1":"Dalam 1 jam","0":"Dalam 0 jam","other":"Dalam {0} jam"},
      "DAY": const {"1":"Dalam 1 hari","0":"Dalam 0 hari","other":"Dalam {0} hari"},
      "WEEK": const {"1":"Dalam 1 minggu","0":"Dalam 0 minggu","other":"Dalam {0} minggu"},
      "MONTH": const {"1":"Dalam 1 Bulan","0":"Dalam 0 bulan","other":"Dalam {0} bulan"},
      "YEAR": const {"1":"Dalam 1 tahun","0":"Dalam 0 tahun","other":"Dalam {0} tahun"}
    });
