/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_symbols_sv;

import '../symbols.dart';

const RelativeTimeSymbols locale = const RelativeTimeSymbols(
  name: "sv",
  units: const {
    "second": const {"one":"{0} sekund","other":"{0} sekunder"},
    "minute": const {"one":"{0} minut","other":"{0} minuter"},
    "hour": const {"one":"{0} timme","other":"{0} timmar"},
    "day": const {"one":"{0} dygn","other":"{0} dygn"},
    "week": const {"one":"{0} vecka","other":"{0} veckor"},
    "month": const {"one":"{0} månad","other":"{0} månader"},
    "year": const {"one":"{0} år","other":"{0} år"}
  },
  shortUnits: const {
    "second": const {"one":"{0} s","other":"{0} s"},
    "minute": const {"one":"{0} min","other":"{0} min"},
    "hour": const {"one":"{0} tim","other":"{0} tim"},
    "day": const {"one":"{0} d","other":"{0} d"},
    "week": const {"one":"{0} v","other":"{0} v"},
    "month": const {"one":"{0} mån","other":"{0} mån"},
    "year": const {"one":"{0} år","other":"{0} år"}
  },
  pastUnits: const {
    "second": const {"1":"för 1 sekund sedan","one":"för {0} sekund sedan","0":"för 0 sekunder sedan","other":"för {0} sekunder sedan"},
    "minute": const {"1":"för 1 minut sedan","one":"för {0} minut sedan","0":"för 0 minuter sedan","other":"för {0} minuter sedan"},
    "hour": const {"1":"för 1 timme sedan","one":"för {0} timme sedan","0":"för 0 timmar sedan","other":"för {0} timmar sedan"},
    "day": const {"1":"för 1 dag sedan","one":"för {0} dygn sedan","0":"för 0 dagar sedan","other":"för {0} dygn sedan"},
    "week": const {"1":"för 1 vecka sedan","one":"för {0} vecka sedan","0":"för 0 veckor sedan","other":"för {0} veckor sedan"},
    "month": const {"1":"för 1 månad sedan","one":"för {0} månad sedan","0":"för 0 månader sedan","other":"för {0} månader sedan"},
    "year": const {"1":"för 1 år sedan","one":"för {0} år sedan","0":"för 0 år sedan","other":"för {0} år sedan"}
  },
  futureUnits: const {
    "second": const {"1":"om 1 sekund","one":"om {0} sekund","0":"om 0 sekunder","other":"om {0} sekunder"},
    "minute": const {"1":"om 1 minut","one":"om {0} minut","0":"om 0 minuter","other":"om {0} minuter"},
    "hour": const {"1":"om 1 timme","one":"om {0} timme","0":"om 0 timmar","other":"om {0} timmar"},
    "day": const {"1":"om 1 dag","one":"om {0} dygn","0":"om 0 dagar","other":"om {0} dygn"},
    "week": const {"1":"om 1 vecka","one":"om {0} vecka","0":"om 0 veckor","other":"om {0} veckor"},
    "month": const {"1":"om 1 månad","one":"om {0} månad","0":"om 0 månader","other":"om {0} månader"},
    "year": const {"1":"om 1 år","one":"om {0} år","0":"om 0 år","other":"om {0} år"}
  });
