/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_sv;

import 'package:intlx/src/relative_time/symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "second": const {"one":"{0} sekund","other":"{0} sekunder"},
      "minute": const {"one":"{0} minut","other":"{0} minuter"},
      "hour": const {"one":"{0} timme","other":"{0} timmar"},
      "day": const {"one":"{0} dygn","other":"{0} dygn"},
      "week": const {"one":"{0} vecka","other":"{0} veckor"},
      "month": const {"one":"{0} mÃ¥nad","other":"{0} mÃ¥nader"},
      "year": const {"one":"{0} Ã¥r","other":"{0} Ã¥r"}
    },
      shortUnits: const {
      "second": const {"one":"{0} s","other":"{0} s"},
      "minute": const {"one":"{0} min","other":"{0} min"},
      "hour": const {"one":"{0} tim","other":"{0} tim"},
      "day": const {"one":"{0} d","other":"{0} d"},
      "week": const {"one":"{0} v","other":"{0} v"},
      "month": const {"one":"{0} mÃ¥n","other":"{0} mÃ¥n"},
      "year": const {"one":"{0} Ã¥r","other":"{0} Ã¥r"}
    },
      pastUnits: const {
      "second": const {"1":"fÃ¶r 1 sekund sedan","one":"fÃ¶r {0} sekund sedan","0":"fÃ¶r 0 sekunder sedan","other":"fÃ¶r {0} sekunder sedan"},
      "minute": const {"1":"fÃ¶r 1 minut sedan","one":"fÃ¶r {0} minut sedan","0":"fÃ¶r 0 minuter sedan","other":"fÃ¶r {0} minuter sedan"},
      "hour": const {"1":"fÃ¶r 1 timme sedan","one":"fÃ¶r {0} timme sedan","0":"fÃ¶r 0 timmar sedan","other":"fÃ¶r {0} timmar sedan"},
      "day": const {"1":"fÃ¶r 1 dag sedan","one":"fÃ¶r {0} dygn sedan","0":"fÃ¶r 0 dagar sedan","other":"fÃ¶r {0} dygn sedan"},
      "week": const {"1":"fÃ¶r 1 vecka sedan","one":"fÃ¶r {0} vecka sedan","0":"fÃ¶r 0 veckor sedan","other":"fÃ¶r {0} veckor sedan"},
      "month": const {"1":"fÃ¶r 1 mÃ¥nad sedan","one":"fÃ¶r {0} mÃ¥nad sedan","0":"fÃ¶r 0 mÃ¥nader sedan","other":"fÃ¶r {0} mÃ¥nader sedan"},
      "year": const {"1":"fÃ¶r 1 Ã¥r sedan","one":"fÃ¶r {0} Ã¥r sedan","0":"fÃ¶r 0 Ã¥r sedan","other":"fÃ¶r {0} Ã¥r sedan"}
    },
      futureUnits: const {
      "second": const {"1":"om 1 sekund","one":"om {0} sekund","0":"om 0 sekunder","other":"om {0} sekunder"},
      "minute": const {"1":"om 1 minut","one":"om {0} minut","0":"om 0 minuter","other":"om {0} minuter"},
      "hour": const {"1":"om 1 timme","one":"om {0} timme","0":"om 0 timmar","other":"om {0} timmar"},
      "day": const {"1":"om 1 dag","one":"om {0} dygn","0":"om 0 dagar","other":"om {0} dygn"},
      "week": const {"1":"om 1 vecka","one":"om {0} vecka","0":"om 0 veckor","other":"om {0} veckor"},
      "month": const {"1":"om 1 mÃ¥nad","one":"om {0} mÃ¥nad","0":"om 0 mÃ¥nader","other":"om {0} mÃ¥nader"},
      "year": const {"1":"om 1 Ã¥r","one":"om {0} Ã¥r","0":"om 0 Ã¥r","other":"om {0} Ã¥r"}
    });
