/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_th;

import '../symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "second": const {"other":"{0} วินาที"},
      "minute": const {"other":"{0} นาที"},
      "hour": const {"other":"{0} ชั่วโมง"},
      "day": const {"other":"{0} วัน"},
      "week": const {"other":"{0} สัปดาห์"},
      "month": const {"other":"{0} เดือน"},
      "year": const {"other":"{0} ปี"}
    },
      shortUnits: const {
      "second": const {"other":"{0} วิ"},
      "minute": const {"other":"{0} นา"},
      "hour": const {"other":"{0} ชั่วโมง"},
      "day": const {"other":"{0} ว"},
      "week": const {"other":"{0} สัปดาห์"},
      "month": const {"other":"{0} ด"},
      "year": const {"other":"{0} ป"}
    },
      pastUnits: const {
      "second": const {"1":"1 วินาทีที่ผ่านมา","0":"0 วินาทีที่ผ่านมา","other":"{0} วินาทีที่ผ่านมา"},
      "minute": const {"1":"1 นาทีที่ผ่านมา","0":"0 นาทีที่ผ่านมา","other":"{0} นาทีที่ผ่านมา"},
      "hour": const {"1":"1 ชั่วโมงที่ผ่านมา","0":"0 ชั่วโมงที่ผ่านมา","other":"{0} ชั่วโมงที่ผ่านมา"},
      "day": const {"1":"1 วันที่ผ่านมา","0":"0 วันที่ผ่านมา","other":"{0} วันที่ผ่านมา"},
      "week": const {"1":"1 สัปดาห์ที่ผ่านมา","0":"0 สัปดาห์ที่ผ่านมา","other":"{0} สัปดาห์ที่ผ่านมา"},
      "month": const {"1":"1 เดือนที่ผ่านมา","0":"0 เดือนที่ผ่านมา","other":"{0} เดือนที่ผ่านมา"},
      "year": const {"1":"1 year ago","0":"0 ปีที่แล้ว","other":"{0} ปีที่แล้ว"}
    },
      futureUnits: const {
      "second": const {"1":"ในอีก 1 วินาที","0":"ในอีก 0 วินาที","other":"ในอีก {0} วินาที"},
      "minute": const {"1":"ในอีก 1 นาที","0":"ในอีก 0 นาที","other":"ในอีก {0} นาที"},
      "hour": const {"1":"ในอีก 1 ชั่วโมง","0":"ในอีก 0 ชั่วโมง","other":"ในอีก {0} ชั่วโมง"},
      "day": const {"1":"ในอีก 1 วัน","0":"ในอีก 0 วัน","other":"ในอีก {0} วัน"},
      "week": const {"1":"ในอีก 1 สัปดาห์","0":"ในอีก 0 สัปดาห์","other":"ในอีก {0} สัปดาห์"},
      "month": const {"1":"ในอีก 1 เดือน","0":"ในอีก 0 เดือน","other":"ในอีก {0} เดือน"},
      "year": const {"1":"ในอีก 1 ปี","0":"ในอีก 0 ปี","other":"ในอีก {0} ปี"}
    });
