/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_tl;

import 'package:intlx/src/relative_time/symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "second": const {"one":"{0} segundo","other":"{0} segundo"},
      "minute": const {"one":"{0} minuto","other":"{0} minuto"},
      "hour": const {"one":"{0} oras","other":"{0} oras"},
      "day": const {"one":"{0} araw","other":"{0} araw"},
      "week": const {"one":"{0} linggo","other":"{0} linggo"},
      "month": const {"one":"{0} buwan","other":"{0} buwan"},
      "year": const {"one":"{0} taon","other":"{0} taon"}
    },
      shortUnits: const {
      "second": const {"one":"{0} seg","other":"{0} seg"},
      "minute": const {"one":"{0} min","other":"{0} min"},
      "hour": const {"one":"{0} or","other":"{0} or"},
      "day": const {"one":"{0} arw","other":"{0} arw"},
      "week": const {"one":"{0} ling","other":"{0} ling"},
      "month": const {"one":"{0} buw","other":"{0} buw"},
      "year": const {"one":"{0} ta","other":"{0} ta"}
    },
    pastUnits: const {},
    futureUnits: const {});
