/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_tr;

import 'package:intlx/src/relative_time/symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "second": const {"other":"{0} saniye"},
      "minute": const {"other":"{0} dakika"},
      "hour": const {"other":"{0} saat"},
      "day": const {"other":"{0} gÃ¼n"},
      "week": const {"other":"{0} hafta"},
      "month": const {"other":"{0} ay"},
      "year": const {"other":"{0} yÄ±l"}
    },
      shortUnits: const {
      "second": const {"other":"{0} sn."},
      "minute": const {"other":"{0} dk."},
      "hour": const {"other":"{0} sa."},
      "day": const {"other":"{0} gÃ¼n"},
      "week": const {"other":"{0} hafta"},
      "month": const {"other":"{0} ay"},
      "year": const {"other":"{0} yÄ±l"}
    },
      pastUnits: const {
      "second": const {"1":"1 saniye Ã¶nce","0":"0 saniye Ã¶nce","other":"{0} saniye Ã¶nce"},
      "minute": const {"1":"1 dakika Ã¶nce","0":"0 dakika Ã¶nce","other":"{0} dakika Ã¶nce"},
      "hour": const {"1":"1 saat Ã¶nce","0":"0 saat Ã¶nce","other":"{0} saat Ã¶nce"},
      "day": const {"1":"1 gÃ¼n Ã¶nce","0":"0 gÃ¼n Ã¶nce","other":"{0} gÃ¼n Ã¶nce"},
      "week": const {"1":"1 hafta Ã¶nce","0":"0 hafta Ã¶nce","other":"{0} hafta Ã¶nce"},
      "month": const {"1":"1 ay Ã¶nce","0":"0 ay Ã¶nce","other":"{0} ay Ã¶nce"},
      "year": const {"1":"1 yÄ±l Ã¶nce","0":"0 yÄ±l Ã¶nce","other":"{0} yÄ±l Ã¶nce"}
    },
      futureUnits: const {
      "second": const {"1":"1 saniye sonra","0":"0 saniye sonra","other":"{0} saniye sonra"},
      "minute": const {"1":"1 dakika sonra","0":"0 dakika sonra","other":"{0} dakika sonra"},
      "hour": const {"1":"1 saat sonra","0":"0 saat sonra","other":"{0} saat sonra"},
      "day": const {"1":"1 gÃ¼n sonra","0":"0 gÃ¼n sonra","other":"{0} gÃ¼n sonra"},
      "week": const {"1":"1 hafta sonra","0":"0 hafta sonra","other":"{0} hafta sonra"},
      "month": const {"1":"1 ay sonra","0":"0 ay sonra","other":"{0} ay sonra"},
      "year": const {"1":"1 yÄ±l sonra","0":"0 yÄ±l sonra","other":"{0} yÄ±l sonra"}
    });
