/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/relative_time/locale_build.dart"

library relative_time_symbols_tr;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "SECOND": const {"other":"{0} saniye"},
      "MINUTE": const {"other":"{0} dakika"},
      "HOUR": const {"other":"{0} saat"},
      "DAY": const {"other":"{0} gÃ¼n"},
      "WEEK": const {"other":"{0} hafta"},
      "MONTH": const {"other":"{0} ay"},
      "YEAR": const {"other":"{0} yÄ±l"}
    },
      shortUnits: const {
      "SECOND": const {"other":"{0} sn."},
      "MINUTE": const {"other":"{0} dk."},
      "HOUR": const {"other":"{0} sa."},
      "DAY": const {"other":"{0} gÃ¼n"},
      "WEEK": const {"other":"{0} hafta"},
      "MONTH": const {"other":"{0} ay"},
      "YEAR": const {"other":"{0} yÄ±l"}
    },
      pastUnits: const {
      "SECOND": const {"1":"1 saniye Ã¶nce","0":"0 saniye Ã¶nce","other":"{0} saniye Ã¶nce"},
      "MINUTE": const {"1":"1 dakika Ã¶nce","0":"0 dakika Ã¶nce","other":"{0} dakika Ã¶nce"},
      "HOUR": const {"1":"1 saat Ã¶nce","0":"0 saat Ã¶nce","other":"{0} saat Ã¶nce"},
      "DAY": const {"1":"1 gÃ¼n Ã¶nce","0":"0 gÃ¼n Ã¶nce","other":"{0} gÃ¼n Ã¶nce"},
      "WEEK": const {"1":"1 hafta Ã¶nce","0":"0 hafta Ã¶nce","other":"{0} hafta Ã¶nce"},
      "MONTH": const {"1":"1 ay Ã¶nce","0":"0 ay Ã¶nce","other":"{0} ay Ã¶nce"},
      "YEAR": const {"1":"1 yÄ±l Ã¶nce","0":"0 yÄ±l Ã¶nce","other":"{0} yÄ±l Ã¶nce"}
    },
      futureUnits: const {
      "SECOND": const {"1":"1 saniye sonra","0":"0 saniye sonra","other":"{0} saniye sonra"},
      "MINUTE": const {"1":"1 dakika sonra","0":"0 dakika sonra","other":"{0} dakika sonra"},
      "HOUR": const {"1":"1 saat sonra","0":"0 saat sonra","other":"{0} saat sonra"},
      "DAY": const {"1":"1 gÃ¼n sonra","0":"0 gÃ¼n sonra","other":"{0} gÃ¼n sonra"},
      "WEEK": const {"1":"1 hafta sonra","0":"0 hafta sonra","other":"{0} hafta sonra"},
      "MONTH": const {"1":"1 ay sonra","0":"0 ay sonra","other":"{0} ay sonra"},
      "YEAR": const {"1":"1 yÄ±l sonra","0":"0 yÄ±l sonra","other":"{0} yÄ±l sonra"}
    });
