// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"/// 
/// Before checkin, this file could have been manually edited. This is
/// to incorporate changes before we could correct CLDR. All manual
/// modification must be documented in this section, and should be
/// removed after those changes land to CLDR.

library relative_time_symbols_ur;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "SECOND": const {"1":"1 Ø³ÛÚ©ÙÚ","0":"0 Ø³ÛÚ©ÙÚ","other":"{0} Ø³ÛÚ©ÙÚ"},
      "MINUTE": const {"1":"1 ÙÙÙ¹","0":"0 ÙÙÙ¹","other":"{0} ÙÙÙ¹"},
      "HOUR": const {"1":"1 Ú¯Ú¾ÙÙ¹Û","0":"0 Ú¯Ú¾ÙÙ¹Û","other":"{0} Ú¯Ú¾ÙÙ¹Û"},
      "DAY": const {"1":"1 Ø¯Ù","0":"0 Ø¯Ù","other":"{0} Ø¯Ù"},
      "WEEK": const {"1":"1 ÛÙØªÛ","0":"0 ÛÙØªÛ","other":"{0} ÛÙØªÛ"},
      "MONTH": const {"1":"1 ÙÛÛÙÛ","0":"0 ÙÛÛÙÛ","other":"{0} ÙÛÛÙÛ"},
      "YEAR": const {"1":"1 Ø³Ø§Ù","0":"0 Ø³Ø§Ù","other":"{0} Ø³Ø§Ù"}
    },
      shortUnits: const {
      "SECOND": const {"1":"1 Ø³ÛÚ©ÙÚ","0":"0 Ø³ÛÚ©ÙÚ","other":"{0} Ø³ÛÚ©ÙÚ"},
      "MINUTE": const {"1":"1 ÙÙÙ¹","0":"0 ÙÙÙ¹","other":"{0} ÙÙÙ¹"},
      "HOUR": const {"1":"1 Ú¯Ú¾ÙÙ¹Û","0":"0 Ú¯Ú¾ÙÙ¹Û","other":"{0} Ú¯Ú¾ÙÙ¹Û"},
      "DAY": const {"1":"1 Ø¯Ù","0":"0 Ø¯Ù","other":"{0} Ø¯Ù"},
      "WEEK": const {"1":"1 ÛÙØªÛ","0":"0 ÛÙØªÛ","other":"{0} ÛÙØªÛ"},
      "MONTH": const {"1":"1 ÙÛÛÙÛ","0":"0 ÙÛÛÙÛ","other":"{0} ÙÛÛÙÛ"},
      "YEAR": const {"1":"1 Ø³Ø§Ù","0":"0 Ø³Ø§Ù","other":"{0} Ø³Ø§Ù"}
    },
      pastUnits: const {
      "SECOND": const {"1":"1 Ø³ÛÚ©ÙÚ Ù¾ÛÙÛ","0":"0 Ø³ÛÚ©ÙÚ Ù¾ÛÙÛ","other":"{0} Ø³ÛÚ©ÙÚ Ù¾ÛÙÛ"},
      "MINUTE": const {"1":"1 ÙÙÙ¹ Ù¾ÛÙÛ","0":"0 ÙÙÙ¹ Ù¾ÛÙÛ","other":"{0} ÙÙÙ¹ Ù¾ÛÙÛ"},
      "HOUR": const {"1":"1 Ú¯Ú¾ÙÙ¹Û Ù¾ÛÙÛ","0":"0 Ú¯Ú¾ÙÙ¹Û Ù¾ÛÙÛ","other":"{0} Ú¯Ú¾ÙÙ¹Û Ù¾ÛÙÛ"},
      "DAY": const {"1":"1 Ø¯Ù Ù¾ÛÙÛ","0":"0 Ø¯Ù Ù¾ÛÙÛ","other":"{0} Ø¯Ù Ù¾ÛÙÛ"},
      "WEEK": const {"1":"1 ÛÙØªÛ Ù¾ÛÙÛ","0":"0 ÛÙØªÛ Ù¾ÛÙÛ","other":"{0} ÛÙØªÛ Ù¾ÛÙÛ"},
      "MONTH": const {"1":"1 ÙÛÛÙÛ Ù¾ÛÙÛ","0":"0 ÙÛÛÙÛ Ù¾ÛÙÛ","other":"{0} ÙÛÛÙÛ Ù¾ÛÙÛ"},
      "YEAR": const {"1":"1 Ø³Ø§Ù Ù¾ÛÙÛ","0":"0 Ø³Ø§Ù Ù¾ÛÙÛ","other":"{0} Ø³Ø§Ù Ù¾ÛÙÛ"}
    },
      futureUnits: const {
      "SECOND": const {"1":"1 Ø³ÛÚ©ÙÚ ÙÛÚº","0":"0 Ø³ÛÚ©ÙÚ ÙÛÚº","other":"{0} Ø³ÛÚ©ÙÚ ÙÛÚº"},
      "MINUTE": const {"1":"1 ÙÙÙ¹ ÙÛÚº","0":"0 ÙÙÙ¹ ÙÛÚº","other":"{0} ÙÙÙ¹ ÙÛÚº"},
      "HOUR": const {"1":"1 Ú¯Ú¾ÙÙ¹Û ÙÛÚº","0":"0 Ú¯Ú¾ÙÙ¹Û ÙÛÚº","other":"{0} Ú¯Ú¾ÙÙ¹Û ÙÛÚº"},
      "DAY": const {"1":"1 Ø¯Ù ÙÛÚº","0":"0 Ø¯Ù ÙÛÚº","other":"{0} Ø¯Ù ÙÛÚº"},
      "WEEK": const {"1":"1 ÛÙØªÛ ÙÛÚº","0":"0 ÛÙØªÛ ÙÛÚº","other":"{0} ÛÙØªÛ ÙÛÚº"},
      "MONTH": const {"1":"1 ÙÛÛÙÛ ÙÛÚº","0":"0 ÙÛÛÙÛ ÙÛÚº","other":"{0} ÙÛÛÙÛ ÙÛÚº"},
      "YEAR": const {"1":"1 Ø³Ø§Ù ÙÛÚº","0":"0 Ø³Ø§Ù ÙÛÚº","other":"{0} Ø³Ø§Ù ÙÛÚº"}
    });
