/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_symbols_zh_CN;

import '../symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "second": const {"other":"{0}秒"},
      "minute": const {"other":"{0}分"},
      "hour": const {"other":"{0}小时"},
      "day": const {"other":"{0}日"},
      "week": const {"other":"{0}周"},
      "month": const {"other":"{0}月"},
      "year": const {"other":"{0}年"}
    },
      shortUnits: const {
      "second": const {"other":"{0}秒"},
      "minute": const {"other":"{0}分"},
      "hour": const {"other":"{0}小时"},
      "day": const {"other":"{0}日"},
      "week": const {"other":"{0}周"},
      "month": const {"other":"{0}月"},
      "year": const {"other":"{0}年"}
    },
    pastUnits: const {},
    futureUnits: const {});
