/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/relative_time/locale_build.dart"

library relative_time_symbols_zh_CN;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: const {
      "SECOND": const {"other":"{0}ç§"},
      "MINUTE": const {"other":"{0}å"},
      "HOUR": const {"other":"{0}å°æ¶"},
      "DAY": const {"other":"{0}æ¥"},
      "WEEK": const {"other":"{0}å¨"},
      "MONTH": const {"other":"{0}æ"},
      "YEAR": const {"other":"{0}å¹´"}
    },
      shortUnits: const {
      "SECOND": const {"other":"{0}ç§"},
      "MINUTE": const {"other":"{0}å"},
      "HOUR": const {"other":"{0}å°æ¶"},
      "DAY": const {"other":"{0}æ¥"},
      "WEEK": const {"other":"{0}å¨"},
      "MONTH": const {"other":"{0}æ"},
      "YEAR": const {"other":"{0}å¹´"}
    },
    pastUnits: const {},
    futureUnits: const {});
