/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_symbols_zh_HK;

import '../symbols.dart';

const RelativeTimeSymbols locale = const RelativeTimeSymbols(
  name: "zh_HK",
  units: const {
    "second": const {"other":"{0}秒"},
    "minute": const {"other":"{0}分"},
    "hour": const {"other":"{0}時"},
    "day": const {"other":"{0}日"},
    "week": const {"other":"{0}星期"},
    "month": const {"other":"{0}月"},
    "year": const {"other":"{0}年"}
  },
  shortUnits: const {
    "second": const {"other":"{0}秒"},
    "minute": const {"other":"{0}分"},
    "hour": const {"other":"{0}小時"},
    "day": const {"other":"{0}日"},
    "week": const {"other":"{0}週"},
    "month": const {"other":"{0}月"},
    "year": const {"other":"{0}年"}
  },
  pastUnits: const {},
  futureUnits: const {});
