// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"/// 
/// Before checkin, this file could have been manually edited. This is
/// to incorporate changes before we could correct CLDR. All manual
/// modification must be documented in this section, and should be
/// removed after those changes land to CLDR.

library relative_time_symbols_zh_HK;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';

final symbols = new RelativeTimeSymbols(      units: {
      "SECOND": {"other":"{0}ç§"},
      "MINUTE": {"other":"{0}å"},
      "HOUR": {"other":"{0}æ"},
      "DAY": {"other":"{0}æ¥"},
      "WEEK": {"other":"{0}ææ"},
      "MONTH": {"other":"{0}æ"},
      "YEAR": {"other":"{0}å¹´"}
    },
      shortUnits: {
      "SECOND": {"other":"{0}ç§"},
      "MINUTE": {"other":"{0}å"},
      "HOUR": {"other":"{0}å°æ"},
      "DAY": {"other":"{0}æ¥"},
      "WEEK": {"other":"{0}é±"},
      "MONTH": {"other":"{0}æ"},
      "YEAR": {"other":"{0}å¹´"}
    },
      pastUnits: {
      
    },
      futureUnits: {
      
    });
