// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/iterable/code_build.dart"

/// Exposes [LocaleData] constants for use with [IterableFormat].
/// For example:
///     import 'package:intlx/iterable_locale_data.dart' as iterable_data;
///     main() {
///       iterable_data.EN.load();
///       iterable_data.DE.load();
///       // do something with [IterableFormat].
///     }
library iterable_locale_data;

import 'package:intlx/intlx.dart';
import 'package:intlx/src/locale_data_impl.dart';
import 'package:intlx/src/iterable/data/af.dart' as symbols_AF;
import 'package:intlx/src/iterable/data/am.dart' as symbols_AM;
import 'package:intlx/src/iterable/data/ar.dart' as symbols_AR;
import 'package:intlx/src/iterable/data/bg.dart' as symbols_BG;
import 'package:intlx/src/iterable/data/bn.dart' as symbols_BN;
import 'package:intlx/src/iterable/data/ca.dart' as symbols_CA;
import 'package:intlx/src/iterable/data/cs.dart' as symbols_CS;
import 'package:intlx/src/iterable/data/da.dart' as symbols_DA;
import 'package:intlx/src/iterable/data/de.dart' as symbols_DE;
import 'package:intlx/src/iterable/data/de_AT.dart' as symbols_DE_AT;
import 'package:intlx/src/iterable/data/de_CH.dart' as symbols_DE_CH;
import 'package:intlx/src/iterable/data/el.dart' as symbols_EL;
import 'package:intlx/src/iterable/data/en.dart' as symbols_EN;
import 'package:intlx/src/iterable/data/en_AU.dart' as symbols_EN_AU;
import 'package:intlx/src/iterable/data/en_GB.dart' as symbols_EN_GB;
import 'package:intlx/src/iterable/data/en_IE.dart' as symbols_EN_IE;
import 'package:intlx/src/iterable/data/en_IN.dart' as symbols_EN_IN;
import 'package:intlx/src/iterable/data/en_SG.dart' as symbols_EN_SG;
import 'package:intlx/src/iterable/data/en_US.dart' as symbols_EN_US;
import 'package:intlx/src/iterable/data/en_ZA.dart' as symbols_EN_ZA;
import 'package:intlx/src/iterable/data/es.dart' as symbols_ES;
import 'package:intlx/src/iterable/data/es_419.dart' as symbols_ES_419;
import 'package:intlx/src/iterable/data/et.dart' as symbols_ET;
import 'package:intlx/src/iterable/data/eu.dart' as symbols_EU;
import 'package:intlx/src/iterable/data/fa.dart' as symbols_FA;
import 'package:intlx/src/iterable/data/fi.dart' as symbols_FI;
import 'package:intlx/src/iterable/data/fil.dart' as symbols_FIL;
import 'package:intlx/src/iterable/data/fr.dart' as symbols_FR;
import 'package:intlx/src/iterable/data/fr_CA.dart' as symbols_FR_CA;
import 'package:intlx/src/iterable/data/gl.dart' as symbols_GL;
import 'package:intlx/src/iterable/data/gsw.dart' as symbols_GSW;
import 'package:intlx/src/iterable/data/gu.dart' as symbols_GU;
import 'package:intlx/src/iterable/data/he.dart' as symbols_HE;
import 'package:intlx/src/iterable/data/hi.dart' as symbols_HI;
import 'package:intlx/src/iterable/data/hr.dart' as symbols_HR;
import 'package:intlx/src/iterable/data/hu.dart' as symbols_HU;
import 'package:intlx/src/iterable/data/id.dart' as symbols_ID;
import 'package:intlx/src/iterable/data/in.dart' as symbols_IN;
import 'package:intlx/src/iterable/data/is.dart' as symbols_IS;
import 'package:intlx/src/iterable/data/it.dart' as symbols_IT;
import 'package:intlx/src/iterable/data/iw.dart' as symbols_IW;
import 'package:intlx/src/iterable/data/ja.dart' as symbols_JA;
import 'package:intlx/src/iterable/data/kn.dart' as symbols_KN;
import 'package:intlx/src/iterable/data/ko.dart' as symbols_KO;
import 'package:intlx/src/iterable/data/ln.dart' as symbols_LN;
import 'package:intlx/src/iterable/data/lt.dart' as symbols_LT;
import 'package:intlx/src/iterable/data/lv.dart' as symbols_LV;
import 'package:intlx/src/iterable/data/ml.dart' as symbols_ML;
import 'package:intlx/src/iterable/data/mr.dart' as symbols_MR;
import 'package:intlx/src/iterable/data/ms.dart' as symbols_MS;
import 'package:intlx/src/iterable/data/mt.dart' as symbols_MT;
import 'package:intlx/src/iterable/data/nl.dart' as symbols_NL;
import 'package:intlx/src/iterable/data/no.dart' as symbols_NO;
import 'package:intlx/src/iterable/data/or.dart' as symbols_OR;
import 'package:intlx/src/iterable/data/pl.dart' as symbols_PL;
import 'package:intlx/src/iterable/data/pt.dart' as symbols_PT;
import 'package:intlx/src/iterable/data/pt_BR.dart' as symbols_PT_BR;
import 'package:intlx/src/iterable/data/pt_PT.dart' as symbols_PT_PT;
import 'package:intlx/src/iterable/data/ro.dart' as symbols_RO;
import 'package:intlx/src/iterable/data/ru.dart' as symbols_RU;
import 'package:intlx/src/iterable/data/sk.dart' as symbols_SK;
import 'package:intlx/src/iterable/data/sl.dart' as symbols_SL;
import 'package:intlx/src/iterable/data/sq.dart' as symbols_SQ;
import 'package:intlx/src/iterable/data/sr.dart' as symbols_SR;
import 'package:intlx/src/iterable/data/sv.dart' as symbols_SV;
import 'package:intlx/src/iterable/data/sw.dart' as symbols_SW;
import 'package:intlx/src/iterable/data/ta.dart' as symbols_TA;
import 'package:intlx/src/iterable/data/te.dart' as symbols_TE;
import 'package:intlx/src/iterable/data/th.dart' as symbols_TH;
import 'package:intlx/src/iterable/data/tl.dart' as symbols_TL;
import 'package:intlx/src/iterable/data/tr.dart' as symbols_TR;
import 'package:intlx/src/iterable/data/uk.dart' as symbols_UK;
import 'package:intlx/src/iterable/data/ur.dart' as symbols_UR;
import 'package:intlx/src/iterable/data/vi.dart' as symbols_VI;
import 'package:intlx/src/iterable/data/zh.dart' as symbols_ZH;
import 'package:intlx/src/iterable/data/zh_CN.dart' as symbols_ZH_CN;
import 'package:intlx/src/iterable/data/zh_HK.dart' as symbols_ZH_HK;
import 'package:intlx/src/iterable/data/zh_TW.dart' as symbols_ZH_TW;
import 'package:intlx/src/iterable/data/zu.dart' as symbols_ZU;

part 'package:intlx/src/iterable/iterable_all_data_constant.dart';
part 'package:intlx/src/iterable/iterable_locale_data_constants.dart';
