// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/plural/code_build.dart"

/// Exposes [LocaleData] constants for use with [PluralFormat].
/// For example:
///     import 'package:intlx/plural_locale_data.dart' as plural_data;
///     main() {
///       plural_data.EN.load();
///       plural_data.DE.load();
///       // do something with [PluralFormat].
///     }
library plural_locale_data;

import 'package:intlx/intlx.dart';
import 'package:intlx/src/locale_data_impl.dart';
import 'package:intlx/src/symbols_map.dart';
import 'package:intlx/src/plural/plural_locale_list.dart';
import 'package:intlx/src/plural/plural.dart';
import 'package:intlx/src/plural/data/af.dart' as symbols_AF;
import 'package:intlx/src/plural/data/am.dart' as symbols_AM;
import 'package:intlx/src/plural/data/ar.dart' as symbols_AR;
import 'package:intlx/src/plural/data/bg.dart' as symbols_BG;
import 'package:intlx/src/plural/data/bn.dart' as symbols_BN;
import 'package:intlx/src/plural/data/ca.dart' as symbols_CA;
import 'package:intlx/src/plural/data/cs.dart' as symbols_CS;
import 'package:intlx/src/plural/data/da.dart' as symbols_DA;
import 'package:intlx/src/plural/data/de.dart' as symbols_DE;
import 'package:intlx/src/plural/data/el.dart' as symbols_EL;
import 'package:intlx/src/plural/data/en.dart' as symbols_EN;
import 'package:intlx/src/plural/data/es.dart' as symbols_ES;
import 'package:intlx/src/plural/data/et.dart' as symbols_ET;
import 'package:intlx/src/plural/data/eu.dart' as symbols_EU;
import 'package:intlx/src/plural/data/fa.dart' as symbols_FA;
import 'package:intlx/src/plural/data/fi.dart' as symbols_FI;
import 'package:intlx/src/plural/data/fil.dart' as symbols_FIL;
import 'package:intlx/src/plural/data/fr.dart' as symbols_FR;
import 'package:intlx/src/plural/data/gl.dart' as symbols_GL;
import 'package:intlx/src/plural/data/gsw.dart' as symbols_GSW;
import 'package:intlx/src/plural/data/gu.dart' as symbols_GU;
import 'package:intlx/src/plural/data/he.dart' as symbols_HE;
import 'package:intlx/src/plural/data/hi.dart' as symbols_HI;
import 'package:intlx/src/plural/data/hr.dart' as symbols_HR;
import 'package:intlx/src/plural/data/hu.dart' as symbols_HU;
import 'package:intlx/src/plural/data/id.dart' as symbols_ID;
import 'package:intlx/src/plural/data/in.dart' as symbols_IN;
import 'package:intlx/src/plural/data/is.dart' as symbols_IS;
import 'package:intlx/src/plural/data/it.dart' as symbols_IT;
import 'package:intlx/src/plural/data/iw.dart' as symbols_IW;
import 'package:intlx/src/plural/data/ja.dart' as symbols_JA;
import 'package:intlx/src/plural/data/kn.dart' as symbols_KN;
import 'package:intlx/src/plural/data/ko.dart' as symbols_KO;
import 'package:intlx/src/plural/data/ln.dart' as symbols_LN;
import 'package:intlx/src/plural/data/lt.dart' as symbols_LT;
import 'package:intlx/src/plural/data/lv.dart' as symbols_LV;
import 'package:intlx/src/plural/data/ml.dart' as symbols_ML;
import 'package:intlx/src/plural/data/mr.dart' as symbols_MR;
import 'package:intlx/src/plural/data/ms.dart' as symbols_MS;
import 'package:intlx/src/plural/data/mt.dart' as symbols_MT;
import 'package:intlx/src/plural/data/nl.dart' as symbols_NL;
import 'package:intlx/src/plural/data/no.dart' as symbols_NO;
import 'package:intlx/src/plural/data/or.dart' as symbols_OR;
import 'package:intlx/src/plural/data/pl.dart' as symbols_PL;
import 'package:intlx/src/plural/data/pt.dart' as symbols_PT;
import 'package:intlx/src/plural/data/ro.dart' as symbols_RO;
import 'package:intlx/src/plural/data/ru.dart' as symbols_RU;
import 'package:intlx/src/plural/data/sk.dart' as symbols_SK;
import 'package:intlx/src/plural/data/sl.dart' as symbols_SL;
import 'package:intlx/src/plural/data/sq.dart' as symbols_SQ;
import 'package:intlx/src/plural/data/sr.dart' as symbols_SR;
import 'package:intlx/src/plural/data/sv.dart' as symbols_SV;
import 'package:intlx/src/plural/data/sw.dart' as symbols_SW;
import 'package:intlx/src/plural/data/ta.dart' as symbols_TA;
import 'package:intlx/src/plural/data/te.dart' as symbols_TE;
import 'package:intlx/src/plural/data/th.dart' as symbols_TH;
import 'package:intlx/src/plural/data/tl.dart' as symbols_TL;
import 'package:intlx/src/plural/data/tr.dart' as symbols_TR;
import 'package:intlx/src/plural/data/uk.dart' as symbols_UK;
import 'package:intlx/src/plural/data/ur.dart' as symbols_UR;
import 'package:intlx/src/plural/data/vi.dart' as symbols_VI;
import 'package:intlx/src/plural/data/zh.dart' as symbols_ZH;
import 'package:intlx/src/plural/data/zu.dart' as symbols_ZU;

part 'package:intlx/src/plural/plural_all_data_constant.dart';
part 'package:intlx/src/plural/plural_locale_data_constants.dart';
