// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "intlx/tool/relative_time/code_build.dart"

/// Exposes [LocaleData] constants for use with [DurationFormat] and/or [AgeFormat].
/// For example:
///     import 'package:intlx/relative_time_locale_data.dart' as relative_time_data;
///     main() {
///       relative_time_data.EN.load();
///       relative_time_data.DE.load();
///       // do something with [DurationFormat] and/or [AgeFormat].
///     }
library intlx.relative_time_locale_data;

import 'package:intlx/intlx.dart';
import 'package:intlx/src/locale_data_impl.dart';
import 'package:intlx/src/symbols_map.dart';
import 'package:intlx/src/relative_time/relative_time_locale_list.dart';
import 'package:intlx/src/relative_time/relative_time_symbols.dart';
import 'package:intlx/plural_locale_data.dart' as plural_locale_data;
import 'package:intlx/src/relative_time/data/AF.dart' as symbols_AF;
import 'package:intlx/src/relative_time/data/AM.dart' as symbols_AM;
import 'package:intlx/src/relative_time/data/AR.dart' as symbols_AR;
import 'package:intlx/src/relative_time/data/BG.dart' as symbols_BG;
import 'package:intlx/src/relative_time/data/BN.dart' as symbols_BN;
import 'package:intlx/src/relative_time/data/CA.dart' as symbols_CA;
import 'package:intlx/src/relative_time/data/CS.dart' as symbols_CS;
import 'package:intlx/src/relative_time/data/DA.dart' as symbols_DA;
import 'package:intlx/src/relative_time/data/DE.dart' as symbols_DE;
import 'package:intlx/src/relative_time/data/EL.dart' as symbols_EL;
import 'package:intlx/src/relative_time/data/EN.dart' as symbols_EN;
import 'package:intlx/src/relative_time/data/ES.dart' as symbols_ES;
import 'package:intlx/src/relative_time/data/ES_419.dart' as symbols_ES_419;
import 'package:intlx/src/relative_time/data/ET.dart' as symbols_ET;
import 'package:intlx/src/relative_time/data/EU.dart' as symbols_EU;
import 'package:intlx/src/relative_time/data/FA.dart' as symbols_FA;
import 'package:intlx/src/relative_time/data/FI.dart' as symbols_FI;
import 'package:intlx/src/relative_time/data/FIL.dart' as symbols_FIL;
import 'package:intlx/src/relative_time/data/FR.dart' as symbols_FR;
import 'package:intlx/src/relative_time/data/FR_CA.dart' as symbols_FR_CA;
import 'package:intlx/src/relative_time/data/GL.dart' as symbols_GL;
import 'package:intlx/src/relative_time/data/GSW.dart' as symbols_GSW;
import 'package:intlx/src/relative_time/data/GU.dart' as symbols_GU;
import 'package:intlx/src/relative_time/data/HE.dart' as symbols_HE;
import 'package:intlx/src/relative_time/data/HI.dart' as symbols_HI;
import 'package:intlx/src/relative_time/data/HR.dart' as symbols_HR;
import 'package:intlx/src/relative_time/data/HU.dart' as symbols_HU;
import 'package:intlx/src/relative_time/data/ID.dart' as symbols_ID;
import 'package:intlx/src/relative_time/data/IN.dart' as symbols_IN;
import 'package:intlx/src/relative_time/data/IS.dart' as symbols_IS;
import 'package:intlx/src/relative_time/data/IT.dart' as symbols_IT;
import 'package:intlx/src/relative_time/data/IW.dart' as symbols_IW;
import 'package:intlx/src/relative_time/data/JA.dart' as symbols_JA;
import 'package:intlx/src/relative_time/data/KN.dart' as symbols_KN;
import 'package:intlx/src/relative_time/data/KO.dart' as symbols_KO;
import 'package:intlx/src/relative_time/data/LN.dart' as symbols_LN;
import 'package:intlx/src/relative_time/data/LT.dart' as symbols_LT;
import 'package:intlx/src/relative_time/data/LV.dart' as symbols_LV;
import 'package:intlx/src/relative_time/data/ML.dart' as symbols_ML;
import 'package:intlx/src/relative_time/data/MR.dart' as symbols_MR;
import 'package:intlx/src/relative_time/data/MS.dart' as symbols_MS;
import 'package:intlx/src/relative_time/data/MT.dart' as symbols_MT;
import 'package:intlx/src/relative_time/data/NL.dart' as symbols_NL;
import 'package:intlx/src/relative_time/data/NO.dart' as symbols_NO;
import 'package:intlx/src/relative_time/data/OR.dart' as symbols_OR;
import 'package:intlx/src/relative_time/data/PL.dart' as symbols_PL;
import 'package:intlx/src/relative_time/data/PT.dart' as symbols_PT;
import 'package:intlx/src/relative_time/data/RO.dart' as symbols_RO;
import 'package:intlx/src/relative_time/data/RU.dart' as symbols_RU;
import 'package:intlx/src/relative_time/data/SK.dart' as symbols_SK;
import 'package:intlx/src/relative_time/data/SL.dart' as symbols_SL;
import 'package:intlx/src/relative_time/data/SQ.dart' as symbols_SQ;
import 'package:intlx/src/relative_time/data/SR.dart' as symbols_SR;
import 'package:intlx/src/relative_time/data/SV.dart' as symbols_SV;
import 'package:intlx/src/relative_time/data/SW.dart' as symbols_SW;
import 'package:intlx/src/relative_time/data/TA.dart' as symbols_TA;
import 'package:intlx/src/relative_time/data/TE.dart' as symbols_TE;
import 'package:intlx/src/relative_time/data/TH.dart' as symbols_TH;
import 'package:intlx/src/relative_time/data/TL.dart' as symbols_TL;
import 'package:intlx/src/relative_time/data/TR.dart' as symbols_TR;
import 'package:intlx/src/relative_time/data/UK.dart' as symbols_UK;
import 'package:intlx/src/relative_time/data/UR.dart' as symbols_UR;
import 'package:intlx/src/relative_time/data/VI.dart' as symbols_VI;
import 'package:intlx/src/relative_time/data/ZH.dart' as symbols_ZH;
import 'package:intlx/src/relative_time/data/ZH_CN.dart' as symbols_ZH_CN;
import 'package:intlx/src/relative_time/data/ZH_HK.dart' as symbols_ZH_HK;
import 'package:intlx/src/relative_time/data/ZH_TW.dart' as symbols_ZH_TW;
import 'package:intlx/src/relative_time/data/ZU.dart' as symbols_ZU;

part 'package:intlx/src/relative_time/relative_time_all_data_constant.dart';
part 'package:intlx/src/relative_time/relative_time_locale_data_constants.dart';


