/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_az;

import '../plural.dart';

final symbols = new PluralLocaleImpl('az', (int n) {
return PluralCategory.OTHER;
  });
