/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_symbols_az;

import 'package:intlx/src/plural/plural.dart';

final symbols = new PluralLocaleImpl('az', (int n) {
return PluralCategory.OTHER;
  });
