/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/locale_build.dart"

library plural_symbols_cs;

import 'package:intlx/src/plural/plural.dart';

final symbols = new PluralLocaleImpl('cs', (int n) {
if(n == 1) return PluralCategory.ONE;
else if((range(3, 2).contains(n))) return PluralCategory.FEW;
else return PluralCategory.OTHER;
  });
