/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_cy;

import '../plural.dart';

final symbols = new PluralLocaleImpl('cy', (int n) {
if(n == 0) return PluralCategory.ZERO;
else if(n == 1) return PluralCategory.ONE;
else if(n == 2) return PluralCategory.TWO;
else if(n == 3) return PluralCategory.FEW;
else if(n == 6) return PluralCategory.MANY;
else return PluralCategory.OTHER;
  });
