/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_fa;

import '../plural.dart';

final symbols = new PluralLocaleImpl('fa', (int n) {
return PluralCategory.OTHER;
  });
