/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_symbols_fr;

import 'package:intlx/src/plural/plural.dart';

final symbols = new PluralLocaleImpl('fr', (int n) {
if(((n >= 0 && n <= 2)) && n != 2) return PluralCategory.ONE;
else return PluralCategory.OTHER;
  });
