/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/code_build.dart"

library plural_symbols_gl;

import 'package:intlx/src/plural/plural.dart';

final symbols = new PluralLocaleImpl('gl', (int n) {
if(n == 1) return PluralCategory.ONE;
else return PluralCategory.OTHER;
  });
