/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/locale_build.dart"

library plural_symbols_id;

import 'package:intlx/src/plural/plural.dart';

final symbols = new PluralLocaleImpl('id', (int n) {
return PluralCategory.OTHER;
  });
