/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_ii;

import '../plural.dart';

final symbols = new PluralLocaleImpl('ii', (int n) {
return PluralCategory.OTHER;
  });
