/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/locale_build.dart"

library plural_symbols_kde;

import 'package:intlx/src/plural/plural.dart';

final symbols = new PluralLocaleImpl('kde', (int n) {
return PluralCategory.OTHER;
  });
