/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_kea;

import '../plural.dart';

final symbols = new PluralLocaleImpl('kea', (int n) {
return PluralCategory.OTHER;
  });
