/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_km;

import '../plural.dart';

final symbols = new PluralLocaleImpl('km', (int n) {
return PluralCategory.OTHER;
  });
