/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_lag;

import '../plural.dart';

final symbols = new PluralLocaleImpl('lag', (int n) {
if(n == 0) return PluralCategory.ZERO;
else if(((n >= 0 && n <= 2)) && n != 0 && n != 2) return PluralCategory.ONE;
else return PluralCategory.OTHER;
  });
