/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_lo;

import '../plural.dart';

final symbols = new PluralLocaleImpl('lo', (int n) {
return PluralCategory.OTHER;
  });
