/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_mg;

import '../plural.dart';

final symbols = new PluralLocaleImpl('mg', (int n) {
if(([0, 1].contains(n))) return PluralCategory.ONE;
else return PluralCategory.OTHER;
  });
