/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/locale_build.dart"

library plural_symbols_naq;

import 'package:intlx/src/plural/plural.dart';

final symbols = new PluralLocaleImpl('naq', (int n) {
if(n == 1) return PluralCategory.ONE;
else if(n == 2) return PluralCategory.TWO;
else return PluralCategory.OTHER;
  });
