/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_or;

import 'package:intlx/src/plural/plural.dart';

final symbols = new PluralLocaleImpl('or', (int n) {
if(n == 1) return PluralCategory.ONE;
else return PluralCategory.OTHER;
  });
