/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_ps;

import '../plural.dart';

final symbols = new PluralLocaleImpl('ps', (int n) {
if(n == 1) return PluralCategory.ONE;
else return PluralCategory.OTHER;
  });
