/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_ses;

import '../plural.dart';

final symbols = new PluralLocaleImpl('ses', (int n) {
return PluralCategory.OTHER;
  });
