/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_sms;

import '../plural.dart';

final symbols = new PluralLocaleImpl('sms', (int n) {
if(n == 1) return PluralCategory.ONE;
else if(n == 2) return PluralCategory.TWO;
else return PluralCategory.OTHER;
  });
