/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/plural/locale_build.dart"

library plural_symbols_ta;

import 'package:intlx/src/plural/plural.dart';

final symbols = new PluralLocaleImpl('ta', (int n) {
if(n == 1) return PluralCategory.ONE;
else return PluralCategory.OTHER;
  });
