/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_wa;

import 'package:intlx/src/plural/plural.dart';

final symbols = new PluralLocaleImpl('wa', (int n) {
if((range(2, 0).contains(n))) return PluralCategory.ONE;
else return PluralCategory.OTHER;
  });
