/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_wo;

import 'package:intlx/src/plural/plural.dart';

final symbols = new PluralLocaleImpl('wo', (int n) {
return PluralCategory.OTHER;
  });
