/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library plural_symbols_yo;

import '../plural.dart';

final symbols = new PluralLocaleImpl('yo', (int n) {
return PluralCategory.OTHER;
  });
