// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// DO NOT EDIT. This file is autogenerated by script, see
// "package:intl_data_gen/bin/intl_data_gen.dart"

library intlx.relative_time.relative_time_locale_list;

const relativeTimeLocales = const <String> ["bo","br","brx","bs","byn","ca","cch","cgg","chr","cs","cy","da","dav","de","dje","dua","dyo","dz","ebu","ee","el","en","en-Dsrt","en-Dsrt-US","eo","es","es-419","es-AR","es-BO","es-CL","es-CO","es-CR","es-DO","es-EC","es-GT","es-HN","es-MX","es-NI","es-PA","es-PE","es-PR","es-PY","es-SV","es-US","es-UY","es-VE","et","eu","ewo","fa","ff","fi","fil","fo","fr","fr-CA","fur","ga","gaa","gl","gsw","gu","guz","gv","ha","haw","he","hi","hr","hu","hy","ia","id","ig","ii","in","is","it","iw","ja","jmc","ka","kab","kaj","kam","kcg","kde","kea","khq","ki","kk","kl","kln","km","kn","ko","kok","ksb","ksf","ksh","ku","ku-Latn","ku-Latn-SY","ku-Latn-TR","ku-SY","ku-TR","kw","ky","lag","lg","ln","lo","lt","lu","luo","luy","lv","mas","mer","mfe","mg","mgh","mk","ml","mn","mo","mr","ms","mt","mua","my","naq","nb","nd","nds","ne","ne-IN","nl","nmg","nn","no","nr","nso","nus","nyn","oc","om","or","pa","pl","ps","pt","rm","rn","ro","rof","root","ru","rw","rwk","sah","saq","sbp","se","seh","ses","sg","sh","sh-BA","sh-CS","sh-YU","shi","si","sid","sk","sl","sn","so","sq","sr","sr-Latn","sr-Latn-BA","sr-Latn-CS","sr-Latn-ME","sr-Latn-RS","sr-Latn-YU","sr-ME","ss","ssy","st","sv","sw","swc","ta","te","teo","tg","th","ti","tig","tl","tl-PH","tn","to","tr","trv","ts","twq","tzm","uk","ur","uz","vai","ve","vi","vun","wae","wal","xh","xog","yav","yo","zh","zh-HK","zh-Hans-HK","zh-Hans-MO","zh-Hans-SG","zh-Hant","zh-Hant-HK","zh-Hant-MO","zh-Hant-TW","zh-MO","zh-TW","zu"];

