/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_af;

  import 'package:intlx/src/relative_time/relative_time_symbols.dart';
  import 'package:intlx/src/relative_time/locale/af.dart' as relative_time_symbols_af;
    import '../plural/af.dart' as plural_locale_af;

  void init() {
    RelativeTimeSymbols.map['af'] = relative_time_symbols_af.symbols;
      plural_locale_af.init();
  }
  