/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_locale_ar;

  import 'package:intlx/src/relative_time/relative_time_symbols.dart';
  import 'package:intlx/src/relative_time/locale/ar.dart' as relative_time_symbols_ar;
    import '../plural/ar.dart' as plural_locale_ar;

  void init() {
    RelativeTimeSymbols.map['ar'] = relative_time_symbols_ar.symbols;
      plural_locale_ar.init();
  }
  