/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_bn;

  import 'package:intlx/src/relative_time/relative_time_symbols.dart';
  import 'package:intlx/src/relative_time/locale/bn.dart' as relative_time_symbols_bn;
    import '../plural/bn.dart' as plural_locale_bn;

  void init() {
    RelativeTimeSymbols.map['bn'] = relative_time_symbols_bn.symbols;
      plural_locale_bn.init();
  }
  