/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_ca;

import '../../src/internal.dart';
import '../../src/relative_time/locale/ca.dart' as relative_time_symbols_ca;
import '../plural/ca.dart' as plural_locale_ca;

void init() {
  registerSymbols(relative_time_symbols_ca.locale);
  plural_locale_ca.init();
}
