/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_da;

import '../../src/internal.dart';
import '../../src/relative_time/locale/da.dart' as relative_time_symbols_da;
import '../plural/da.dart' as plural_locale_da;

void init() {
  registerSymbols(relative_time_symbols_da.locale);
  plural_locale_da.init();
}
