/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_locale_de_AT;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/relative_time/symbols.dart';
  import 'package:intlx/src/relative_time/locale/de_AT.dart' as relative_time_symbols_de_AT;
    import '../plural/de.dart' as plural_locale_de;

  void init() {
    RelativeTimeSymbols.map['de_AT'] = relative_time_symbols_de_AT.symbols;
      plural_locale_de.init();
  }
  