/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_de_CH;

import '../../src/internal.dart';
import '../../src/relative_time/locale/de_CH.dart' as relative_time_symbols_de_CH;
import '../plural/de.dart' as plural_locale_de;

void init() {
  registerSymbols(relative_time_symbols_de_CH.locale);
  plural_locale_de.init();
}
