/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_de_CH;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';
import 'package:intlx/src/relative_time/locale/de_CH.dart' as relative_time_symbols_de_CH;
    import '../plural/de.dart' as plural_locale_de;

void init() {
    RelativeTimeSymbols.map['de_CH'] = relative_time_symbols_de_CH.symbols;
      plural_locale_de.init();
}
  