/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/relative_time/locale_build.dart"

library relative_time_locale_en;

  import 'package:intlx/src/relative_time/relative_time_symbols.dart';
  import 'package:intlx/src/relative_time/locale/en.dart' as relative_time_symbols_en;
    import '../plural/en.dart' as plural_locale_en;

  void init() {
    RelativeTimeSymbols.map['en'] = relative_time_symbols_en.symbols;
      plural_locale_en.init();
  }
  