/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_en_AU;

import '../../src/internal.dart';
import '../../src/relative_time/locale/en_AU.dart' as relative_time_symbols_en_AU;
import '../plural/en.dart' as plural_locale_en;

void init() {
  registerSymbols(relative_time_symbols_en_AU.locale);
  plural_locale_en.init();
}
