/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_locale_en_IN;

  import '../../src/internal.dart';
  import 'package:intlx/src/relative_time/locale/en_IN.dart' as relative_time_symbols_en_IN;
    import '../plural/en.dart' as plural_locale_en;
  
  void init() {
    RelativeTimeSymbols.map['en_IN'] = relative_time_symbols_en_IN.symbols;
      plural_locale_en.init();
  }
  