/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_en_US;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';
import 'package:intlx/src/relative_time/locale/en_US.dart' as relative_time_symbols_en_US;
    import '../plural/en.dart' as plural_locale_en;

void init() {
    RelativeTimeSymbols.map['en_US'] = relative_time_symbols_en_US.symbols;
      plural_locale_en.init();
}
  