/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_locale_en_ZA;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/relative_time/symbols.dart';
  import 'package:intlx/src/relative_time/locale/en_ZA.dart' as relative_time_symbols_en_ZA;
    import '../plural/en.dart' as plural_locale_en;

  void init() {
    RelativeTimeSymbols.map['en_ZA'] = relative_time_symbols_en_ZA.symbols;
      plural_locale_en.init();
  }
  