/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_es;

import '../../src/internal.dart';
import '../../src/relative_time/locale/es.dart' as relative_time_symbols_es;
import '../plural/es.dart' as plural_locale_es;

void init() {
  registerSymbols(relative_time_symbols_es.locale);
  plural_locale_es.init();
}
