/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_et;

import '../../src/internal.dart';
import '../../src/relative_time/locale/et.dart' as relative_time_symbols_et;
import '../plural/et.dart' as plural_locale_et;

void init() {
  registerSymbols(relative_time_symbols_et.locale);
  plural_locale_et.init();
}
