/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_eu;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';
import 'package:intlx/src/relative_time/locale/eu.dart' as relative_time_symbols_eu;
    import '../plural/eu.dart' as plural_locale_eu;

void init() {
    RelativeTimeSymbols.map['eu'] = relative_time_symbols_eu.symbols;
      plural_locale_eu.init();
}
  