// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_fil;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';
import 'package:intlx/src/relative_time/locale/fil.dart' as relative_time_symbols_fil;
    import '../plural/fil.dart' as plural_locale_fil;

void init() {
    RelativeTimeSymbols.map['fil'] = relative_time_symbols_fil.symbols;
      plural_locale_fil.init();
}
  