/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_fil;

  import 'package:intlx/src/relative_time/relative_time_symbols.dart';
  import 'package:intlx/src/relative_time/locale/fil.dart' as relative_time_symbols_fil;
    import '../plural/fil.dart' as plural_locale_fil;

  void init() {
    RelativeTimeSymbols.map['fil'] = relative_time_symbols_fil.symbols;
      plural_locale_fil.init();
  }
  