/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_locale_fr_CA;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/relative_time/symbols.dart';
  import 'package:intlx/src/relative_time/locale/fr_CA.dart' as relative_time_symbols_fr_CA;
    import '../plural/fr.dart' as plural_locale_fr;

  void init() {
    RelativeTimeSymbols.map['fr_CA'] = relative_time_symbols_fr_CA.symbols;
      plural_locale_fr.init();
  }
  