/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_gsw;

import '../../src/internal.dart';
import '../../src/relative_time/locale/gsw.dart' as relative_time_symbols_gsw;
import '../plural/gsw.dart' as plural_locale_gsw;

void init() {
  registerSymbols(relative_time_symbols_gsw.locale);
  plural_locale_gsw.init();
}
