/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_gsw;

  import 'package:intlx/src/relative_time/relative_time_symbols.dart';
  import 'package:intlx/src/relative_time/locale/gsw.dart' as relative_time_symbols_gsw;
    import '../plural/gsw.dart' as plural_locale_gsw;

  void init() {
    RelativeTimeSymbols.map['gsw'] = relative_time_symbols_gsw.symbols;
      plural_locale_gsw.init();
  }
  