/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/relative_time/locale_build.dart"

library relative_time_locale_he;

  import 'package:intlx/src/relative_time/relative_time_symbols.dart';
  import 'package:intlx/src/relative_time/locale/he.dart' as relative_time_symbols_he;
    import '../plural/he.dart' as plural_locale_he;

  void init() {
    RelativeTimeSymbols.map['he'] = relative_time_symbols_he.symbols;
      plural_locale_he.init();
  }
  