// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_hu;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';
import 'package:intlx/src/relative_time/locale/hu.dart' as relative_time_symbols_hu;
    import '../plural/hu.dart' as plural_locale_hu;

void init() {
    RelativeTimeSymbols.map['hu'] = relative_time_symbols_hu.symbols;
      plural_locale_hu.init();
}
  