/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_hu;

import '../../src/internal.dart';
import '../../src/relative_time/locale/hu.dart' as relative_time_symbols_hu;
import '../plural/hu.dart' as plural_locale_hu;

void init() {
  registerSymbols(relative_time_symbols_hu.locale);
  plural_locale_hu.init();
}
