/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_in;

import '../../src/internal.dart';
import '../../src/relative_time/locale/in.dart' as relative_time_symbols_in;
import '../plural/in.dart' as plural_locale_in;

void init() {
  registerSymbols(relative_time_symbols_in.locale);
  plural_locale_in.init();
}
