/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_locale_in;

  import 'package:intlx/src/relative_time/relative_time_symbols.dart';
  import 'package:intlx/src/relative_time/locale/in.dart' as relative_time_symbols_in;
    import '../plural/in.dart' as plural_locale_in;

  void init() {
    RelativeTimeSymbols.map['in'] = relative_time_symbols_in.symbols;
      plural_locale_in.init();
  }
  