/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_iw;

import '../../src/internal.dart';
import '../../src/relative_time/locale/iw.dart' as relative_time_symbols_iw;
import '../plural/iw.dart' as plural_locale_iw;

void init() {
  registerSymbols(relative_time_symbols_iw.locale);
  plural_locale_iw.init();
}
