/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_locale_kn;

  import '../../src/internal.dart';
  import 'package:intlx/src/relative_time/locale/kn.dart' as relative_time_symbols_kn;
    import '../plural/kn.dart' as plural_locale_kn;
  
  void init() {
    RelativeTimeSymbols.map['kn'] = relative_time_symbols_kn.symbols;
      plural_locale_kn.init();
  }
  