/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_ko;

import '../../src/internal.dart';
import '../../src/relative_time/locale/ko.dart' as relative_time_symbols_ko;
import '../plural/ko.dart' as plural_locale_ko;

void init() {
  registerSymbols(relative_time_symbols_ko.locale);
  plural_locale_ko.init();
}
