/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_locale_ln;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/relative_time/symbols.dart';
  import 'package:intlx/src/relative_time/locale/ln.dart' as relative_time_symbols_ln;
    import '../plural/ln.dart' as plural_locale_ln;

  void init() {
    RelativeTimeSymbols.map['ln'] = relative_time_symbols_ln.symbols;
      plural_locale_ln.init();
  }
  