/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_locale_lv;

  import 'package:intlx/src/relative_time/relative_time_symbols.dart';
  import 'package:intlx/src/relative_time/locale/lv.dart' as relative_time_symbols_lv;
    import '../plural/lv.dart' as plural_locale_lv;

  void init() {
    RelativeTimeSymbols.map['lv'] = relative_time_symbols_lv.symbols;
      plural_locale_lv.init();
  }
  