/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_mt;

import '../../src/internal.dart';
import '../../src/relative_time/locale/mt.dart' as relative_time_symbols_mt;
import '../plural/mt.dart' as plural_locale_mt;

void init() {
  registerSymbols(relative_time_symbols_mt.locale);
  plural_locale_mt.init();
}
