// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_nl;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';
import 'package:intlx/src/relative_time/locale/nl.dart' as relative_time_symbols_nl;
    import '../plural/nl.dart' as plural_locale_nl;

void init() {
    RelativeTimeSymbols.map['nl'] = relative_time_symbols_nl.symbols;
      plural_locale_nl.init();
}
  