/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_no;

import '../../src/internal.dart';
import '../../src/relative_time/locale/no.dart' as relative_time_symbols_no;
import '../plural/no.dart' as plural_locale_no;

void init() {
  registerSymbols(relative_time_symbols_no.locale);
  plural_locale_no.init();
}
