/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_locale_no;

  import 'package:intlx/src/relative_time/relative_time_symbols.dart';
  import 'package:intlx/src/relative_time/locale/no.dart' as relative_time_symbols_no;
    import '../plural/no.dart' as plural_locale_no;

  void init() {
    RelativeTimeSymbols.map['no'] = relative_time_symbols_no.symbols;
      plural_locale_no.init();
  }
  