// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_no;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';
import 'package:intlx/src/relative_time/locale/no.dart' as relative_time_symbols_no;
    import '../plural/no.dart' as plural_locale_no;

void init() {
    RelativeTimeSymbols.map['no'] = relative_time_symbols_no.symbols;
      plural_locale_no.init();
}
  