/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/relative_time/locale_build.dart"

library relative_time_locale_pt;

  import 'package:intlx/src/relative_time/relative_time_symbols.dart';
  import 'package:intlx/src/relative_time/locale/pt.dart' as relative_time_symbols_pt;
    import '../plural/pt.dart' as plural_locale_pt;

  void init() {
    RelativeTimeSymbols.map['pt'] = relative_time_symbols_pt.symbols;
      plural_locale_pt.init();
  }
  