/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_pt_PT;

import '../../src/internal.dart';
import '../../src/relative_time/locale/pt_PT.dart' as relative_time_symbols_pt_PT;
import '../plural/pt.dart' as plural_locale_pt;

void init() {
  registerSymbols(relative_time_symbols_pt_PT.locale);
  plural_locale_pt.init();
}
