/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_ro;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';
import 'package:intlx/src/relative_time/locale/ro.dart' as relative_time_symbols_ro;
    import '../plural/ro.dart' as plural_locale_ro;

void init() {
    RelativeTimeSymbols.map['ro'] = relative_time_symbols_ro.symbols;
      plural_locale_ro.init();
}
  