/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_ro;

import '../../src/internal.dart';
import '../../src/relative_time/locale/ro.dart' as relative_time_symbols_ro;
import '../plural/ro.dart' as plural_locale_ro;

void init() {
  registerSymbols(relative_time_symbols_ro.locale);
  plural_locale_ro.init();
}
