/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_sk;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';
import 'package:intlx/src/relative_time/locale/sk.dart' as relative_time_symbols_sk;
    import '../plural/sk.dart' as plural_locale_sk;

void init() {
    RelativeTimeSymbols.map['sk'] = relative_time_symbols_sk.symbols;
      plural_locale_sk.init();
}
  