/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_sl;

  import 'package:intlx/src/relative_time/relative_time_symbols.dart';
  import 'package:intlx/src/relative_time/locale/sl.dart' as relative_time_symbols_sl;
    import '../plural/sl.dart' as plural_locale_sl;

  void init() {
    RelativeTimeSymbols.map['sl'] = relative_time_symbols_sl.symbols;
      plural_locale_sl.init();
  }
  