/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_locale_sw;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/relative_time/symbols.dart';
  import 'package:intlx/src/relative_time/locale/sw.dart' as relative_time_symbols_sw;
    import '../plural/sw.dart' as plural_locale_sw;

  void init() {
    RelativeTimeSymbols.map['sw'] = relative_time_symbols_sw.symbols;
      plural_locale_sw.init();
  }
  