/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_ta;

import '../../src/internal.dart';
import '../../src/relative_time/locale/ta.dart' as relative_time_symbols_ta;
import '../plural/ta.dart' as plural_locale_ta;

void init() {
  registerSymbols(relative_time_symbols_ta.locale);
  plural_locale_ta.init();
}
