/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_locale_ta;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/relative_time/symbols.dart';
  import 'package:intlx/src/relative_time/locale/ta.dart' as relative_time_symbols_ta;
    import '../plural/ta.dart' as plural_locale_ta;

  void init() {
    RelativeTimeSymbols.map['ta'] = relative_time_symbols_ta.symbols;
      plural_locale_ta.init();
  }
  