/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library relative_time_locale_te;

  import '../../src/internal.dart';
  import 'package:intlx/src/relative_time/locale/te.dart' as relative_time_symbols_te;
    import '../plural/te.dart' as plural_locale_te;
  
  void init() {
    RelativeTimeSymbols.map['te'] = relative_time_symbols_te.symbols;
      plural_locale_te.init();
  }
  