/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_th;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';
import 'package:intlx/src/relative_time/locale/th.dart' as relative_time_symbols_th;
    import '../plural/th.dart' as plural_locale_th;

void init() {
    RelativeTimeSymbols.map['th'] = relative_time_symbols_th.symbols;
      plural_locale_th.init();
}
  