// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// DO NOT EDIT. This file is autogenerated by script, see
/// "<this package>/tool/relative_time/code_build.dart"

library relative_time_locale_th;

import 'package:intlx/src/relative_time/relative_time_symbols.dart';
import 'package:intlx/src/relative_time/locale/th.dart' as relative_time_symbols_th;
    import '../plural/th.dart' as plural_locale_th;

void init() {
    RelativeTimeSymbols.map['th'] = relative_time_symbols_th.symbols;
      plural_locale_th.init();
}
  