/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_tl;

import '../../src/internal.dart';
import '../../src/relative_time/locale/tl.dart' as relative_time_symbols_tl;
import '../plural/tl.dart' as plural_locale_tl;

void init() {
  registerSymbols(relative_time_symbols_tl.locale);
  plural_locale_tl.init();
}
