/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_tr;

import '../../src/internal.dart';
import '../../src/relative_time/locale/tr.dart' as relative_time_symbols_tr;
import '../plural/tr.dart' as plural_locale_tr;

void init() {
  registerSymbols(relative_time_symbols_tr.locale);
  plural_locale_tr.init();
}
