/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_ur;

import '../../src/internal.dart';
import '../../src/relative_time/locale/ur.dart' as relative_time_symbols_ur;
import '../plural/ur.dart' as plural_locale_ur;

void init() {
  registerSymbols(relative_time_symbols_ur.locale);
  plural_locale_ur.init();
}
