/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_zh_HK;

import '../../src/internal.dart';
import '../../src/relative_time/locale/zh_HK.dart' as relative_time_symbols_zh_HK;
import '../plural/zh.dart' as plural_locale_zh;

void init() {
  registerSymbols(relative_time_symbols_zh_HK.locale);
  plural_locale_zh.init();
}
