/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library relative_time_locale_zh_TW;

import '../../src/internal.dart';
import '../../src/relative_time/locale/zh_TW.dart' as relative_time_symbols_zh_TW;
import '../plural/zh.dart' as plural_locale_zh;

void init() {
  registerSymbols(relative_time_symbols_zh_TW.locale);
  plural_locale_zh.init();
}
