/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library de;

import '../symbols.dart';

const RelativeTimeSymbols locale = const RelativeTimeSymbols(
  name: "de",
  past: "vor %s",
  future: "in %s",
  units: const {
    "SECOND": const ["ein paar Sekunden"],
    "MINUTE": const ["einer Minute","%d Minuten"],
    "HOUR": const ["einer Stunde","%d Stunden"],
    "DAY": const ["einem Tag","%d Tagen"],
    "MONTH": const ["einem Monat","%d Monaten"],
    "YEAR": const ["einem Jahr","%d Jahren"]});

