/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"


#library("relative_time_fr_CA_symbols");

#import("../symbols.dart");

const RelativeTimeSymbols locale = const RelativeTimeSymbols(
  name: "fr_CA",
  past: "il y a %s",
  future: "dans %s",
  units: const {
    "SECOND": const ["quelques secondes"],
    "MINUTE": const ["une minute","%d minutes"],
    "HOUR": const ["une heure","%d heures"],
    "DAY": const ["un jour","%d jours"],
    "MONTH": const ["un mois","%d mois"],
    "YEAR": const ["une année","%d années"]});

