/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"

library it;

import '../symbols.dart';

const RelativeTimeSymbols locale = const RelativeTimeSymbols(
  name: "it",
  past: "%s fa",
  future: "in %s",
  units: const {
    "SECOND": const ["secondi"],
    "MINUTE": const ["un minuto","%d minuti"],
    "HOUR": const ["un'ora","%d ore"],
    "DAY": const ["un giorno","%d giorni"],
    "MONTH": const ["un mese","%d mesi"],
    "YEAR": const ["un anno","%d anni"]});

