/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"


#library("relative_time_nl_symbols");

#import("../symbols.dart");

const RelativeTimeSymbols locale = const RelativeTimeSymbols(
  name: "nl",
  past: "for %s siden",
  future: "om %s",
  units: const {
    "SECOND": const ["noen sekunder"],
    "MINUTE": const ["ett minutt","%d minutter"],
    "HOUR": const ["en time","%d timer"],
    "DAY": const ["en dag","%d dager"],
    "MONTH": const ["en måned","%d måneder"],
    "YEAR": const ["ett år","%d år"]});

