/// DO NOT EDIT. This file is autogenerated by script.
/// See "tool/build_locale_libraries.dart"


#library("relative_time_zh_CN_symbols");

#import("../symbols.dart");

const RelativeTimeSymbols locale = const RelativeTimeSymbols(
  name: "zh_CN",
  past: "%s前",
  future: "%s内",
  units: const {
    "SECOND": const ["几秒"],
    "MINUTE": const ["1分钟","%d分钟"],
    "HOUR": const ["1小时","%d小时"],
    "DAY": const ["1天","%d天"],
    "MONTH": const ["1个月","%d个月"],
    "YEAR": const ["1年","%d年"]});

