/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library iterable_symbols_he;

import 'package:intlx/src/iterable/iterable_symbols.dart';

final symbols = new IterableSymbols(    start: '{0}, {1}',
    middle: '{0}, {1}',
    end: '{0} ×-{1}',
    indexed: const {"2":"{0} ×-{1}"});
