/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/code_build.dart"

library iterable_symbols_ml;

import 'package:intlx/src/iterable/iterable_symbols.dart';

final symbols = new IterableSymbols(    start: '{0}, {1}',
    middle: '{0}, {1}',
    end: '{0}, {1} à´à´¨àµà´¨à´¿à´µ',
    indexed: const {"2":"{0} à´àµà´à´¾à´¤àµ {1}"});
