/// DO NOT EDIT. This file is autogenerated by script.
/// See "<this package>/tool/iterable/locale_build.dart"

library iterable_symbols_zh_TW;

import 'package:intlx/src/iterable/iterable_symbols.dart';

final symbols = new IterableSymbols(    start: '{0}ã{1}',
    middle: '{0}ã{1}',
    end: '{0}å{1}',
    indexed: const {"2":"{0}å{1}"});
