/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_bg;

  import 'package:intlx/src/collection/collection_symbols.dart';
  import 'package:intlx/src/collection/locale/bg.dart' as collection_symbols_bg;

  void init() {
  CollectionSymbols.map['bg'] = collection_symbols_bg.symbols;
  }
  