/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_cs;

  import 'package:intlx/src/collection/collection_symbols.dart';
  import 'package:intlx/src/collection/locale/cs.dart' as collection_symbols_cs;

  void init() {
  CollectionSymbols.map['cs'] = collection_symbols_cs.symbols;
  }
  