/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_de;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/collection/symbols.dart';
  import 'package:intlx/src/collection/locale/de.dart' as collection_symbols_de;

  void init() {
  CollectionSymbols.map['de'] = collection_symbols_de.symbols;
  }
  