/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_de_AT;

  import 'package:intlx/src/collection/collection_symbols.dart';
  import 'package:intlx/src/collection/locale/de_AT.dart' as collection_symbols_de_AT;

  void init() {
  CollectionSymbols.map['de_AT'] = collection_symbols_de_AT.symbols;
  }
  