/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_en;

  import '../../src/internal.dart';
  import 'package:intlx/src/collection/locale/en.dart' as collection_symbols_en;
  
  void init() {
  CollectionSymbols.map['en'] = collection_symbols_en.symbols;
  }
  