/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_en_GB;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/collection/symbols.dart';
  import 'package:intlx/src/collection/locale/en_GB.dart' as collection_symbols_en_GB;

  void init() {
  CollectionSymbols.map['en_GB'] = collection_symbols_en_GB.symbols;
  }
  