/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_en_IN;

  import '../../src/internal.dart';
  import 'package:intlx/src/collection/locale/en_IN.dart' as collection_symbols_en_IN;
  
  void init() {
  CollectionSymbols.map['en_IN'] = collection_symbols_en_IN.symbols;
  }
  