/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_en_US;

  import '../../src/internal.dart';
  import 'package:intlx/src/collection/locale/en_US.dart' as collection_symbols_en_US;
  
  void init() {
  CollectionSymbols.map['en_US'] = collection_symbols_en_US.symbols;
  }
  