/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_fr_CA;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/collection/symbols.dart';
  import 'package:intlx/src/collection/locale/fr_CA.dart' as collection_symbols_fr_CA;

  void init() {
  CollectionSymbols.map['fr_CA'] = collection_symbols_fr_CA.symbols;
  }
  