/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_gsw;

  import 'package:intlx/src/collection/collection_symbols.dart';
  import 'package:intlx/src/collection/locale/gsw.dart' as collection_symbols_gsw;

  void init() {
  CollectionSymbols.map['gsw'] = collection_symbols_gsw.symbols;
  }
  