/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_gu;

  import 'package:intlx/src/collection/collection_symbols.dart';
  import 'package:intlx/src/collection/locale/gu.dart' as collection_symbols_gu;

  void init() {
  CollectionSymbols.map['gu'] = collection_symbols_gu.symbols;
  }
  