/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_he;

  import '../../src/internal.dart';
  import 'package:intlx/src/collection/locale/he.dart' as collection_symbols_he;
  
  void init() {
  CollectionSymbols.map['he'] = collection_symbols_he.symbols;
  }
  