/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_hr;

  import 'package:intlx/src/collection/collection_symbols.dart';
  import 'package:intlx/src/collection/locale/hr.dart' as collection_symbols_hr;

  void init() {
  CollectionSymbols.map['hr'] = collection_symbols_hr.symbols;
  }
  