/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_is;

  import 'package:intlx/src/collection/collection_symbols.dart';
  import 'package:intlx/src/collection/locale/is.dart' as collection_symbols_is;

  void init() {
  CollectionSymbols.map['is'] = collection_symbols_is.symbols;
  }
  