/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_ln;

  import 'package:intlx/src/collection/collection_symbols.dart';
  import 'package:intlx/src/collection/locale/ln.dart' as collection_symbols_ln;

  void init() {
  CollectionSymbols.map['ln'] = collection_symbols_ln.symbols;
  }
  