/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_mr;

  import '../../src/internal.dart';
  import 'package:intlx/src/collection/locale/mr.dart' as collection_symbols_mr;
  
  void init() {
  CollectionSymbols.map['mr'] = collection_symbols_mr.symbols;
  }
  