/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_ms;

  import '../../src/internal.dart';
  import 'package:intlx/src/collection/locale/ms.dart' as collection_symbols_ms;
  
  void init() {
  CollectionSymbols.map['ms'] = collection_symbols_ms.symbols;
  }
  