/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_no;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/collection/symbols.dart';
  import 'package:intlx/src/collection/locale/no.dart' as collection_symbols_no;

  void init() {
  CollectionSymbols.map['no'] = collection_symbols_no.symbols;
  }
  