/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_pt;

  import 'package:intlx/src/collection/collection_symbols.dart';
  import 'package:intlx/src/collection/locale/pt.dart' as collection_symbols_pt;

  void init() {
  CollectionSymbols.map['pt'] = collection_symbols_pt.symbols;
  }
  