/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_ro;

  import 'package:intlx/src/collection/collection_symbols.dart';
  import 'package:intlx/src/collection/locale/ro.dart' as collection_symbols_ro;

  void init() {
  CollectionSymbols.map['ro'] = collection_symbols_ro.symbols;
  }
  