/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_sk;

  import '../../src/internal.dart';
  import 'package:intlx/src/collection/locale/sk.dart' as collection_symbols_sk;
  
  void init() {
  CollectionSymbols.map['sk'] = collection_symbols_sk.symbols;
  }
  