/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_sl;

  import 'package:intlx/src/collection/collection_symbols.dart';
  import 'package:intlx/src/collection/locale/sl.dart' as collection_symbols_sl;

  void init() {
  CollectionSymbols.map['sl'] = collection_symbols_sl.symbols;
  }
  