/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_ta;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/collection/symbols.dart';
  import 'package:intlx/src/collection/locale/ta.dart' as collection_symbols_ta;

  void init() {
  CollectionSymbols.map['ta'] = collection_symbols_ta.symbols;
  }
  