/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_tl;

  import 'package:intlx/src/collection/collection_symbols.dart';
  import 'package:intlx/src/collection/locale/tl.dart' as collection_symbols_tl;

  void init() {
  CollectionSymbols.map['tl'] = collection_symbols_tl.symbols;
  }
  