/// DO NOT EDIT. This file is autogenerated by script.
/// See "intlx/tool/"

library collection_locale_zh_TW;

  import 'package:intlx/src/internal.dart';
  import 'package:intlx/src/collection/symbols.dart';
  import 'package:intlx/src/collection/locale/zh_TW.dart' as collection_symbols_zh_TW;

  void init() {
  CollectionSymbols.map['zh_TW'] = collection_symbols_zh_TW.symbols;
  }
  